### ISSUE TITLE
Remote unlocking of native encrypted ZFS root  in Ubuntu

### ISSUE THREAD

**Issue by dynerose** [openzfs/zfs#10017]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	|  19.04,19.10,20.04
Linux Kernel	|  5.4.0-14-generic
Architecture	| AMD64
ZFS Version	| 0.8.3-1ubuntu3
SPL Version	| 0.8.3-1ubuntu3

### 
I needed native encrypt zfs root on Ubuntu and remote ssh password unlock. (similar to Remote unlocking of LUKS-encrypted root) .
I was looking for a solution but couldn't find it so I wrote it instead.

### Install a native encrypt zfs root (in Ubuntu 19.04/19.10/20.04) with ext4 boot partition
The steps can be found in the document -> 
https://github.com/dynerose/Remote-unlock-native-ZFS/blob/master/install.bash 
and the dropbear setup in -> 
https://github.com/dynerose/Remote-unlock-native-ZFS/blob/master/RemoteUnlock
and the solution in -> 
https://github.com/dynerose/Remote-unlock-native-ZFS/blob/master/crypt_unlock.sh. 
The file must be here -> /usr/share/initramfs-tools/hooks/crypt_unlock.sh

This solution works but not very nice.

**Comment by andrey42** [comment]
There is a [new pull request](https://github.com/zfsonlinux/zfs/pull/10027) adding this feature for Debian-based distros, once it will be approved for merge and released, all you will need to do is to install dropbear-initramfs and setup encrypted root partition. Then upon the system boot, you will be prompted for encryption password once you login into dropbear. If no dropbear module present in initramfs, script silently fails to the older encryption input methods.
For the dracut I believe similar feature can be developed, but sadly I have had little exposure to dracut features.

**Comment by pgassmann** [comment]
@dynerose Where can I find information how to setup Ubuntu with encrypted zfs root? Which sources did you use for your script? I would like to setup my laptop with native zfs encryption.

**Comment by andrey42** [comment]
Use [zfs-installer](https://github.com/saveriomiroddi/zfs-installer) script.

**Comment by berenddeboer** [comment]
It seems native ZFS encryption is in 21.10, at least from my reading of `zfs-setup`. Key is stored in luks encrypted zvol, that gets unlocked at boot.

**Comment by terem42** [comment]
Is you mean fresh Ubuntu 21.10, then Its not relevant to this case. The purpose of this feature was to allow remote unlocking of encrypted partition without storing key material on the machine, otherwise it fatally compromises the  security.  Full boot sequence includes small script (not included into distribition, this part is left up to the specifics of the remote keystore used ) which requests remote key store about key material via SSL connection with verifies certificate authority, and if remote keystore considers the host can boot, key token is transmitted and boot sequence is resumed. IMHO the only useable alternative for storing key on machine (for workstations having ZFS as root) is to use TPM module to store key material, combined with secure boot to prevent trojans and keyloggers injection into boot partitions , all others provide only false sence of "security".
