### ISSUE TITLE
Observations/Suggestions: Nested ZFS with Compression and Encryption

### ISSUE THREAD

**Issue by realcarbonneau** [openzfs/zfs#10159]
On Debian 10 Buster

```
zfs-0.8.3-1~bpo10+1
zfs-kmod-0.8.3-1~bpo10+1
```

A few useful observations:

Nested ZFS:
1) ZPOOL/ZFS (compression=on) on a file that is nested in a ZPOOL/ZFS (compression=on|gzip) hangs/freezes.
2) ZPOOL/ZFS (compression=on) that is nested in a ZPOOL/ZVOL (compression=on|gzip) disregards the child ZFS compression.  I assume it knows that it is nested and there are exceptions coded to avoid it hanging/freezing.
3) ZPOOL/ZFS (compression=on-lz4) that is a seperate file, then the file is copied onto another ZPOOL/ZFS (compression=gzip9) achieves approximately the same level of compression as having dedup+gzip9 on the original ZPOOL with a variety of filesystems and VMs, multiple VMs with the similar OS, thus dedup is effective.  
3a) It seems that the compression is limited to each zvol/zfs and only dedup is across zvols/zfs in the same pool.  Nesting the complete zpool file into another zpool/zfs with gzip9 presumably compresses across all the VMs in the same way that dedup does.  This might be an easy gain for ZFS to have a compression that spans across decendent zvol/zfs without the overhead of dedup.
3b) Not having compression=on-lz4 the child/nested zpool results in much worse compression by the parent gzip9.  Presumably because more data in the child means more overhead and checksums, etc.

Encryption:
4) Metadata.  It is really a problem that the metadata of the ZPOOL structure is not encrypted.  A user might have a file system tank/protestphotos (compression=off) and tank/gpstracking (compression=on).  Also, with snapshots it is very clear the level of activity and dates occurring on each filesystem.  This can be easily address with nesting a zfs in an encrypted zfs.  At the moment, the safest way is by having non-encrypted ZFS in a file or vol nested in another ZFS with encryption and snapshots. Thus only the top level snapshots and one tank are visible without the passphrase. Since this already works with nesting, it might not be that difficult to get working natively.

It matters because ideally we keep the compression, robustness and encryption all together.  Nesting non-natively has a variety of negative side effects, an example is LUKS on a ZFS that is replicating.

Summary:
Ideally, it would be nice to have compression and encryption root (base of descendants, not necessarily the root of the zfs pool) to maximize the benefits of global dedup style compression and increased privacy.

Some of these features might already be in the next versions of ZFS, I have not tested further than the current Debian stable.

**Comment by GregorKopka** [comment]
In case I understood that all correctly: 

Only the 1. part (pool backed by zfs hanging/freezing) is an actual issue. Please open an issue with the relevant stack traces etc. 

2. Compression will only happen in case the data shrinks through compression, which is not the case with already compressed data (else we could simply repeat compression recursively, which would be nice but violate certain constraints of our universe).

3./4. No idea what you are talking about as it is not clear what is child, original, whatnot. While a nice drawing might help shed some light on this: Compression is per block, that is by design and can not change without having to discard most of the features that make ZFS... ZFS.

Though there is an open issue arguing that dedup should work across a whole encryption root, if requested by the admin.
