### ISSUE TITLE
[setup/docs41] Debian Buster Root on ZFS: Step 3.2 - cannot mount

### ISSUE THREAD

**Issue by mabra** [openzfs/zfs#10276]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	| 

### Describe the problem you're observing
The instruction under 3.2 are:

zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/debian
zfs mount rpool/ROOT/debian

zfs create -o canmount=noauto -o mountpoint=/boot bpool/BOOT/debian
zfs mount bpool/BOOT/debian

This is not working for me, the bootpool cannot be mounted,
because there ist really a mounted /boot from the running system.
If I would change the mountpoint like this:
zfs set mountpoint=/mnt/boot bpool/BOOT/debian
the resiult would be the same:
```cannot mount '/mnt': directory is not empty```
Additionally, this should happen using the chroot, or not??

**Comment by johnnyjacq16** [comment]
This is NOT a bug in zfs and is a normal zfs behaviour.
Your change of the mountpoint to `/mnt/boot bpool/BOOT/debian` is not accurate and will cause problems boot the system up.
You need to follow the Debian Buster Root on ZFS instructions carefully do not deviate.

When you see the error `cannot mount '/mnt': directory is not empty ` it means that you need to remove any files that is in the the /mnt directory, so that the dataset can be mounted.
So go to the /mnt directory remove any files that is the `/mnt `directory (Backup any files that you need first before remove file) then mount the dataset again.

**Comment by mabra** [comment]
Hallo!

Thank your for your reply!

 

If one follows the instructions, I just write the short:

- reset/prepare your disks

- create two pool (rpool/bool) - BOTH mounted with "-R /mnt"

  (this leads to an empty "/mnt" directory, right?)

- create several filesystems, "zfs create rpool/srv",
  which lead to a directory inside "/mnt" -> "/mnt/srv"

- then you will reach step: 3.1 and 3.2

- the latter's mount's

> zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/debian

zfs mount rpool/ROOT/debian<

will find existings directory inside "/mnt" and will fail
(for my example, because of "/mnt" has "srv" [/mnt/srv]).

 

I started over using sections 3.1/3.2 directly after creating
the pools (and make "zfs create rpool/srv …" later) and everything
is ok.

 

The given "-o canmount=off" effects only the filesystem,
which is implicitely created.

 

Best reagdrs,
Manfred

**Comment by johnnyjacq16** [comment]
Follows the instructions in short:
(To start your `/mnt` directory should be empty no files or directories)
- reset/prepare your disks
- create two pool (rpool/bool) - BOTH mounted with "-R /mnt"
(Note: the creation of the pool does not mount the rpool dataset due to the` canmount=off `parameter)

(After you created both pools you need to mount them immediately afterwards, with the commands below ): 
`zfs create -o canmount=off -o mountpoint=none rpool/ROOT`
`zfs create -o canmount=off -o mountpoint=none bpool/BOOT`

`zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/debian`
`zfs mount rpool/ROOT/debian`

`zfs create -o canmount=noauto -o mountpoint=/boot bpool/BOOT/debian`
`zfs mount bpool/BOOT/debian`

Then after you created ensured that all the above is mounted then continue:
To ensure that the dataset is mounted run the following command.
`df -Th /mnt `should show  `rpool/ROOT/debian`
`df -Th /mnt/boot `should show `bpool/BOOT/debian`
Then:
- create several filesystems, "zfs create rpool/srv",
