### ISSUE TITLE
meta: move to or explicitly endorse semantic versioning for release versions

### ISSUE THREAD

**Issue by gdevenyi** [openzfs/zfs#10334]
**issue template ignored as non-applicable**

Semantic versioning refers to using a versioning scheme that gives users a clear understanding of compatibility and changes at a glance:
https://semver.org/

In particular:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards compatible manner, and
> PATCH version when you make backwards compatible bug fixes.

For example, we followed 0.8.3 by 0.8.4, which I would generally consider a bug-fix increment (and advocated for limiting that scope in the patch series discussion), however the following items in the patch I would consider "add functionality in a backwards compatible manner"
https://github.com/openzfs/zfs/pull/10029
https://github.com/openzfs/zfs/pull/9749

^There is definitely a discussion to be had on if these are bugfixes by the semver definition or not.

Replying to a request for a new feature patch to be added, one developer commented as such:
https://github.com/openzfs/zfs/pull/10209#issuecomment-627593162 referring to add a new feature for 0.8.5

I wanted here, to kickstart a discussion on whether OpenZFS should explicitly endorse semantic versioning for releases, to improve the clarity on what patches should be merged for a given point release. Once such clarity is achieved, a future discussion on releases could include a policy to release PATCH version changes more frequently as they would be "low risk" upgrades for users.

**Comment by ideologysec** [comment]
My understandings/thoughts:
I have not seen any discussion regarding *why* the versioning scheme is changing from "0.7.x, 0.8.x, etc" to "2.0" this year, but I am given to understand this is happening and the major shift there is the transition of FreeBSD to use the Linux upstream, with OpenZFS 3.0 possibly including macOS support, though with all of the changes coming to the Mac hardware platform, who knows what will actually be possible.

- I would expect versions 2.a through 2.z to be feature releases but no major breaking changes
- a bump from e.g. 2.9 to 2.10 seems appropriate for the encryption PRs you linked
- hypothetically, if bitslicing NEON SIMD AES/GCM code was added to improve arm64 performance, would/should that be 2.10.1 because amr64 performance was "fixed", or should it be 2.11?
- are performance improvements features, or are they bugfixes?
- how many additions would be grouped under a major.minor update? a single conceptually linked one like encryption? all of the changes and bugfixes that are grouped in things like the 0.8.3 -> 0.8.4 release?
- the easiest transition path would be to do something akin to "moving the decimal", such that 0.8.4 -> 0.8.5 would simply become 2.4 -> 2.5 after the major version # transition to 2.0 this year; getting more granular about semver could itself be a breaking change (albeit a process one instead of a code one) in 3.0.

lastly:
- this is a filesystem, not a piece of software, so "APIs" don't exactly apply; even with say a jump from the 3.x to 4.x series, I would expect nothing that I as a user would need to be aware of or do - no on-disk format changes, no risk of data loss

**Comment by gdevenyi** [comment]
With the introduction of a patch-branch as per https://github.com/openzfs/zfs/issues/10722#issuecomment-675089721

What remains is a clear policy on the versioning numbers and what is acceptable vs not acceptable in such a branch.

**Comment by Ornias1993** [comment]
Preferably this issue is combined with #10756 and both versioning and changelog file creation is (somewhat) automated in one big swoop.

**Comment by gdevenyi** [comment]
This has been covered reasonably well in meetings and some changes to release cycle.
