### ISSUE TITLE
Abysmal performance on empty dataset with relatively low quota

### ISSUE THREAD

**Issue by jdeluyck** [openzfs/zfs#10373]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Debian / Proxmox 6.2
Distribution Version	| Buster (10.4)
Linux Kernel	|  5.4.41-1-pve
Architecture	| x86_64
ZFS Version	| 0.8.4-pve1
SPL Version	| 0.8.4-pve1

### Describe the problem you're observing

Similar to #1668

As [posted on the zfsonlinux discuss mailinglist](https://zfsonlinux.topicbox.com/groups/zfs-discuss/Ta9c9fdd9814245c0-M383a24388a2b4ed297c5f3b8/quota-impact-on-performance-on-empty-dataset), I was seeing abysmal performance on an **empty** small dataset with quota=8gb.

Increasing the dataset quota to something huge (eg. 800gb) 'fixes' the issue. 
Decreasing spa_asize_inflation also remediates the problem

### Describe how to reproduce the problem

Create a new dataset with a relatively low quota (eg. 8gb)
Try to execute a test with fio:

> fio --name test --eta-newline=5s --filename=/rpool/testzfs/test -rw=randwrite --size=500m --io_size=10g -blocksize=4k --ioengine=libaio --fsync=0 --iodepth=1 --direct=1 --numjobs=1 --runtime=60 --group_reporting

Performance is less than 1/22th of the performance gotten when the dataset size is increased.
It is unclear why this is on a dataset without any data - on a dataset that's reaching it's quota I would understand it.

The actual use of spa_asize_inflation is also less than clear - and I couldn't really find much useful documentation on it.

**Comment by shodanshok** [comment]
Hi, the measured slowdown is inflated by the specific `fio` command being run. More specifically, using a relatively small file size (500M) and high io_size (10G), you are basically overwriting data blocks cached in the ARC. This, in turn, would produce much higher performance than what your disks can really provide (in the mailing list you wrote about 650+ MB/s sustained writes, which are impossible to reach with 4x WD REDs in a RAIDZ1 vdev). Side note: using "--direct=1" has currently no effect on ARC behavior. A more "sane" `fio` command is something as the following: `fio --name=test --filename=/tank/test/test.img --rw=randwrite --size=1G` and I am sure it would show lower sustained performance.

That said, the performance impact from the quota is very real, and it is due to ZFS reducint TXG size in order to avoid over-filling the assigned space. But why it does happen on a empty dataset? It seems to be related to the low quota value (8G only) *and* the high `spa_asize_inflation` (24 by default). `spa_asize_inflation` is basically a worst-case space amplification factor that ZFS considers when deciding if/when the quota would be reached by committing the pending TXG. As a single TXG can containg much data, ZFS preemptly reduce the maximum TXG size breaking user data (fed by the ARC) in many smaller transactions, reducing the write efficiency (and speed).

The default 24x asize inflaction is very big and, when facing small quotas, it can lead to facing quota-related TXG restrictions very early; after all, 500M x 24 = 12G, which clearly is over an 8G quota. Expanding the quota *or* reducing `spa_asize_inflation` eliminates the problem.

If not using "copies=3" and RAIDZ3 vdevs, you should be able to safely lower it to 6 or even 4; this should restore all (or a significant part) of the missing performance. Here you can find some tests done on a simple 4x mirrored disks (2x 2-way mirrored vdevs);

```
CMD: fio --name=test --filename=/tank/test/test.img --rw=randwrite --size=1G

RESULTS:
noquota				write: IOPS=9082, BW=35.5MiB/s (37.2MB/s)(1024MiB/28863msec)
quota=4G 			write: IOPS=2873, BW=11.2MiB/s (11.8MB/s)(1024MiB/91214msec)
quota=2G			write: IOPS=1753, BW=7013KiB/s (7182kB/s)(1024MiB/149513msec)
quota=2G+spa_asize_inflation=4	write: IOPS=5853, BW=22.9MiB/s (23.0MB/s)(1024MiB/44781msec)
```

**Comment by dioni21** [comment]
> the performance impact from the quota is very real, and it is due to ZFS reducint TXG size in order to avoid over-filling the assigned space

If I understood correctly, does this mean that it is possible to use more than reserved quota, and this is just a workaround to reduce the possibility?

**Comment by shodanshok** [comment]
Yes, at least this is my understanding.

**Comment by jdeluyck** [comment]
Thanks. That makes it a lot clearer. 
Perhaps this can be added in the documentation somewhere, as it was rather hard to find anything useful about this behaviour. 

I realize that 8gb is relatively small, but for a VM/LXC image not much more might be needed if it's just running some isolated function.

**Comment by shodanshok** [comment]
Well, I always am for more docs. Anyway, as the problem was explained, I suggest you to close this issue.
