### ISSUE TITLE
Are there any way to recover a broken raidz2 pool?

### ISSUE THREAD

**Issue by diodep** [openzfs/zfs#10447]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| Debian 10
Linux Kernel	| 4.19.90
Architecture	| amd64
ZFS Version	| 0.8.3-1
SPL Version	| 0.8.3-1

### Describe the problem you're observing

I mistakenly added a disk to zpool (what I mean is to replace a old disk from pool). And I realize that is a problem. I try to remove this disk from zpool but it said 

cannot remove sdj: invalid config; all top-level vdevs must have the same sector size and not be raidz.

So I try to reboot the system, then zpool can't import:

it said:

One or more drivers are faulted.

I tried zpool import, import -f, import -m, import -fFX but with no luck.

### Describe how to reproduce the problem

zpool add nas_1 sdj

**Comment by rincebrain** [comment]
You're missing a lot of details that would be helpful here, like the output when you try running "zpool import" without arguments and with.

That said, assuming it's the single-disk you accidentally added to the pool instead of using zpool replace, you could try setting the module parameter "zfs_max_missing_tvds" on the zfs module to 1, and then try importing and see how much you can recover from the pool. (You should not keep using the pool if this works, you should copy your data somewhere else and recreate the pool entirely.)

**Comment by diodep** [comment]
> You're missing a lot of details that would be helpful here, like the output when you try running "zpool import" without arguments and with.
> 
> That said, assuming it's the single-disk you accidentally added to the pool instead of using zpool replace, you could try setting the module parameter "zfs_max_missing_tvds" on the zfs module to 1, and then try importing and see how much you can recover from the pool. (You should not keep using the pool if this works, you should copy your data somewhere else and recreate the pool entirely.)

Okay, that helped. I'm exporting data to other disks now. Thank you!
