### ISSUE TITLE
scrub impacts user I/O latency too much

### ISSUE THREAD

**Issue by dechamps** [openzfs/zfs#10535]
Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| Unstable/Sid
Linux Kernel	| 5.7.0-1
Architecture	| amd64
ZFS Version	| 0.8.4-1
SPL Version	| 0.8.4-1

When a scrub is ongoing, normal user I/O slows down to an unacceptable degree (e.g. simple commands take seconds to run). It would be nice if ZFS could better manage I/O priority during scrubs. I don't really care that much how long a scrub takes, as long as it's not too noticeable.

A quick search reveals some potentially useful tunables such as `zfs_scrub_delay` and `zfs_scan_idle` but I can't find these in ZoL. (Maybe they were removed when the new sequential scrubbing system was introduced?) If there are any knobs I can tweak to improve the situation, I'd be interested to know about them.

Below is the output of various commands during the scrub.

```
# zpool status
  pool: zyklos
 state: ONLINE
  scan: scrub in progress since Mon Jul  6 04:00:01 2020
        8.19T scanned at 524M/s, 7.19T issued at 393M/s, 14.0T total
        0B repaired, 51.37% done, 0 days 05:02:33 to go
config:

        NAME                                            STATE     READ WRITE CKSUM
        zyklos                                          ONLINE       0     0     0
          mirror-0                                      ONLINE       0     0     0
            WDC_WD100EFAX-68LHPN0_JEJDSYJM              ONLINE       0     0     0
            WDC_WD100EFAX-68LHPN0_JEJDV5KM              ONLINE       0     0     0
          mirror-1                                      ONLINE       0     0     0
            WDC_WD100EFAX-68LHPN0_JEJEJYYM              ONLINE       0     0     0
            WDC_WD100EFAX-68LHPN0_JEJEDYSM              ONLINE       0     0     0
          mirror-2                                      ONLINE       0     0     0
            WDC_WD100EFAX-68LHPN0_JEJDTW6M              ONLINE       0     0     0
            WDC_WD100EFAX-68LHPN0_JEJEGWKM              ONLINE       0     0     0
        logs
          INTEL_SSDSC2BB800G4_CVWL431501AV800RGN-part4  ONLINE       0     0     0
        cache
          INTEL_SSDSC2BB800G4_CVWL431501AV800RGN-part5  ONLINE       0     0     0

errors: No known data errors
# zpool iostat -v 30
...
                                                  capacity     operations     bandwidth
pool                                            alloc   free   read  write   read  write
----------------------------------------------  -----  -----  -----  -----  -----  -----
zyklos                                          14.0T  13.3T  1.35K    109   650M  3.28M
  mirror                                        4.65T  4.44T    490     36   188M  1.13M
    WDC_WD100EFAX-68LHPN0_JEJDSYJM                  -      -    242     18  94.1M   578K
    WDC_WD100EFAX-68LHPN0_JEJDV5KM                  -      -    248     18  94.3M   578K
  mirror                                        4.68T  4.41T    462     33   182M  1.04M
    WDC_WD100EFAX-68LHPN0_JEJEJYYM                  -      -    232     16  90.9M   530K
    WDC_WD100EFAX-68LHPN0_JEJEDYSM                  -      -    230     16  90.8M   530K
  mirror                                        4.70T  4.40T    427     38   280M  1.05M
    WDC_WD100EFAX-68LHPN0_JEJDTW6M                  -      -    213     19   140M   539K
    WDC_WD100EFAX-68LHPN0_JEJEGWKM                  -      -    214     19   140M   539K
logs                                                -      -      -      -      -      -
  INTEL_SSDSC2BB800G4_CVWL431501AV800RGN-part4  1.72M  31.7G      0      0      0  63.1K
cache                                               -      -      -      -      -      -
  INTEL_SSDSC2BB800G4_CVWL431501AV800RGN-part5  29.1G  98.9G      0     66  15.1K  7.89M
----------------------------------------------  -----  -----  -----  -----  -----  -----
# iostat -x -m 30
...
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.51    1.07   12.23   57.41    0.00   28.79

Device            r/s     rMB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wMB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dMB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
sda            215.13    139.43     0.07   0.03   26.59   663.68   19.27      0.53     0.00   0.00    1.08    27.96    0.00      0.00     0.00   0.00    0.00     0.00    0.40   23.25    5.75  97.17
sdb              0.47      0.01     0.00   0.00    0.21    32.29   67.07      7.95     0.00   0.00    0.52   121.36    0.00      0.00     0.00   0.00    0.00     0.00    0.23    0.14    0.04   2.35
sdc            230.77     91.24     0.10   0.04   20.89   404.86   16.97      0.52     0.00   0.00    1.12    31.25    0.00      0.00     0.00   0.00    0.00     0.00    0.40   19.00    4.85  98.15
sdd            242.83     93.83     0.13   0.05   21.23   395.68   18.23      0.56     0.00   0.00    1.16    31.68    0.00      0.00     0.00   0.00    0.00     0.00    0.40   19.42    5.18  97.36
sde            213.67    139.77     0.00   0.00   18.91   669.85   19.17      0.53     0.00   0.00    1.21    28.10    0.00      0.00     0.00   0.00    0.00     0.00    0.40   15.92    4.07  96.49
sdf            231.87     91.34     0.03   0.01   23.33   403.39   16.77      0.52     0.00   0.00    1.18    31.63    0.00      0.00     0.00   0.00    0.00     0.00    0.40   16.33    5.44  97.28
sdg            249.23     94.07     0.13   0.05   14.52   386.48   18.40      0.56     0.00   0.00    1.19    31.39    0.00      0.00     0.00   0.00    0.00     0.00    0.40   19.25    3.65  96.65
```

Here's what Prometheus had to show around the time the scrub started:

![Screenshot_2020-07-06 Node - ZFS - Grafana](https://user-images.githubusercontent.com/866859/86581030-6e412d00-bf77-11ea-857c-cf7f2738f735.png)

The hardware setup is as follows:

- Motherboard: [Gigabyte GA-Z87X-UD3H](https://www.gigabyte.com/Motherboard/GA-Z87X-UD3H-rev-1x)
  - Z87 SATA Controller ([DMI](https://en.wikipedia.org/wiki/Direct_Media_Interface) 2.0)
     - Disks JEJEGWKM, JEJEDYSM, JEJDSYJM, JEJDTW6M and JEJEJYYM
     - CVWL431501AV800RGN SSD
  - Marvell 88SE9172 SATA Controller (PCIe 2.0 x1)
     - Disk JEJDV5KM

It doesn't look like the bottleneck is within the bus or SATA controllers, as [Z87 is capable of at least double that total throughput](https://youtu.be/JPuywNBctvg?t=141).

**Comment by zenaan** [comment]
I experienced similar "massive latency" issues on a new backup pool when populating the pool with a dataset from a non-zfs drive (~700Gib, and on another, ~1.3TiB), with the backup pool on a USB SATA adapter and no other actvity on that pool.

I have also had this problem with large copy/rsync between Ext3 and Ext4 drives.

Due to the consistency of the resultant massive latency issue which hits the user on anything requiring `sync` (like closing an email folder) during such "filesystem copies", and hints from research, my present conclusion is that Linux is the problem.

It seems that the default Linux IO scheduler is an absolute pig for desktop latency, or in fact for just about anything other than the absolute lowest possible achievable throughput Total time for bulk transfers (e.g. cp, rsync, etc).

The default Linux IO scheduler seems to consume all available RAM, with no thought re eviction of all other memory pages which might be even remotely useful to the user in the near future, and SO, when a user's humble little `sync` request comes along, even when that sync request is limited to a SINGLE 17MiB mbox file, the user's MUA is forced to completely stop and wait for __Gigabytes__ of cached bulk IO pages to be flushed before anything else can happen. This can take 10's of seconds!

My own attempts to use `ionice` to throttle such bulk IO with the `Idle` IO scheduling class, have not been successful at curbing Linux's profligate IO behaviour - bulk IO is simply tooo valuable to the Enterprise Users™©® to sacrifice about 2% of maximum IO throughput required in order to solve this for the majority of Linux desktop users.

There has been some work on a new IO scheduler - or new default behaviour at least - search lwn.net, here's something from 2018:

https://lwn.net/Articles/767987/

**Comment by shodanshok** [comment]
Hi, I had similar a issue and discussed it here: https://github.com/openzfs/zfs/issues/10253

The worst offenders were due to flawed NCQ on SATA drives.

**Comment by dechamps** [comment]
Wow, that's amazing detective work @shodanshok! I'm glad you found my report - I don't know why my searches didn't return yours, maybe because it's a closed issue. I was able to determine that I'm indeed suffering from the exact same issue as the one you found, so I added my findings to #10253.
