### ISSUE TITLE
mentions to 'child gangs' in the source

### ISSUE THREAD

**Issue by misterbigstuff** [openzfs/zfs#10554]
considering the trend for removing problematic language, is there another term that could be applied to gang blocks that could make discussion of such topics easier and less trigger-prone?

**Comment by zenaan** [comment]
On Sat, Jul 11, 2020 at 11:46:46AM -0700, misterbigstuff wrote:
> considering the trend for removing problematic language, is there another term that could be applied to gang blocks that could make discussion of such topics easier and less trigger-prone?


This PC posturing is reactionary, and not at all sincere (by the hidden instigators originating this plan upon us all), - it is attempts to control our language, and more yet..

Controlling language is a temporary "effect producing intention" dasigned to demonstrate power, to cause submission to a hidden will, and nothing else, and under the guise of social signalling.

Controlling language, or rather, imposing the will of a minority (not the stated minority of "those triggered" either) upon the majority in regard to the words we use, is also an attempt to control thoughts.  As Professor of psychology Dr. Jordan Peterson has pointed out quite succinctly, we "think" in words, and so such attempts to control the words we use, is an attempt to control our thoughts.

And the reason this can only be temporary is that all concepts still exist (child, gang, etc) for eternity, and in time we will if we succumb to this hidden intention, begin to use new words for the old concepts, but in the meantime we will be poorer of thought and definitively testing the waters of society wide, violent revolution; I suggest this is unwise.  As temporary as it may be, the destructive power it unleashes is usually unseen until too late.


Some folks really do not know that they are being lead in their superficial social signalling desires, for hidden and very dark intentions.  If you are unfamiliar, please begin to read Solzhenitsyn's "Gulag Archipelago" which was recently translated into English and available for download, and was for decades outlawed in Russia.  We owe it to ourselves to not fall into these same traps again.


If you struggle with the basics of good and evil, as many have and some still do, consider the following:


   I have a conscience.

   By my conscience I know good, and evil.

   By my will, I choose to do good, and not evil.


Pretending evil "will no longer exist if certain words are no longer used" is obviously not true, and not a solution, and carrying very real and historically precedented potential consequences.

It is not the words we use which are the measure of us, it is how we treat one another.

Let's be kind, but firm in the face of those who need help to cope in this world and direct them in weys to get the support and help they may genuinely need.

**Comment by RJVB** [comment]
Interesting how this proposal was made by someone under a pseudo that isn't AT ALL prone to induce all kinds of inappropriate associations ;)

How long is a gang block anyway 8-)

**Comment by zenaan** [comment]
On Sun, Jul 12, 2020 at 06:53:06AM -0700, René Bertin wrote:
> Interesting how this proposal was made by someone under a pseudo that isn't AT ALL prone to induce all kinds of inappropriate associations ;)
> 
> How long is a gang block anyway 8-)

As long as a HuWaite CodeOfConduct?

We shouldn't call them CoCs anymore, too triggering.

**Comment by GregorKopka** [comment]
@ahrens @behlendorf 

Please end this joke before someone takes it seriously by accident.

**Comment by misterbigstuff** [comment]
it isn't a joke. this arose because I was discussing ZFS internals with a potential employer who was turned off by the terminology. discussions in a modern era invoking thoughts of Favelas in Brasil are probably something we can do without.

initially, i was against these changes, but after experiencing it first hand, i understand why we have to modify how we speak about tech.

**Comment by misterbigstuff** [comment]
i don't see how calling this "reactionary" is false, but i don't see how it's inherently bad, either. all civil rights movements have been reactionary - a reaction to something that needed change.

**Comment by RJVB** [comment]
AFAIK, Germans are careful with the context in which they use the words Führer, sieg and heil or (I presume) the name Adolf, but they still use them.

Should we start avoiding the words bit(s) and byte(s) just because for French speaking developers they might evoke images of male appendices? There are probably many more words that are used commonly throughout common code that will be at least similarly evocative in some more or less exotic language. How about the words "class" or "race" (as in race condition)?

There's nothing wrong with finding politically correct translations for the translatable messages a user might see (someone might even contribute an en_TB (for teddy bear) translation as far as I'm concerned. Doing this in the code itself is a bad idea and something we shouldn't have to waste time on discussing.

**Comment by misterbigstuff** [comment]
is this because developers should have thicker skin than users? developers have to stare at the code all day. we must be subjected to this?

**Comment by misterbigstuff** [comment]
fwiw the changes to remove blacklist/whitelist also only affected code and not anything an end user would see, which is the opposite of what you are fine with. either way, it's up to @ahrens and @behlendorf what happens.

**Comment by ahrens** [comment]
I welcome improvements to the terminology we use in ZFS.  Ideally, a change would make the code easier to understand as well as removing potential for offense or confusion.  Someone would need to figure that out and propose the change in a PR.

**Comment by RJVB** [comment]
>is this because developers should have thicker skin than users? developers have to stare at the code all day. we must be subjected to this?

If you have a real problem with commonly accepted terms like blacklist and whitelist than I guess all I can say is that nobody obliges you to stare at those terms all day. Which also isn't what developers are supposed to be doing O:-)

Maybe develop an editor extension that replaces the terms on the fly for your comfort, like soft line wrapping.


Oh wait, I just wrote "line", I guess now I must apologise to my colleagues from the former Warsaw Pact countries who have bad memories of having to wait in line for everything?

Frankly, I'm burning to say "grow up, get a life" but I'm too polite for that so I guess I'm not going to be going any further down this rabbit hole.

**Comment by GregorKopka** [comment]
> I welcome improvements to the terminology we use in ZFS. Ideally, a change would make the code easier to understand as well as removing potential for offense or confusion. 

@ahrens in case your goal is to remove potential for confusion: please keep in mind that plenty of documentation of the concepts, structure and codebase of ZFS is spread all over the internet. Renaming things for no good reason will needlessly make it harder to understand the codebase as nomenclature changes will turn searches that currently yield good explanations of concepts to come up dry in the future. How that can be a good thing is beyond me, _unless the goal is to destroy knowledge_.

> Someone would need to figure that out and propose the change in a PR.

Given https://github.com/openzfs/zfs/issues/10458 and this issue are from the same user... I suspect this one is simply to make the point that the current trend of renaming $unacceptable_language_of_the_day ist pointless (at best). Or both are ment to be read together as a proof of how easy it is to troll the OpenZFS leadership into performing pointless acts that defy reason - or proof that [Doublethink](https://en.wikipedia.org/wiki/Doublethink) has been achieved.

Please stop this nonsense and concentrate on things that actually matter, my comment in the other issue has further details.

**Comment by RJVB** [comment]
>Please stop this nonsense and concentrate on things that actually matter, my comment in the other issue has further details.

Amen to that.

One last thought, inspired by a quote from that other issue (of which I'd been blissfully unaware):

>  Regardless of race, the term "slave" is an analogy to human slavery

No, no, no. It is NOT an analogy to that. The term slave may well have evolved in a context where our ancestors only thought of and applied it to humans (implying that a slave was still considered to be more than just an animal). But it has since evolved to apply to anything that's controlled by and exist only to work for something else.

>  , and in my opinion, it is too serious and painful of a topic to be used in this
>  way.

I'd argue the opposite: keep the term (put in inside quotes if you want, where feasible) and let it act as a reminder of horrors we've rid ourselves of (to those who are susceptible and/or distracted enough to think of the association).

But anyone looking for similar supposedly lofty goals should go after eradicating the word `gas` from common language, esp. if it risks being used in conjunction with a synonym of chambers. Do I have to explain why?

**Comment by misterbigstuff** [comment]
> If you have a real problem with commonly accepted terms like blacklist and whitelist than I guess all I can say is that nobody obliges you to stare at those terms all day. Which also isn't what developers are supposed to be doing O:-)

we already removed those from the source tree, and as @ahrens and @ryao explained, it is *because a developer wanted the change*. developers are important people, we're trying to attract more people into the project. part of that is becoming a more welcoming environment. if using blacklist and whitelist are an obstacle, it's easy to change yourself. it's harder to change other people.


 > Maybe develop an editor extension that replaces the terms on the fly for your comfort, like soft line wrapping.

i guess the same suggestion could be tossed back your way for how to deal with these changes that you don't like.

> Oh wait, I just wrote "line", I guess now I must apologise to my colleagues from the former Warsaw Pact countries who have bad memories of having to wait in line for everything?

if you can please attempt to pretend to maintain some sense of professionalism here, it'd be swell.

> Frankly, I'm burning to say "grow up, get a life" but I'm too polite for that so I guess I'm not going to be going any further down this rabbit hole.

i don't see how any of this has been polite, after all, you uh... went ahead and wrote it here anyway while patting yourself on the back. you should have just not commented to begin with.

**Comment by misterbigstuff** [comment]
> @ahrens in case your goal is to remove potential for confusion: please keep in mind that plenty of documentation of the concepts, structure and codebase of ZFS is spread all over the internet. Renaming things for no good reason will needlessly make it harder to understand the codebase as nomenclature changes will turn searches that currently yield good explanations of concepts to come up dry in the future. How that can be a good thing is beyond me, unless the goal is to destroy knowledge.

he said it could be changed to avoid offense *or* confusion.

**Comment by misterbigstuff** [comment]
wanted to ask people to just remain on-topic for finding a new term to describe gang blocks, if you want to debate the philosophy of it, do so somewhere else.

**Comment by zenaan** [comment]
On Tue, Jul 21, 2020 at 05:06:16PM -0700, misterbigstuff wrote:
> wanted to ask people to just remain on-topic for finding a new term to describe gang blocks, if you want to debate the philosophy of it, do so somewhere else.

(And yet, you used the _more_ triggering term "child gangs" in your subject line: this is disingenuous by you, and belies that within you is a hidden agenda, and an intention which you fail to disclose to us.)


If the leadership falls for this continued attack on rationality, for "the benefit of people's feelings", that will be a sad indictment against that leadership.

To put feelings above facts, is to raise into authority he, or she, who brings those purported "feelings" to the table as a relevant and significant issue (in this case, supposedly, "in relation to a hypothetical developer's lack of contributions due to their feelings).

Matthew Ahrens, for whatever reasons, is taking the submission/ politically "comfortable" approach of appeasement and submission, bowing low and proferring to offer up supplication in the form of "working together" and "communicating fruitfully",

which is a little sad in the face of the inherently divisive language and intentions beinw either wittingly or unwittingly blought to this community.

Matthew I put to you this and mak my words: this is a pure power play, and nothing else.  Be deceived at peril.  Your statement in the other thread:

> Some people (myself included) feel that there is a connection, however unintended, between "whitelist/blacklist" and implicit bias / systemic racism.

is misguided, your belief is misguided.

The reason that your opinion is misguided is that there is a connection between all language, and all problems.

Indeed, there is an inherent connection between our very existence, and all problems in the world, and this is inescapable.

Neutering our language is never the appropriate solution to any problem.

Indeed, neutering the language we use, is not only never an appropriate solution, in fact it always, over the medium to long term, exacerbates and energizes, the very problems that are proclaimed as 'reduced' by the neutering of our language.

The reason(s) that neutering our language in any way, exacerbates the problems supposedly 'reduced' by such language neutering, include:

 - All words have roots in our deep past.

 - NO amount of language neutering is EVER accepted as sufficient to remedy "the problem" (whatever problem is presented); as there are always more words which have problems, including all words used to replace the "old" wolds, since it is the "trigger" of being reminded of the very concept (not the word itself) which is the (implied/ purported) problem.

 - Those who proclaim "feelings" as the ground for any such change, can and do change those feelings over time, and correspondingly increase their demands over time.

 - There are hidden intentions behind all attempts to control language, which most fail to witness, and which few can even properly name.

 - All concepts still exist, regardless of which word(s) are used to name that concept at any point in history.

 - The hidden intentions behind all attemps to control our language, are usually unseen until much community and other damage has been done.

 - Mental illness ought never be a foundation on which technical projects make technical decisions.

 - Basing any technical decision on any "equality" foundation, rather than on technical and competance considerations, damages the product, and damages the community.

 - Using the limited resources of a volunteer technical project, to handle the issues of mentally ill people, is perhaps unwise.

Unseen virtue signalling, especially towards mentally ill people, is dangerous.

@ahrens , I suggest you carefully consider the following questions, and possibly ask them of pourself whilst you're at it:

I suggest the following questions be put to any and all persons who come to the OpenZFS/ZoL projects proclaiming to want "inclusiveness" whilst bringing divisive issues:

 - Given your statement that you are triggered emotionally by plain words which are used in this specific and highly technical context, why do you say that you do NOT need professional help?

 - Why do you say that this project, which is both volunteer AND with very limited resources, should spend time making changes to accommodate you, when you appear to require professional help?

 - Have you ever had a mental illness?

 - Have you ever been diagnosed with a mental illness?

 - If you have never been diagnosed with a mental illness, do you consider that you may need professional help, either by a psychiatrist, or a psychologist, or by a counsellor?

**Comment by misterbigstuff** [comment]
> (And yet, you used the _more_ triggering term "child gangs" in your subject line: this is disingenuous by you, and belies that within you is a hidden agenda, and an intention which you fail to disclose to us.)

I wasn't triggered by it. an interviewer I was discussing it with, however, was. I still don't think (personally) that it's a huge deal, but it is here, open for discussion, if enough people want to change it.

the rest of your comment is exactly what's not needed here. do you think all that questioning of ahrens' mental state is helpful? i think if _you_ were being genuine, you would have privately reached out to him instead of trying to insult him here in public. for what it's worth, you seem like you are doing a comedy session for your supporters that you think are going to come here and read, and give thumbs up and laugh with you. but it's not really funny, you're not funny.

**Comment by zenaan** [comment]
On Sun, Aug 09, 2020 at 09:16:00AM -0700, misterbigstuff wrote:
> > (And yet, you used the _more_ triggering term "child gangs" in your subject line: this is disingenuous by you, and belies that within you is a hidden agenda, and an intention which you fail to disclose to us.)
> 
> I wasn't triggered by it. an interviewer I was discussing it with, however, was. I still don't think (personally) that it's a huge deal, but it is here, open for discussion, if enough people want to change it.
> 
> the rest of your comment is exactly what's not needed here. do you think all that questioning of ahrens' mental state is helpful? i think if _you_ were being genuine, you would have privately reached out to him instead of trying to insult him here in public. for what it's worth, you seem like you are doing a comedy session for your supporters that you think are going to come here and read, and give thumbs up and laugh with you. but it's not really funny, you're not funny.


It is primarily questioning of your mental state.

Perhaps you missed that part.

If you are triggered, and/or those you say you interviewed got triggered and you imply "they" won't contribute to OZFS because they are so triggered, perhaps you and this group of people you interview and who are not contributing to OZFS because they are so triggered, ought get professional help for your individual and collective, and evident (by your own words) mental issues.

So again, those questions are primarily, for you.  And it becomes evident that we need to add an additional question for you personally:

 - Since you failed to observe that the questions were directly aimed at you, and you missed this point, and instead you appear to present quite certainly that those questions were aimed exclusively at Matthew Ahrens, are you cognitively impaired?

That's a serious question: are you cognitively impaired?

**Comment by misterbigstuff** [comment]
@ahrens @behlendorf doesn't ^ this kind of stuff fall under CoC as targeted harassment?

**Comment by amotin** [comment]
@misterbigstuff, aren't you intentionally harassing this project and the people with your insinuations of something that never existed here before you?

**Comment by ahrens** [comment]
I will reiterate my previous [comment](https://github.com/openzfs/zfs/issues/10554#issuecomment-661604988) on this thread:

> I welcome improvements to the terminology we use in ZFS. Ideally, a change would make the code easier to understand as well as removing potential for offense or confusion. Someone would need to figure that out and propose the change in a PR.

For reference, here are links to the [Code of Conduct](https://openzfs.org/wiki/Code_of_Conduct) and [guide for reporting incidents](https://openzfs.org/wiki/Reporting_Guide).

I'm going to close and lock this issue because it contains personal attacks and isn't moving us towards a proposed solution to the reported issue.
