### ISSUE TITLE
Edonr dedup readiness confusion

### ISSUE THREAD

**Issue by Atemu** [openzfs/zfs#10594]
### System information
N / A

### Describe the problem you're observing

In the [manpage](https://github.com/openzfs/zfs/blob/9a49d3f3d3bfa26df4e5e54d574cb490f0ee284b/man/man5/zpool-features.5#L323) it says that edonr requires `verify` for use with dedup.

What strikes me as especially weird that it is allowed for nopwrites which should require the same collision resistance as dedup.  
Does it automatically use verify or is it only nopwrite capable when verify is also enabled?

In the [openzfs docs](https://github.com/openzfs/openzfs-docs/blame/62c172a8ebd42db166c8b56e8f06a950b14d9232/docs/Basic%20Concepts/Checksums.rst#L87) however, it says that edonr is fine for dedup and nopwrites.

Additionally, edonr is a cryptographic hash and ZFS seems to be using it in 512bit mode; should't a collision about as unlikely as with sha512?

I think further clarification is necessary.

### Describe how to reproduce the problem

N / A

### Include any warning/errors/backtraces from the system logs

N / A

**Comment by ahrens** [comment]
The manpage is accurate, the docs are incorrect.

> Does it automatically use verify or is it only nopwrite capable when verify is also enabled?

dedup with edonr will automatically verify.  nopwrite never does verification, regardless of checksum algorithm.

Dedup and nopwrite have different security requirements.  For dedup, it must be "impossible" for an attacker to generate a block with the same checksum as a different block, otherwise you could change someone else's data (note that the dedup table is pool-wide).

For nopwrite, there's no real security requirement, because you have to be allowed to overwrite the block to begin with.  For nopwrite we just have to be sure to not *accidentally* drop a write that is not identical to what's already there, but we don't need to be resistant to an attacker who's trying to "fool" us into dropping a write, because they only hurt themself.

Edon-R was designed to be cryptographically strong and therefore good enough for dedup, but there have been some credible descriptions of potential attacks against it, so we consider it inappropriate for (unverified) dedup.

**Comment by Atemu** [comment]
Thanks!
