### ISSUE TITLE
cannot remove non-empty dir, invalid exchange

### ISSUE THREAD

**Issue by mo-han** [openzfs/zfs#10902]
## System information
Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 18.04.1
Linux Kernel	| 5.4.0-42-generic
Architecture	| x86-64
ZFS Version	| 0.8.3-1ubuntu12.1
SPL Version	| 0.8.3-1ubuntu12.1

### Describe the problem you're observing
a dir is corrupted, everytime accessing it the CKSUM error count increases in `zpool status -v`.
but it cannot be removed, `invalid exchange` error:
```shell
$ ll /samba/error/ph/
ls: reading directory '/samba/error/ph/': Invalid exchange
total 49
drwxr-x--- 2 ungrown ungrown 54 Sep  8 17:51 ./
drwxr-xr-x 3 root    root     3 Sep  9 10:43 ../

$ rm -rf /samba/error/ph/
rm: cannot remove '/samba/error/ph/': Directory not empty
```

### Include any warning/errors/backtraces from the system logs
(have no idea how to get those logs, didn't see "zfs" in `dmesg`)

**Comment by behlendorf** [comment]
If the directory is damaged, as indicated by the checksum error, then it cannot be safely removed without leaking the disk space used by the files in that directory.  This seems like it's working correctly, sorry but I don't see what can be done here.

**Comment by gentlecolts** [comment]
I'm encountering this, and it doesn't really inspire confidence in zfs that the answer is "something vague got corrupt"" (metadata? blocks within file itself?) and now you can't do anything about it.  In my case, it's a handful of files, on a fully mirrored (2 disk) vdev, generated by a script, nothing but their name/path is really all that important, and I'd be happy to just remove the offending files and regenerate them, but cannot do so through any obvious means.  It was hard enough finding anything even referencing what "invalid exchange" could even mean or be caused by, guidance on how to approach this scenario as a user and plans for potentially mitigating this within ZFS seem appropriate
