### ISSUE TITLE
ZFS ISN'T RUNNING SINCE Kernel 5.8.x, 

### ISSUE THREAD

**Issue by irgendwer-2020** [openzfs/zfs#10922]
Module can't be loadet with actual Kernels. I'm to newbie the precise it. Last Updates make it broken.

**Comment by Ornias1993** [comment]
Ofcoarse all issues are welcome, but please:
If you open a defect issue: Fill in the form.

That form is there for a reason.
We currently have NO IDEA what your issue is about... so you can just as well close it, because there is nothing in your issue now that even shows what your issue is. (no log, no version, no OS, nothing...)

(might be simpler closing it and reopening and filling out the form when you have the time ;)

**Comment by irgendwer-2020** [comment]
Fedora 32

zfs-0.8.4-1.fc32.x86_64
libzfs2-0.8.4-1.fc32.x86_64
zfs-release-1-5.fc32.noarch
libvirt-daemon-driver-storage-zfs-6.1.0-4.fc32.x86_64
zfs-dkms-0.8.4-1.fc32.noarch

Kernel function OK:
Linux System-01 5.7.17-200.fc32.x86_64 #1 SMP Fri Aug 21 15:23:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Kernel No function avaiable:
kernel-core-5.8.6-201.fc32.x86_64
kernel-core-5.8.7-200.fc32.x86_64

**Comment by Ornias1993** [comment]
@irgendwer-2020 Thanks for the info
As stated in the 0.8.4 release notes 5.8.x is not supported on 0.8.4. Please upgrade in due time:

> Compatible with 2.6.32 - 5.6 Linux kernels

You can close this issue now, as the changes required are (at least) already imported into 2.0.0 RC1 (and I guess that those also will get backported)

**Comment by irgendwer-2020** [comment]
How can I get 2.0 RC1 for Fedora 32?

**Comment by Ornias1993** [comment]
Build it yourself or have someone build it. Guides are in the docs.
If you can't manage, please ask the ZoL mailinglist for help :)
(link should be on both the wiki and the docs)

But I think this issue is closed now. There is no problem with running OpenZFS 0.8.4 on kernel 5.8 (because it isn't supposed to work)

**Comment by mabod** [comment]
I would not recommend to go for 2.0 RC1 yet. Not for a production system. I would rather take 0.8.5-staging instead. That compiles and runs perfectly fine on 5.8.

**Comment by Ornias1993** [comment]
@mabod Both are considered RC/staging releases and both are considered "Not production ready".
But yes, 0.8.5 staging is also an option :)

**Comment by behlendorf** [comment]
I'd also recommend using the 0.8.5-staging branch for now until an 0.8.5 tag is releases which supports the newer kernel.

**Comment by monwarez** [comment]
Building the dkms with 2.0RC1 version I get runtime error with `zstd` related symbol for compression and decompression
The missing symbol are
`zfs_zstd_compress`
`zfs_zstd_decompress`

Was 2.0 RC-1 tested with a 5.8 kernel ?

**Comment by Ornias1993** [comment]
@monwarez That is really a totally unrelated issue, please file your own seperate issue.

**Comment by monwarez** [comment]
That was more a dkms issue, for the 2.0RC we need to add `zzstd` module. I guess I could leave the diff of the dkms here
```
2c2
< PACKAGE_VERSION="0.8.4"
---
> PACKAGE_VERSION="2.0.0"
70a71
> STRIP[8]="${STRIP[0]}"
94a96,98
> BUILT_MODULE_NAME[8]="zzstd"
> BUILT_MODULE_LOCATION[8]="module/zstd/"
> DEST_MODULE_LOCATION[8]="/extra/zstd/zzstd"
```

**Comment by Ornias1993** [comment]
@monwarez Your issue with ZZSTD, is something that is NOT related to the original post in this issue at all.
I also not get what you are trying to say, mostly because you didn't write a complete issue report.

Please file an issue report, type "Defect" and fill in the form correctly, so everyone involved can have a look. ZSTD-on-ZFS should work just fine, even in 5.8. If that isn't working (even though it was tested), please make a new bug report, because it has been working previously. 

It is not related to general kernel compatibility with kernel 5.8 (which is what this issue is about).

**Comment by Lalufu** [comment]
What's the main thing holding up 0.8.5?

**Comment by Ornias1993** [comment]
@Lalufu Testing, verification etc.
It's done when the maintainers think its done.

The goal isn't to release support for new kernels as soon as possible, it never was....

**Comment by jochendemuth** [comment]
Would like to help with testing, but fedora-testing repo does not seem to be working at this moment. Please note that Fedora 32 does not offer access to kernel 5.7 versions anymore, essentially rendering zfs unavailable on Fedora via the convenient dnf package manager. 
I appreciate the challenge of maintaining compatibility with a large assortment of distributions/kernel versions. However, at this point the compatibility issue with kernel 5.8 has been fixed in multiple branches for a while, yet none have been released.

**Comment by Ornias1993** [comment]
It's a known flaw with Fedora, ZFS releases are more than kernel patches and used in production where mistakes are not acceptable.

**Comment by behlendorf** [comment]
Closing.  The initial issue here has been resolved, the packages in the Fedora repository support up to the 5.14 kernel.  We'll continue to update them as new versions are released.
