### ISSUE TITLE
Library SONAME version bump

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#11138]
### Ask your question!

As of the (rapidly approaching) 2.0 release, what is the backwards-compatibility with 0.8 libraries?  More generally, is it safe to run programs linked against a previous version of the libraries in zfs?

Also: should the soversion of the old libraries be bumped?  Should they be synchronized with the FreeBSD soversion?

### Which portion of the codebase does your question involve?

This involves the libraries: `lib/lib*/Makefile.am` (`LDFLAGS`)

### Additional context

I am packaging the [Open ZFS 2.0 release for Debian](https://salsa.debian.org/zfsonlinux-team/zfs/-/merge_requests/24), and Debian makes some stringent demands of library versioning.  Symbols have been removed, suggesting we should bump the version number.

**Comment by aerusso** [comment]
@behlendorf I've opened #11144 that should address both of your points.

One question remaining is how to manage the ABI version in master---should we bump it at release time, during development (sounds painful, but would be easier with the abigail setup in that patchset), or maybe when we pinch off the first RC?

My suggestion is:

1. Include #11144 in master
2. Cherry pick it into zfs-2.0-staging, re-running abigail for the zfs 2.0 ABI
3. Ask the BSD people if the SOVERSION needs to be bumped for any libraries (for Linux, I think the answer is "no further bump required").
4. Add in a `make checkabi` during CI, and require bumps at every release (not rc) where the ABI changes.
5. For future releases, don't worry about the ABI level in master until we pinch off the first RC.  Right before that RC, bump the SOVERSION so that it follows semantic versioning relative to the last release branch: any time we merge master wholly into a release version, tidy up the ABI versioning just beforehand.  I.e.,  "The parents are coming over! Quick, clean up the living room!"

**Comment by kevans91** [comment]
Has symbol versioning been considered/discussed here? I'd be interested in seeing it being applied as a consumer of libzfs/libnvpair, and I could work on it if there's buy-in.

**Comment by behlendorf** [comment]
@aerusso I tend to agree, that sounds like the best approach to me as well.  I'll go ahead and get this change merged in to master and to the zfs 2.0 release branch for the next -rc (with updated ABI files).

> 3. Ask the BSD people if the SOVERSION needs to be bumped for any libraries

@freqlabs or @allanjude can correct me on this, but my understanding is no further SOVERSION bump should be need for FreeBSD.  The versions were already bumped to avoid conflicting with the versions from the OpenZFS repo sources.

> 4. Add in a make checkabi during CI
> 5. For future releases, don't worry about the ABI level in master until we pinch off the first RC

The easiest way to enable these checks would probably be to add them to the GitHub actions checkstyle workflow, `.github/workflows/checkstyle.yaml`, after the `make lint` target.  Though as you said I don't think we want to make them fatal in master since we want the flexibility to change the ABI when required.  What would be nice through is to still report that change so we can better avoid any gratuitous changes. 

@kevans91 this isn't something which has really been considered before.  What did you have in mind?
