### ISSUE TITLE
pam_zfs_key failures lead to password prompts for root su

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#11222]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| unstable
Linux Kernel	| 5.9
Architecture	| amd64
ZFS Version	| 2.0-release (813185d14)

### Describe the problem you're observing

Trying to `su` to another user from root leads to a spurious prompt for a password on the first attempt to su to another user.  This leads to ZTS failures when trying to execute commands as another user (e.g., `posix_sa` tests).

### Describe how to reproduce the problem

On Debian, install and enable the pam_zfs_key.so module in the PAM system, have no imported pools. `su` to another user as root, and get a password prompt. 

### Include any warning/errors/backtraces from the system logs

I do not know where to begin.  I get errors like

```
su: pam_zfs_key(su:session): couldn't get password from PAM stack
```

and

```
su: pam_zfs_key(su:session): dataset rpool/home/testrunner not found
```

in `/var/log/auth`.  Tagging @felixdoerre, hopefully your expertise can help me narrow this down!

**Comment by behlendorf** [comment]
Until you can narrow it down you might consider disabling the pam module by default, `./configure --disable-pam`.

**Comment by aerusso** [comment]
So I looked into this a tiny bit.  If a password is not available at authentication time, the module asks fails the authentication---causing a password to be requested.  I'd like to modify the behavior in the following way:  if the dataset to be mounted is already mounted (or at least the key is unlocked), do not ask for a password.  Additionally, if there is no dataset to mount, do not ask for a password.

IMO, this would solve the majority of the breaking behavior of requiring a password unconditionally at authentication time.

Tagging @CragW for comments as well, since I'd like to avoid stepping on anyone else's work (e.g., #11165). Also, I'd like input on this, since I've never touched PAM code before.

**Comment by felixdoerre** [comment]
One important thing to note is that this problem only occurs for users with uid >= 1000, so `su`-ing to system users is not problem.

I think, not asking for a password when the key is already loaded is reasonable and shouldn't be any problem. So moving the `pw_get`-block below this line: https://github.com/openzfs/zfs/blob/4d0ba9411312991635edc5154bb42b9dfff192a2/contrib/pam_zfs_key/pam_zfs_key.c#L679 and adding an early-return check for dataset-existence and `is_key_loaded`.

I would suggest that we do the session-counting in any case as the existence of a home dataset and key load status can change anytime. So the behavior for a user with already key loaded and mounted dataset would be:
- open session (without password), does nothing
- close session, does unload and unmount
- open session (requests password), does load and mount

This would happen if a home dataset does not exist in the beginning
- open session (without password), does nothing
- user creates their home dataset, with encryption and mounts it
- close session, does unload and unmount.

I believe that behavior in the corner cases is reasonable.

**Comment by aerusso** [comment]
I've gone ahead and created #11226 to address this.

While testing, I noticed some corner cases that are less than ideal: if you control-c at the su prompt, the session counter is incremented making it impossible to ever drop it back down to zero---and no more attempts will be made to automatically unlock the dataset.  Is there any better way to count open PAM sessions?

Also, the pam session close happens immediately upon logout, but for systemd user, there will probably be lingering user processes for at least the next few seconds.  This will block unmounted (and key unloading) of the dataset.  This represents a security concern for users expecting the auto-lock behavior.

Additionally, we might also consider adding 1 to the session counter at first session open if the dataset is already unlocked---signaling that the dataset was manually unlocked, and should not be locked by the PAM module.

**Comment by felixdoerre** [comment]
Yes, the problem of lingering user-process was already considered in the initial pull request: https://github.com/openzfs/zfs/pull/9903#issuecomment-632345204
However we don't have a satisfying solution for that.

I don't know of a better way to count sessions. If you find one, let us know! This is essentially the same way that pam_mount uses to detect open sessions. Maybe integrating more deeply with loginctl/systemd could allow a cleaner solution.

**Comment by aerusso** [comment]
Another option would be to just mount without keeping track of the counter, but have the unmount be handled by systemd.  Put a condition `After=zfs-user-mount@%i.service` for `user@.service`, and have that new service file `ExecStop=-zfs unmount $(magic_mountpoint_command)`.   Assuming that, if the user has another open session, they have at least one process has an open file on the mountpoint, the unmount would fail, and we'd be OK to not keep a session counter.  The PAM integration in this case would just drop the session close behavior.  On my machine, I see a dbus-session that has my home directory open.  If that's universal, we're fine.  If its not, we could just spawn an infinite sleep in zfs-user-mount.service (i.e., `ExecStart=/bin/sh -c 'cd "$(magic_mountpoint_command)" ; sleep 10000000000' `).

We could handle non-systemd users by testing for the non-existence of `/run/systemd`, and preserving the existing behavior for them.

In any case, the more I think about it, the more I think the PR is moving in the right direction.

**Comment by CragW** [comment]
On Ubuntu, I realized that some processes may be still using the directory when `pam_zfs_key` attempts to `unmount` the home directory ends up pam failure.

For instance on logout of `ssh test@localhost` error message is seen:
```
sshd[19896]: pam_zfs_key(sshd:session): zfs_unmount failed with : -1
```
Since systemd manages user session with individual runtime directory, I used to `unmount` and `unload-key` by adding `ExecStop` line to `systemd`, for instance [user-runtime-dir](https://github.com/CragW/dell-recovery/commit/bb8c9600cf7a41b07da4d562658c33d5eaf64baa#diff-bd7a925b799120365cbfad187c8a26dd8d9f3eaf86250523d5e99d61ef44a23bR12) that does the magic but user space tool is then required.

**Comment by felixdoerre** [comment]
Interesting, on my system (Debian unstable) the unit `user-runtime-dir@.service` does not seem to be used. Also I can't seem to find a `zfs-user-mount` unit.

**Comment by aerusso** [comment]
Re. `zfs-user-mount.service`: no such unit exists, I was suggesting creating a new one to accomplish this goal.  But, perhaps instead we could hook into `zfs-user-mount` somehow to do the job in a more systemd-integrated way.

**Comment by myfreeweb** [comment]
> zfs_unmount failed with : -1

Same on FreeBSD (with just a `login` from shell and without any extra pam modules even), syscall tracing indeed shows EBUSY:

```
unmount("/home/ztest",0x0)                ERR#16 'Device busy'
```

**Comment by beren12** [comment]
I'm getting these errors on my debian server now. I don't have anything encrypted, and on top of that the datasets are wrong. I don't even have an rpool, or a /home dataset. My root is valtank yet:
```
Feb  5 08:50:08 valinor su: pam_zfs_key(su:session): couldn't get password from PAM stack
Feb  5 08:50:08 valinor su: pam_zfs_key(su:session): dataset rpool/home/mid-earth not found
```

**Comment by aerusso** [comment]
@beren12 : If you are using the official Debian packaging, remove the libpam-zfs package.  If you're using upstream directly, use behlendorf's suggestion:

`./configure --disable-pam`

**Comment by beren12** [comment]
Yeah, that’s logical. I didn’t realize I installed it and it wasn’t already. Thanks!

**Comment by ColMelvin** [comment]
# Problem

The `pam_zfs_key.so` PAM module adds a password prompt to the `session` interface (an uncommon approach), in addition to prompting during the `auth` interface.  If no password is provided during `auth` (when one would normally be provided), then the `session` will prompt.

Many systems configure PAM to skip authentication on `su` and `su-l` when invoked by root.  On these systems, the `auth` interface is generally terminated early with a `sufficient` module to prevent later modules from running (and, therefore, from prompting).  Since `pam_zfs_key.so` prompts both in the `auth` and `session` interfaces, skipping `auth` alone is insufficient to prevent the prompt; we must also skip `session`.

# Workaround

Configure PAM to skip the `session` interface, in addition to skipping the `auth` interface, for `pam_zfs_key,so`.  A PAM configuration file (`/etc/pam.d/su`. `/etc/pam.d/su-l`, or a file included thereby) might use the following lines to do this:

```
auth   sufficient  pam_rootok.so
…
-auth   optional    pam_zfs_key.so
```
and
```
session   [success=1 default=ignore] pam_succeed_if.so use_uid uid = 0
-session   optional    pam_zfs_key.so
```

Notice the `session`s must be one after another but the `auth`s do not need to be (see [control field notes](https://helpful.knobs-dials.com/index.php/PAM_notes#Control_field)).

**Note:** the leading `-` is not necessary; it avoids errors if `pam_zfs_key.so` gets uninstalled.

## Caveat

By skipping PAM session opening/closing on `su`, the session count does not get incremented/decremented.  This means that if a user logged in (before or after root did `su`) and then logged out before root exited `su`, the module would attempt to unmount the dataset and unload the key.  If you're keeping the dataset busy, it won't unmount; then when root exits `su`the dataset will remain unlocked.

**Comment by DBotThePony** [comment]
This is still an issue
