### ISSUE TITLE
Bad SSL certificate at https://download.zfsonlinux.org

### ISSUE THREAD

**Issue by IvanVolosyuk** [openzfs/zfs#11292]
SSL certificate info:

Common Name (CN) *.s3-us-west-2.amazonaws.com
Organization (O) Amazon.com, Inc.

Opening the URL in my browser warns:
**Attackers might be trying to steal your information from download.zfsonlinux.org (for example, passwords, messages, or credit cards).**
The most probable cause is a wrong DNS record.

**Comment by behlendorf** [comment]
The packages are only provided over `http` and not `https`.  This is ok because as mentioned in the [Fedora documentation](https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora.html) the repository and packages themselves are all secured by gpg signatures.  You just want to manually verify the fingerprint after installing the `zfs-release` package.  Still, this question has come up before so when I get a chance I'll see about setting up the https address.

**Comment by IvanVolosyuk** [comment]
I think it makes sense to disable https at all in this case than use incorrect certificate. Setting up auto-updating SSL certificate these days is pretty easy as well with https://letsencrypt.org/.
