### ISSUE TITLE
Plans for new features/stability of the 2.0 branch

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#11314]
### Ask your question!

Downstream in Debian, we're trying to decide if Debian 11 should ship with the ZFS 2.0-branch or the 0.8-branch.  In my opinion, there is really one point that is of primary concern for Debian stable.

- What are the plans to provide noninvasive, targeted bug fixes for each of these branches?

From the perspective of downstream Debian, we'd like to only be including the least dangerous possible fixes--this means avoiding things like any new features and even future kernel compatibility (since we aren't upgrading the kernel either).  It's (perhaps oddly) not Debian policy to import new point releases, but rather cherry-pick these targeted fixes.

The 0.8-branch picked up some significant features throughout its lifetime, so there's a concern that an early 2.0 or perhaps 2.0.1 might be left in the past, with bug fixes that may need significant back-porting to apply to such an old release (and I'm thinking far down the line, say at least 3 years).  Conversely, the 0.8-branch might simply receive no more attention at all---and there are already many changes relative to that branch that prevent `git cherry-pick` from applying cleanly.

Moreover, I would prefer to not have Debian users showing up here, asking for support for an "outdated" version, taxing upstream developer's time.  (Though, notice that Ubuntu LTS shipped with 0.8.3, so that may be happening for years to come anyway).

As a note to any Debian user reading this who wants to say "please choose 2.0, because I want some *new feature X*": please don't worry about that, there will most definitely be ZFS 2.0, readily accessible in backports.  The question here is restricted entirely to old-school, pure-stable, users who are concerned about stability over features, at all costs.

### Which portion of the codebase does your question involve?

The whole code base.

I'm not sure if this is more suited for the mailing list---I can move the discussion there if that's more appropriate.

**Comment by gdevenyi** [comment]
Related discussion; https://github.com/openzfs/zfs/issues/10334

**Comment by Ornias1993** [comment]
I myself also had questions about this and I think this short explaination from @ahrens sums it up perfectly:

> Going forward, major versions are the part before the _(first)*_ "."  (2.0, 3.0, etc) .
> Minor releases will be 2.1, 2.2, 2.3, etc and usually will be bug fixes only.
> I don't think there would generally be a need for "micro" releases (2.1.1, 2.1.2, 2.1.3 etc).
> 
>  
> DRAID is an exception to the "bug fixes only", feel free to ask Brian about that.

(*) Text before * is added to clearify the answer

So normally 2.* would be patch releases, just like 0.8.* is just patch releases.
With the exception of draid, because delaying DRAID till next major had/has some downsides.

**Comment by behlendorf** [comment]
Good question.  Let me do my best to summarize the plan for the release branches to help you decide.  I know this hasn't been crystal clear in the past, and I agree the 0.8 series underwent more churn that I would have liked.  This is something we will do our best to avoid with the 2.0 branch.  However, since the kernel is a moving target I expected we will have to pull in some larger changes as needed to maintain compatibility over the lifetime of the 2.0 branch.  If Debian's policy is to only apply what you need it should be straight forward to just cherry pick those changes and skip the kernel compatibility patches if they're not needed.

- **0.8** - The 0.8 branch is now 18 months old and will only receive important bug fixes and minimal kernel compatibility changes.  Users running kernels newer than 5.9 will need to migrate to the 2.0 release due to the difficulty in backporting the required patches.

- **2.0** - The 2.0 branch will get documentation updates, important bug fixes, minor performance improvements, and any required kernel compatibility changes.  It will also provide a stable user space library API (libzfs, libzfs_core).   I'd encourage downstream distributions and users to adopt this release if possible since it will be easiest for us to support long term.  We will continue to apply patches as need to this release even after OpenZFS 2.1 has been tagged.

- **2.1** - Minor release, targeted for early 2021.  It will include dRAID (which has already been merged) plus any other changes which have been finalized and integrated before cutting the 2.1 branch from the master branch.  It's intend for those who need to have the latest features.

- **3.0** - Major release, targeted for late 2021.

As for the version numbers we're using the popular MAJOR.MINOR.PATCH scheme.  As new OpenZFS 2,0 releases are cut we'll create tags on the release branch (2.0.1, 2.0.2, etc).  OpenZFS 2.1 will include at least one new features hence the bump to the minor number.

- MAJOR version when you make incompatible API changes,
- MINOR version when you add functionality in a backwards compatible manner, and
- PATCH version when you make backwards compatible bug fixes.

**Comment by aerusso** [comment]
Thank you, @behlendorf.  This is great news, and it answers my question completely.  I will be advocating for 2.0 in Debian 11.

**Comment by happyaron** [comment]
@behlendorf we had a discussion about what version we'd like to ship in next Debian stable version (11) and here's our preliminary thoughs:
1. We are happy to ship a newer version, with long-term upstream dedication of bug fixes. Reading through this issue we see that you mentioned to maintain 2.0 in the future but we are really interested in shipping dRAID for the next major stable, while we don't think features like zzstd is very concerned.
2. If it's not able to ship dRAID, we might have an option to stay with old and safe version which is likely 0.8.x series, and the only blocking stuff is that 5.10 is very likely to be the choice of kernel, which isn't supported by 0.8.x yet (the iov_iter patch is complex to rework).

What do you think?

**Comment by Ornias1993** [comment]
>  while we don't think features like zzstd is very concerned.

What are you trying to say here?
ARE you concerned about something?

**Comment by happyaron** [comment]
@Ornias1993 This issue was started for a simple question: which version of openzfs should Debian ship for its next stable release. We are not yet decided and it's still great time to discuss.

As for the quoted part, I don't mean zzstd isn't important and actually I like it very much, but from a distro maintainer's perspective it's not something have or not (i.e. have compression or no compression at all). Secondly, no matter which direction we eventually go with, the latest branch will be tracked in stable-backports (which we recommend everyone on Debian to use) and zzstd will be there. Talking about dRAID, we have some motivation to put a bet for shipping the new dRAID feature for a Debian stable release (i.e. bullseye's default), otherwise we would consider being conservative enough.

**Comment by Ornias1993** [comment]
@happyaron I wasn't offended, what you wrote just simply wasn't readable understandable english... ;-)

**Comment by behlendorf** [comment]
@happyaron depending on what Debian's release / testing timetable looks like I think it could make good sense to plan for the 2.1 release and dRAID.  If for no other reason than to avoid an entire type of OpenZFS pool which can't be imported with the default Debian packages.  This has been mentioned elsewhere, but to aid in your planning we're currently pushing to get the direct IO functionality wrapped up (PR 10018) for inclusion in 2.1.  While not a blocker it's also likely the ability to force export a suspended pool will also be ready in time (PR 11082).  These are both features we've seen a lot of interest in and would be "nice to have".  The plan is to wrap them up in the next few months and then cut the 2.1 release branch from the master branch for final soak testing.

We'd obviously like to maintain as few branches as possible so it would be ideal if distributions did settle on the 2.1 branch when it's available.  Aside from the features mentioned above, which are relatively self contained, 2.1 won't actually be so different from the current 2.0 release.  As for the 0.8.x branch we're not currently planning to port the Linux 5.10/5.11 compatibility patches.  As you saw porting and testing those changes is pretty involved but definitely doable.  But it's entirely possible someone in the community will decide to tackle that backport and do the need testing.
