### ISSUE TITLE
checkabi fails on 32-bit architecture

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#11345]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian (but applies to all)
Distribution Version	| sid
Linux Kernel	| 5.9
Architecture	| i386
ZFS Version	| 2.0.0
SPL Version	| NA

### Describe the problem you're observing
Running `make checkabi` fails because the bit width has changed, and libabigail complains.  See this [Debian build failure log](https://salsa.debian.org/zfsonlinux-team/zfs/-/jobs/1237523) around line 1730.

### Describe how to reproduce the problem
Build the source, and then run `make checkabi` on a 32-bit architecture.

### Include any warning/errors/backtraces from the system logs
Here's an except from that [Debian build failure log](https://salsa.debian.org/zfsonlinux-team/zfs/-/jobs/1237523) around line 1730:

```
ELF architecture changed
Functions changes summary: 0 Removed, 219 Changed (6 filtered out), 0 Added functions
Variables changes summary: 0 Removed, 7 Changed, 0 Added variables
architecture changed from 'elf-amd-x86_64' to 'elf-intel-80386'
219 functions with some indirect sub-type change:
  [C] 'function void dump_nvlist(nvlist_t*, int)' at libnvpair.c:794:1 has some indirect sub-type changes:
    parameter 1 of type 'nvlist_t*' has sub-type changes:
      in pointed to type 'typedef nvlist_t' at nvpair.h:91:1:
        underlying type 'struct nvlist' at nvpair.h:85:1 changed:
          type size hasn't changed
          1 data member change:
            type of 'uint64_t nvlist::nvl_priv' changed:
              underlying type 'typedef __uint64_t' at types.h:45:1 changed:
                underlying type 'unsigned long int' changed:
                  type name changed from 'unsigned long int' to 'long long unsigned int'
                  type size hasn't changed
    address size of function changed from 64 bits to 32 bits
  [C] 'function void fnvlist_add_boolean(nvlist_t*, const char*)' at fnvpair.c:131:1 has some indirect sub-type changes:
    address size of function changed from 64 bits to 32 bits
  [C] 'function void fnvlist_add_boolean_array(nvlist_t*, const char*, boolean_t*, uint_t)' at fnvpair.c:215:1 has some indirect sub-type changes:
```

### Other thoughts

Should we just ship a 32-bit ABI as well?  We obviously don't expect ABI compatibility between architectures.

**Comment by behlendorf** [comment]
Good question.  Now that you mention it there's probably a decent chance it will fail on other 64-bit architectures as well (arm64, ppc64, etc).  Including an ABI file for each of these feels a bit burdensome when we're primarily attempting to catch accidental ABI changes which would very likely effect all of the architectures.  Perhaps instead of adding another ABI file we could update the `make checkabi` target to only run on x86_64 and add a comment with the justification above.

**Comment by cdluminate** [comment]
It's a good idea to noop `make checkabi` on non-amd64 architectures.

**Comment by behlendorf** [comment]
This is still the case, since this is expected not to work what we should probably do is simply disable the `make checkabi` target on non-amd64 architectures.

**Comment by szubersk** [comment]
> This is still the case, since this is expected not to work what we should probably do is simply disable the `make checkabi` target on non-amd64 architectures.

@behlendorf @aerusso @gmelikov
How about taking a shot at disabling non-64-bit architectures to check what the feedback from users is? It might turn out that there might be no size discrepancies between same-word-size architectures. This issue is about specifically C types having different sizes because of the word size.
Just an idea.
