### ISSUE TITLE
zfs errors with receive -x prevent robust backups

### ISSUE THREAD

**Issue by jgoerzen** [openzfs/zfs#11416]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Debian
Distribution Version	| buster
Linux Kernel	| 4.19.0-13-amd64
Architecture	| amd64
ZFS Version	|0.8.6
SPL Version	|0.8.6

### Describe the problem you're observing

I have a system that is designed to receive backups.  In order to protect against the zfs send side being compromised and malicious, it is strongly desirable to use `-x mountpoint` with `zfs receive`, and also nearly as desirable to use `-o volmode=none` for zvols.

The problem arises that the receiving end cannot know whether it is receiving a filesystem or a zvol.  With `-x mountpoint`, as noted in #6371, I get:

`cannot receive incremental stream: property 'mountpoint' does not apply to datasets of this type`

Similar would apply to `-o volmode=none` for non-zvols.

It should be noted that, security-wise, a `zfs receive` command cannot have control over whether they are receiving a replication stream.

### Describe how to reproduce the problem

Receive a zfs send from a zvol with `-x mountpoint

### Possible workaround

Importing with zpool -R mitigates the immediate security concern (a malicious mounting over, say, /etc) but raises other complications.

**Comment by IvanVolosyuk** [comment]
Another possible workaround - spawn two 'zfs recv' - one which will work for zvol another for filesystem. Send the stream to both, like:
https://unix.stackexchange.com/questions/40277/is-there-a-way-to-pipe-the-output-of-one-program-into-two-other-programs
One of the 'zfs recv' will fail instantly because of the wrong arguments.
It is kind of a dirty hack.
