### ISSUE TITLE
zfs send -R broken on 2.0.1 and Linux 5.10 when piped to /dev/null

### ISSUE THREAD

**Issue by aerusso** [openzfs/zfs#11445]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| sid
Linux Kernel	| 5.10.4
Architecture	| amd64
ZFS Version	|  2.0.1

### Describe the problem you're observing
Many ZTS failures related to send:

    FAIL cli_root/zfs_send/zfs_send-b (expected PASS)
    FAIL cli_root/zfs_send/zfs_send_003_pos (expected PASS)
    FAIL cli_root/zfs_send/zfs_send_005_pos (expected PASS)
    FAIL cli_root/zfs_send/zfs_send_encrypted (expected PASS)
    FAIL cli_root/zfs_send/zfs_send_raw (expected PASS)
    FAIL pyzfs/pyzfs_unittest (expected PASS)
    FAIL redacted_send/redacted_negative (expected PASS)
    FAIL removal/removal_with_send (expected PASS)

This is not reproducible on 5.9.

### Describe how to reproduce the problem

    truncate -s 512M /tmp/loopdev0
    losetup loop0 /tmp/loopdev0
    zpool create testpool /dev/loop0
    zfs snapshot -r testpool@snap
    zfs send -R testpool@snap >/dev/null

### Include any warning/errors/backtraces from the system logs

This gives an error:

    internal error: warning: cannot send 'testpool@snap': Invalid argument

The send command results a log in dmesg:

    kernel: kernel write not supported for file /null (pid: 2241 comm: zfs)

**Comment by behlendorf** [comment]
I've starting looking in to this and the short version is that the kernel `kernel_write()` and `kernel_read()` functions can no longer access the `/dev/null` and `/dev/zero` virtual devices because they do not register any `*_iter` operations.  The good news is that it should only effect those two devices.  Any filesystem which supports the `*_iter` operations (and most do) will continue to work fine.

For background here's the relevant [kernel commit](https://github.com/0day-ci/linux/commit/ef30fb3c6024456f0bb0eaf2f3e12eaf6b3d64a8) which adds the new check to `__kernel_write()` and a link to the [upstream discussion](https://lkml.org/lkml/2020/9/3/557) regarding this change.  We'll have to give some thought as the the best way to handle this.

**Comment by aerusso** [comment]
Thanks, this is far less concerning than I originally feared.

The ZTS now passes on 5.10 with 2.0.1.  If there's a need for it, I can provide the patches I used to avoid piping to `/dev/null`.

**Comment by behlendorf** [comment]
That would be helpful to at least keep the CI happy until we settle on a solution we're happy with.  Would you mind opening a PR.

**Comment by curiousercreative** [comment]
FWiW I just reproduced this in the wild while attempting to check the estimated size of a snapshot send

```
# zfs --version
zfs-2.0.6-1ubuntu2pop0~1642612525~21.10~51ca23c
zfs-kmod-2.0.6-1ubuntu2pop0~1642612525~21.10~51ca23c

# uname -r
5.15.15-76051515-generic

# cat /etc/os-release
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```
