### ISSUE TITLE
Should stat(2) .st_blocks reflect ZFS compression?

### ISSUE THREAD

**Issue by dechamps** [openzfs/zfs#11532]
(For context: st_blocks is what `du` shows unless `--apparent-size` is used.)

In systemd/systemd#18353, @poettering wrote:

> ahum, that's quite some weird semantics, if zfs reports disk space usage like that. the general assumption is that .st_blocks and .st_size difference are about sparse files, not compression. If compression is used we cannot do sane calculations about sizes, I am not sure we possibly could. Maybe file a bug against ZFS that they break all forms of assumptions?

I think this is an interesting question.

On the hand, the [Linux stat(2) manpage](https://linux.die.net/man/2/stat) states:

> The `st_blocks` field indicates the number of blocks allocated to the file, 512-byte units. (This may be smaller than st_size/512 when the file has holes.) 

Which suggests that a file that isn't sparse should have `st_blocks` equal to `st_size/512`. ZFS breaks this assumption.

On the other hand, one could argue that `st_blocks` representing actual disk usage (including filesystem compression) is more useful, because that makes it easy to answer the question "how much actual disk space are these files using?", a question that would be much more difficult to answer otherwise if filesystem compression is used (I guess one would have to resort to `zdb` or something).

POSIX seems silent on this topic.

Is there a rationale for the original decision to make st_blocks reflect ZFS compression? Should this be revisited?

**Comment by ahrens** [comment]
> The st_blocks field indicates the number of blocks allocated to the file, 512-byte units.

We interpret this to mean that `st_blocks` should reflect the amount of space allocated on disk for the file.  It can be used to determine how much space a file is using.  For ZFS, it's always reflected compression, metadata (indirect blocks), the `copies` property, and "unexpected" RAIDZ parity/pad space due to small blocks.  I don't think it's reasonable for applications to make assumptions about the relationship between `st_blocks` and `st_size`.
