### ISSUE TITLE
Failed to add zfs to initrd on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by liqinyuan1211** [openzfs/zfs#11750]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| openSUSE
Distribution Version	| Tumbleweed-20210311
Linux Kernel	| 5.11.4-1-default
Architecture	| x86_64
ZFS Version	| 2.0.4-1
SPL Version	| 2.0.4-1

### Describe the problem you're observing

When making initrd, the inclusion of zfs dracut module failed because libgcc_s.so is not under /usr/lib .

The result of `locate libgcc_s.so` is:

```
# locate libgcc_s.so
/lib64/libgcc_s.so.1
/usr/lib64/gcc/x86_64-suse-linux/10/libgcc_s.so
```

The problem might be caused by `contrib/dracut/90zfs/module-setup.sh.in` in source tree. After editing the path for libgcc_s.so installation in `/usr/lib/dracut/modules.d/90zfs/module-setup.sh`, this module can be added to initrd. 

### Describe how to reproduce the problem

executing `dracut -f` to build the initrd, when adding zfs to initrd, it will fail at dracut-install libgcc_s.so , and zfs module is not included in the initrd. 

### Include any warning/errors/backtraces from the system logs

```
dracut-install: ERROR: installing '/usr/lib/gcc/*/*/libgcc_s.so*'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.ELz0Yb/initramfs -a /usr/lib/gcc/*/*/libgcc_s.so*
```

**Comment by tjburrows** [comment]
I also have this problem with openSUSE Leap 15.2.  I'm not sure what the implications are, because it seems like everything functions normally.  I have been using ZFS for a while, but recently used a hack to 'fix' this, which is to add a soft link to `libgcc_s.so` into a nested directory like `/usr/lib/gcc/for/zfs/libgcc_s.so`.

**Comment by nabijaczleweli** [comment]
Can you try #12108?

**Comment by barathrm** [comment]
Not sure why, but even running with https://github.com/openzfs/zfs/pull/12108/commits/e69792e0afae06da69e6ea445b791525559b6518 I'm still having issues. Running dracut in a chroot, I get 

```
dracut: *** Including module: zfs ***
simple
dracut-install: No SOURCE argument given
Usage: dracut-install -D DESTROOTDIR [-r SYSROOTDIR] [OPTION]... -a SOURCE...
or: dracut-install -D DESTROOTDIR [-r SYSROOTDIR] [OPTION]... SOURCE DEST
or: dracut-install -D DESTROOTDIR [-r SYSROOTDIR] [OPTION]... -m KERNELMODULE [KERNELMODULE …]
...
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.7B9HGe/initramfs -a
``` 

Which I can fix by commenting out the `# Try a simple path first` `elif` so that it tries the suse option first. Oddly, 
```
# echo /usr/lib/libgcc_s.so*
/usr/lib/libgcc_s.so*
```

So I'm not sure why the script fails to skip that elif.
