### ISSUE TITLE
Constantly flushing mmap file on larger record size

### ISSUE THREAD

**Issue by slav** [openzfs/zfs#11810]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.10
Linux Kernel	|
Architecture	|
ZFS Version	| 2.0.3
SPL Version	|

### Describe the problem you're observing
We have a unique situation with our setup. We don't care about resiliency, so if OS crashes and data is corrupted or lost, it's fine. We're in a cloud and in case of a failure we switch to a different VM and restore failed VM local data from a snapshot. Instead, what is important to us is speed and disc space usage (this is why we want to use ZFS, for on the fly compression). It's running on Ubuntu 20.10 with OpenZFS 2.0.3 (installed from Debian dkms).

VM is 16 cores with 128GB of ram and 2.5 TB SSD.

We're using LMDB, which is a mmap file based database. It uses B+ tree with COW for every transaction. Each page is 4kb in size. So, since it's COW, for every transaction all pages that got modified in the transaction will be copied to new pages. Typically it's the leaf with data and all branch pages pointing to the leaf. Branch and leaf pages location is completely random, so there's no benefit from read-ahead or prefetching.

We have two ways we run the database. Initially we pregenerate it based on the data coming from an external database. When we're doing that all commits include equal amount of reads and writes. After the database is generated we will upload it to cloud storage as snapshot and copy to servers doing the actual work. There, depending on the role of the server, it will be either mostly reads with some writes to update when data in another external database changes, or again read/writes (to keep local state up to date as we process messages).

My main focus right now on improving speed of pregeneration, where we do a roughly equal amount of reading and writing.

There're 12 database files we open simultaneously. Overall, uncompressed, they grow to about 2 TB. So, each file is around 100-200 GB in size. We are updating all files in parallel, but LMDB supports only a single writer per file, so it's one transaction at a time per file.

As I mentioned, speed is the most important factor, we enable async both on db level and zfs (sync=disabled) to allow OS and ZFS decide when it's time to flush to get the best speed.

Also, since LMDB is COW, it can reuse old pages that freed up with the last transaction. The longer a page is in memory, the higher chance it will have to be reused and higher the overall speed will be since if we reused the page before it was flushed, we wrote to page multiple times without have to flush it multiple times. Of course during pregeneration DB is constantly growing, so we do have to flush eventually.

In the initial setup we've run on XFS and got very good results. Most of the time the app is running and dirty pages are growing and when they reach certain limit, they're flushed very quickly. This is what it looks like:

![xfs](https://user-images.githubusercontent.com/350987/112756057-58661300-8fb1-11eb-92c8-460a5bc1ba13.png)

Since LMDB page sizes are 4kb we started with ZFS recordsize 4kb. To get any compression, we set ashift to 9.

When we tried to switch to ZFS, after some small initial tweaking we got to the point where dirty pages initially grow to some point, flush, but then don't grow much again and are constantly flushing, never growing to the initial level. This kills performance:

![zfs-flushing](https://user-images.githubusercontent.com/350987/112756138-c4e11200-8fb1-11eb-9a4a-cd552c84b35b.png)

I was able to improve the situation dramatically by disabling VM writebacks in Linux kernel (`vm.dirty_writeback_centisecs=0`). Setting `zfs_vdev_async_write_min_active` to higher value from 2 also significantly increased flush speed. I've set it to 100 (although probably 50 will be just as fast), as it's diminishing return from increasing the async writes beyond that.

These are the configs final configs:
```
cat /etc/sysctl.conf
vm.dirty_background_ratio=75
vm.dirty_ratio=85
vm.dirty_expire_centisecs=360000
vm.dirty_writeback_centisecs=0

cat /etc/modprobe.d/zfs.conf

#80gb
options zfs zfs_arc_max=81474825485

options zfs zfs_dirty_data_max_percent=80
options zfs zfs_dirty_data_max_max_percent=90

options zfs zfs_dirty_data_sync_percent=80
options zfs zfs_vdev_async_write_active_min_dirty_percent=80
options zfs zfs_vdev_async_write_active_max_dirty_percent=100

options zfs zfs_delay_min_dirty_percent=100

options zfs zfs_vdev_async_write_max_active=100
options zfs zfs_vdev_async_write_min_active=50

options zfs zfs_txg_timeout=90
options zfs zfs_prefetch_disable=1
```

And options I use to create pool and file system:

`zpool create pool -o ashift=9  /dev/disk/cloud/azure_resource`

`zfs create -o recordsize=4k -o atime=off -o sync=disabled -o mountpoint=/mnt/db -o redundant_metadata=most -o compression=lz4  -o logbias=throughput -o primarycache=metadata -o xattr=sa pool/raw`

Now dirty pages behave similar to XFS (grow -> full flush -> grow -> full flush, instead of frequent flushing). There's still an initial large growth of dirty pages, flush and they don't grow as much as 1st time, but dirty grows to much higher amounts
 and overall the speed is much better. Flushing is slower, but I'm guessing that's unavoidable due to ZFS design. This behavior doesn't change until the database files are fully generated, which is good.

![zfs-4k](https://user-images.githubusercontent.com/350987/112756263-68cabd80-8fb2-11eb-877a-a60053bdc40e.png)

However, if I try to increase ashift and record size, dirty pages flushing becomes weird. At first it flushes periodically, but eventually it reaches the point where dirty pages are again being flushed very frequently, but not all the way. So the speed, while at first quite a bit better than ashift 9 & recordsize 4k, eventually plummets.

I've tried both recordsize 16k and 128k with similar results. Here's how I create it:

`zpool create pool -o ashift=12  /dev/disk/cloud/azure_resource`

`zfs create -o recordsize=16k -o atime=off -o sync=disabled -o mountpoint=/mnt/db -o redundant_metadata=most -o compression=lz4  -o logbias=throughput -o primarycache=metadata -o xattr=sa bpool/raw`

You can see dirty pages go up and down a few times, and at that time speed is actually pretty good. Eventually they're stuck at high memory usage, never get fully flushed and at that point speed is pretty poor.

![zfs-128k](https://user-images.githubusercontent.com/350987/112756360-c828cd80-8fb2-11eb-92e9-595d94c63333.png)

Does anyone have any idea on why on larger recordsize we would see such different behavior with dirty memory, flushing, and what could be done about it? How could we even approach understanding what's causing this difference in behavior?

**Comment by ahrens** [comment]
The database is essentially doing a bunch of 4K writes to random offsets in files.  Let's think about what happens inside ZFS to process these writes.

When recordsize=4K, each write request results in writing the data to disk (say, ~2k after compression), and maybe writing an indirect block to disk (~40K)  (if writes are to similar file offsets then the indirect block may already be dirty, i.e. many data blocks may be written for each indirect block that's written).  The indirect block may also need to be read from disk, but that's unlikely since you are allowing them to be cached, and they probably use around 20GiB of RAM to cover your entire 2TiB of storage (and your ARC size is up to 80GiB).

With recordsize > 4K (e.g. 16K), each write request is a partial-block write.  It needs to get the 16K block, change the 4K within it, and then write out the 16K block (after compressing it down to say 7K).  Since you have primarycache=metadata, the block is not cached in memory.  Therefore, every write request results in a read from disk to get the block, and then a write.  With recordsize=16k, that requires 8x the disk throughput of recordsize=4k.  Even worse, the current implementation of ZFS performs the reads of the partially-written blocks synchronously.  (The indirect block overhead may be slightly less since the total amount of indirect blocks is 1/4th, since there are 1/4th as many data blocks.)

Given this understanding, my guess is that when you use larger recordsize, ZFS simply can't keep up with the write workload.  It ends up constantly writing (and reading), and the database is also constantly trying to flush to ZFS.  The database uses as much memory as possible to buffer writes, and the overall performance is limited by the rate that dirty pages can be flushed to ZFS.  You can see evidence of this in the last picture that you posted.  Before the steady state is reached, ZFS is able to process writes requests at a higher rate ("TX assigned" rate is high), which corresponds to a decrease in "dirty [database pages]", and a burst of zpool writes/iops.  Once the steady state is reached, we continue to do lots of writes and especially reads from disk, but the write requests processed ("TX assigned") is lower.

If the database's write pattern is truly random, there isn't much you can do about this fundamental problem (of partial-block writes).  However, often "random" writes are not evenly distributed, and caching can help.  You could try primarycache=all, and see if ZFS is able to cache some of the data blocks that are being hit with partial-block writes.  You could also hope that work resumes on the Async DMU project https://github.com/openzfs/zfs/pull/10425 which would at least do the reads in the background.  Or, stick with recordsize=4k, or see if you can increase the database's chunk size so that it writes in say 16KB chunks, and match the zfs recordsize to that.
