### ISSUE TITLE
zpool create "internal error: out of memory" should be EIO

### ISSUE THREAD

**Issue by stuartthebruce** [openzfs/zfs#12347]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux
Distribution Version	| 8.4
Linux Kernel	| 4.18.0-305.7.1.el8_4
Architecture	| x86_64
ZFS Version	| 2.1.0
SPL Version	| 2.1.0

### Describe the problem you're observing

zpool create exits with `internal error: out of memory` when attempting to operate on a failed device. Instead I believe EIO would be more appropriate, e.g., as output by `hdparm`.

### Describe how to reproduce the problem

```
[root@zfsbackup1 ~]# zpool create test dm-88
internal error: out of memory
```

When EIO would be more appropriate
```
[root@zfsbackup1 ~]# hdparm -tT /dev/dm-88

/dev/dm-88:
read() failed: Input/output error
 Timing buffered disk reads: read() failed: Input/output error
BLKFLSBUF failed: Input/output error
```

### Include any warning/errors/backtraces from the system logs

```
Jul 10 13:37:00 zfsbackup1 kernel: blk_update_request: I/O error, dev dm-88, sector 11720803712 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
Jul 10 13:37:00 zfsbackup1 kernel: blk_update_request: I/O error, dev dm-88, sector 11720803712 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
Jul 10 13:37:00 zfsbackup1 kernel: Buffer I/O error on dev dm-88, logical block 1465100464, async page read
Jul 10 13:37:00 zfsbackup1 kernel: blk_update_request: I/O error, dev dm-88, sector 32 op 0x0:(READ) flags 0x0 phys_seg 28 prio class 0
Jul 10 13:37:00 zfsbackup1 kernel: blk_update_request: I/O error, dev dm-88, sector 544 op 0x0:(READ) flags 0x0 phys_seg 28 prio class 0
Jul 10 13:37:00 zfsbackup1 kernel: blk_update_request: I/O error, dev dm-88, sector 11720802848 op 0x0:(READ) flags 0x0 phys_seg 28 prio class 0
Jul 10 13:37:00 zfsbackup1 kernel: blk_update_request: I/O error, dev dm-88, sector 11720803360 op 0x0:(READ) flags 0x0 phys_seg 28 prio class 0
```

**Comment by stuartthebruce** [comment]
Dear bot please don't close this.

**Comment by stuartthebruce** [comment]
I don't think this should have been closed.

**Comment by cdman** [comment]
This is still an issue with:

Type | Version/Name
 --- | ---
Distribution Name	|  Ubuntu
Distribution Version	| 23.04 (lunar)
Kernel Version	|  6.2.0-39-generic
Architecture	|  x86_64
OpenZFS Version	|  zfs-2.1.9-2ubuntu1.2 / zfs-kmod-2.1.9-2ubuntu1.1

How to reproduce:

- create a LUKSv2 device with ` --integrity hmac-sha256 --integrity-no-wipe`. This will make the device unreadeable until it's fully written to (since the data and the integrity data don't match, which is reported as an I/O error)
- try creating a zpool over the device. The output is `internal error: out of memory`
