### ISSUE TITLE
ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist() Aborted

### ISSUE THREAD

**Issue by alkeryn** [openzfs/zfs#12417]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| Latest
Kernel Version	| 5.13.4-arch1-1
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.0-1

### Describe the problem you're observing

At boot i get this error message a few times in a row with a delay of about 1s inbetween each.
i don't really know what that means, but that does slow down the boot procedure and regardless that's something that might deserve a bug report

### Describe how to reproduce the problem

I have arch linux with root on ZFS, starting having that problem as soon as i updated the system and had zfs 2.1
i did rollback and the error was gone, updated again today because there was yet a newer version of zfs than last time but the error is still there.

### Include any warning/errors/backtraces from the system logs

I do not really know of a way to get the text back from the boot framebuffer, if you know one please tell me as that would be handy.
but here is a picture i took.

![image](https://user-images.githubusercontent.com/11599075/126627714-c1435300-76c5-451a-bb15-99a236023294.png)

**Comment by ilyxa** [comment]
I also reproduce this problem with portable pools on external HDDs:
`
[root@orca ~]# trizen -Q zfs
zfs-linux 2.1.0_5.13.8.arch1.1-1
[root@orca ~]# modinfo znvpair
filename:       /lib/modules/5.13.8-arch1-1/extra/nvpair/znvpair.ko.zst
version:        2.1.0-1
license:        CDDL
author:         OpenZFS
description:    Generic name/value pair implementation
srcversion:     4AA1DF0A7202C97F76F4CC9
depends:        spl
retpoline:      Y
name:           znvpair
vermagic:       5.13.8-arch1-1 SMP preempt mod_unload 
[root@orca ~]# LC_ALL=C journalctl --boot=2aa13fc4ec444dd3afa6c438dae08130 | egrep "znvpair|zpool"
Aug 13 15:09:43 orca kernel: znvpair: module license 'CDDL' taints kernel.
Aug 13 15:09:50 orca zpool[1987]: cannot import 'data': no such pool or dataset
Aug 13 15:09:51 orca zpool[1987]: cannot import 'storarray_750': no such pool or dataset
Aug 13 15:09:51 orca zpool[1987]: nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
Aug 13 15:11:59 orca zpool[1987]: ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()
`

storarray_750 is on ext usb, disconnected.

**Comment by pikrzysztof** [comment]
I also experience this problem  and I can't import the pool - at least not by default. It seems to be only an issue with NVMe devices - My SSD attached via SATA-to-USB works just fine.

![image](https://user-images.githubusercontent.com/3964215/131883569-28b9b566-d914-408c-bea3-128109a5dafd.png)

**Comment by Alkeryn** [comment]
to everyone that replied here, on arch the issue seems to have fixed itself (well rather someone must have fixed it and the update resolved it for me).
i did update all the pools after making that issue, but i'm not sure that it is what fixed it or if it was one of the last updates i did on my system.
curious to hear about you guys's experience.

**Comment by lukebakken** [comment]
I saw this for the first time today. Notably, I did *NOT* run `zpool export` on my USB-connected backup drive prior to shutting my workstation down last night. I suspect if I export the pool then shutdown the problem is avoided.

```
linux 5.14.16.arch1-1
linux-api-headers 5.12.3-1
linux-firmware 20211027.1d00989-1
linux-headers 5.14.16.arch1-1
util-linux 2.37.2-1
util-linux-libs 2.37.2-1
zfs-linux 2.1.1_5.14.16.arch1.1-1
zfs-utils 2.1.1-1
```

**Comment by pikrzysztof** [comment]
> to everyone that replied here, on arch the issue seems to have fixed itself (well rather someone must have fixed it and the update resolved it for me). i did update all the pools after making that issue, but i'm not sure that it is what fixed it or if it was one of the last updates i did on my system. curious to hear about you guys's experience.

I confirm that this no longer happens  me. But in the meantime I've replaced my laptop and I think there were a couple of version bumps...

**Comment by 65a** [comment]
This happens consistently with HEAD zfs on an encrypted dataset, with no other side effects than a boot delay.

**Comment by szanni** [comment]
This issue just popped up for me the first time today on bootup. Never had this problem before... or did not notice?
System still boots fine but since this is file system related I am not comfortable running this.

    :: running hook [zfs]
    nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
    ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()Aborted
    nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
    ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()Aborted
    nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
    ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()Aborted
    nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
    ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()Aborted
    nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
    ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()Aborted
    nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
    ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()Aborted
    nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
    ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()Aborted
    nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
    ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()Aborted
    nvpair_value_nvlist(nvp, &rv) == 0 (0x16 == 0)
    ASSERT at ../../module/nvpair/fnvpair.c:586:fnvpair_value_nvlist()Aborted
    ZFS: Importing pool zroot.
    :: running late hook [zfs]

### System information
Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| Latest
Linux Kernel	|  5.15.5-arch1-1 and 5.10.82-1 (LTS)
Architecture	| x86_64
OpenZFS Version |	2.1.1-1

Interesting enough my real time kernel does just fine: `5.15.3.21.realtime1-1` some ZFS version.

**Comment by adroslice** [comment]
I've had this issue for a few months now, however

> to everyone that replied here, on arch the issue seems to have fixed itself (well rather someone must have fixed it and the update resolved it for me). i did update all the pools after making that issue, but i'm not sure that it is what fixed it or if it was one of the last updates i did on my system. curious to hear about you guys's experience.

running `doas zfs upgrade zroot` fixed the issue for me. Thank you so much for the pointer.

 <h3 dir="auto">System information</h3>

Type | Version/Name
-- | --
Distribution Name | Arch Linux
Distribution Version | Latest
Linux Kernel | 5.15.12-arch1-1
Architecture | x86_64
OpenZFS Version | zfs-2.1.2-1 (Dynamic kernel module)

**Comment by AkechiShiro** [comment]
Hi, I'm getting this issue and unfortunately my zfs pool is already upgraded and up to date, I've seen downgrading is probably not a really viable solution.

How should I proceed to either solve this issue or give more information in order to debug what's going on ?

I'm having this issue after having rsync (preserving everything that was possible to preserve) data from an decrypted zfs pool that had ashift=9 to a new pool with ashift=12.

The ZFS pool, root pool, I don't use a boot pool, just standard booting EFI partition along GRUB, I'm also under ArchLinux.

During boot I see a few failing asserts and then the error message saying cannot import zpool, then kernel panic (see image)
![IMG_20220123_160044.jpg](https://user-images.githubusercontent.com/14914796/150686425-5c5beef3-7f43-483e-8e59-a63b4e028700.jpg)

Here are the versions I'm running (mostly latest) : kernel 5.16.2-arch (mainline), zfs-linux-2.1.2_5.16.2.arch1.1-1

Importing the pool from an ArchIso with ZFS support under kernel 5.15.12, arch-chroot, mounting inside the arch-chroot ZFS datasets from the pool, all works without any issue.

**Comment by adroslice** [comment]
@AkechiShiro This looks like a very different issue, but here's something you can try.
1. If it's a grub issue (not finding/supporting the pool with its current options), consider using systemd-boot instead. It can't do legacy boot, but plays a lot more nicely with booting ZFS root in my experience.
2. zfs-linux has severely bricked my kernel before with a regular system upgrade, I highly suggest using zfs-dkms with arch instead and regenerating the initramfs. If there was a (kernel-)upgrade involved, this is likely the issue.

Do let me know how it goes :)

**Comment by AkechiShiro** [comment]
Hi @adroslice, thanks for your quick response, I ended up just reinstalling ArchLinux and rsynced some files from my previous installation (mostly home files), it worked alright (the issue is not happening anymore so I guess it was due to some kind of files missing or perhaps a wrong zfs cache file being used?), I'll be sure to use zfs-dkms from now thanks for the tip !
