### ISSUE TITLE
spare disk remains in inuse status after replacing the defective disk

### ISSUE THREAD

**Issue by temask88** [openzfs/zfs#12466]
spare disk remains in inuse status after replacing the defective disk

zfs version
zfs-0.8.3-1ubuntu12.12
zfs-kmod-2.1.99-399_g7eebcd2be

uname -r
5.4.0-80-generic

draid2:8d:1s:24c

![image](https://user-images.githubusercontent.com/45000603/128680723-925f842a-84fe-4f4d-9c1d-d99dbdcbd4df.png)

**Comment by rincebrain** [comment]
I'm p. sure "0.8.x userland and git master kernel module" aren't expected to do anything reasonable together, and would suggest you upgrade userland.

**Comment by temask88** [comment]
> I'm p. sure "0.8.x userland and git master kernel module" aren't expected to do anything reasonable together, and would suggest you upgrade userland.
> 
> edit: once you've done that, since I doubt that alone will impact this, what happens if you `zpool detach newpool draid2-0-0`?

updated to 2.1.0, although it was originally installed. did not notice at what point the version rolled back to 0.8.x.
After zpool detach newpool draid2-0-0 spare returned to AVAIL status.
Thanks.

Shouldn't the span switch itself off after replacing the disk and return to the AVAIL state. or the reason for this is the userland and git master kernel module version?

**Comment by rincebrain** [comment]
Disclaimer: I don't regularly use ZFS hot spares, so this is not based on a lot of actual use

My initial guess was something went awry with the drastically mismatched userland/kernel versions, but looking at it, my guess is that you did a `zpool replace [POOL] [OLDDISK] [REPLACEMENT]`, when if you had done `zpool replace [POOL] [SPARE] [REPLACEMENT]` it would have done what you expected and just dropped the hot spare back into AVAIL. (`zpool history [POOL] | grep replace`  can probably confirm that if your pool isn't so incredibly busy that it fell off the end of the history list, which is finite, but large).

If I'm correct, then the question becomes whether that should be the behavior - the operator did explicitly replace the failed drive, not the spare. Curiously, [this Sun blogpost](http://dtrace.org/blogs/eschrock/2006/06/06/zfs-hot-spares/) seems to suggest the expected behavior is to detach the spare without your involvement, while [Oracle's docs](https://docs.oracle.com/cd/E53394_01/html/E54801/gpegp.html) seem to suggest they expect operators to explicitly detach afterward. 

I don't know whether that's a change in expectation pre or post-fork, the original blogpost was wrong, or something else is going on here - for example, if it's expected that zed would do the spare detach, but zed was either not running or confused by the version differential, that could result in this too. You could go look through syslog for zed messages and see if it got something that looks like it should have caused this - or `zpool events` if you haven't rebooted since.

I don't see any obvious references (at a casual glance) to detach calls in zed, though, so it seems improbable that that specific case is what happened.

Perhaps someone will pop up and clarify what the expected behavior is, and then it's an opportunity to add a line in the **Hot Spares** section of `zpoolconcepts(7)`.

I'll go poke around and see what it does for me on a not-mismatched system...

**Comment by temask88** [comment]
the disk was not changed manually. set up autoreplace = on.

in the log at the time of disk replacement:
Aug 06 10:52:13 zfs-store zed[2782272]: eid=1605 class=config_sync pool_guid=0xB6ED1BF173BC4918
Aug 06 10:51:59 zfs-store zed[2595687]: eid=1604 class=vdev.unknown pool_guid=0xB6ED1BF173BC4918 vdev_path=/dev/sdc1
Aug 06 10:51:57 zfs-store zed[2595548]: eid=1603 class=config_sync pool_guid=0xB6ED1BF173BC4918

**Comment by rincebrain** [comment]
That fits.

[I'd venture to say that it's expected that it gets detached automatically, and zed isn't required.](https://gist.github.com/rincebrain/da72002024c3219abc229ad04305a1ce)

Anything from zed around when the replace finished?
