### ISSUE TITLE
Unable to use NFS shares with Zpool

### ISSUE THREAD

**Issue by MetallicTsun** [openzfs/zfs#12509]
<html><body>
<h3>System information</h3>

Type | Version/Name
-- | --
Distribution Name | Debian Bullseye
Distribution Version | 11.0
Kernel Version | 4.9.0-12-amd64
Architecture | x86_64
OpenZFS Version | zfs-2.1.0-1

</body>
</html>

### Describe the problem you're observing

I have a single raidz2 pool that after upgrading to the latest version no longer with properly utilize NFS shares. This affects nfs-server and sharenfs= in zfs. the issue is when i share a folder or data set with NFS i cannot copy or move files FROM the share. i am however able to read and write to the share 'normally' although its slow.
if i copy a file from the share the process will basically hand and create a zero byte file and never complete the operation and no data is moved. this does not occur on zfs version 0.7 that is within debians repos. This also affects newly created pools.
i did find the below discussion which sounded like my issue

# https://github.com/openzfs/zfs/discussions/12370

here is output from zfs get all mediaStorage/Files
https://pastebin.com/NffcaeUs

`### Describe how to reproduce the problem
Compile ZFS 2.1.0-1 using these scripts:
https://github.com/kneutron/ansitest/blob/master/debian-compile-zfs--boojum.sh
https://github.com/kneutron/ansitest/blob/master/ubuntu_zfs_build_install.sh
on a debian machine. create a pool and share it with nfs-server or sharenfs=. mount the server on a network machine or locally via 127.0.0.1. and try and copy a file from the share to the local machine

**Comment by rincebrain** [comment]
Right, I was looking at that, then got sidetracked by something catastrophic.

I guess I'll go back to looking at it...

Aside: I wouldn't call Debian 11 with a Debian 9 kernel Debian 11...

**Comment by MetallicTsun** [comment]
> Aside: I wouldn't call Debian 11 with a Debian 9 kernel Debian 11...

i would have to agree but due to driver issues with my host bus adapter that interfaces with the disks in this pool i am unable to upgrade to kernels above the installed one. i havent been able to diagnose as it cripples my zfs pool

**Comment by rincebrain** [comment]
Hey, check this out.
```
$ dd if=/mntdumb/zfs_vanilla/config.log of=/tmp/blackhole/zfs_vanilla/config.log bs=131072 iflag=direct
1+1 records in
1+1 records out
160105 bytes (160 kB, 156 KiB) copied, 0.0006609 s, 242 MB/s
$ dd if=/mntdumb/zfs_vanilla/config.log of=/tmp/blackhole/zfs_vanilla/config.log bs=131073 iflag=direct
[wait 30s]
^C
[requires kicking the mount with umount -f to get it to come back...]
dd: error reading '/mntdumb/zfs_vanilla/config.log': Input/output error
0+0 records in
0+0 records out
0 bytes copied, 1.5938 s, 0.0 kB/s
$
```

So apparently a workaround is {r,w}size=131072, for now.

Because if I mount with those (I was mounted with =256k before)...
```
$ dd if=/mntdumb/zfs_vanilla/config.log of=/tmp/blackhole/zfs_vanilla/config.log bs=131073 iflag=direct
1+1 records in
1+1 records out
160105 bytes (160 kB, 156 KiB) copied, 0.00061106 s, 262 MB/s
$ dd if=/mntdumb/zfs_vanilla/config.log of=/tmp/blackhole/zfs_vanilla/config.log bs=131072 iflag=direct
1+1 records in
1+1 records out
160105 bytes (160 kB, 156 KiB) copied, 0.000608195 s, 263 MB/s
$
```

Still digging...

**Comment by rincebrain** [comment]
It seems like what happens when I try doing bs=1M iflag=direct over NFS with [rw]size=1048576, on my Debian 9 and 10 testbeds, is something like:
* on 4.9.x, we go into dmu_read_uio_dnode initially with size=1M, dmu_buf_hold_array_by_dnode sets numbufs=8 and db->db_size=128k, but our poor uio->uio_iter is an ITER_PIPE, and consists of 16 4k buffers. So we go into zfs_uiomove_iter, read 16x4k and return - but because numbufs=8, we then go through the loop again, and EFAULT out because shockingly, our 4k sized buffers are still full...which [generic_file_splice_read turns into EAGAIN](https://elixir.bootlin.com/linux/v4.9.280/source/fs/splice.c#L297). which bubbles up...and then somebody just requests the thing from the start again and the comedy begins anew.
* On 4.19, this doesn't happen...because dmu_read_uio_dnode (always? at least in my NFS experimenting) gets invoked with size=64k, so numbufs=1 and we never run into this.

If we hardcode size to 64k, then we don't run into this on 4.9 or 4.19. If we hardcode size to 128k, then we run into it on both.

Next experiment is going to be patching all that debug information into the pre-1c2358c tree and see how it functioned, and run this on e.g. 5.10 and see how it looks there, and then go look at how this looks for local accesses. I'm tempted to just suggest not returning EAGAIN if we read any bytes, but don't feel confident that won't have some  side effect somewhere...
