### ISSUE TITLE
Incremental receive (quietly) failing in some scenarios

### ISSUE THREAD

**Issue by foxmox** [openzfs/zfs#12661]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Proxmox VE
Distribution Version	| since 6.4
Kernel Version	| since 5.4.86-1-pve
Architecture	| amd64
OpenZFS Version	| since zfs-kmod-2.0.1-pve1

### Describe the problem you're observing

Sometimes receiving an incremental stream ignores a snapshot from the source. And in a slightly different scenario there is an error (see below for the script used).

Snapshot D is quietly ignored:
````
root@pve701 ~ # ./sendrec.sh myzpool A D
full send of myzpool/recvbug@A estimated size is 42.6K
send from @A to myzpool/recvbug@B estimated size is 624B
send from @B to myzpool/recvbug@C estimated size is 624B
total estimated size is 43.8K
skipping snapshot myzpool/recvbug@E because it was created after the destination snapshot (D)
send from @A to myzpool/recvbug@B estimated size is 624B
send from @B to myzpool/recvbug@D estimated size is 624B
total estimated size is 1.22K
NAME                    USED  AVAIL     REFER  MOUNTPOINT
myzpool/recvbug_rep@A     0B      -       96K  -
myzpool/recvbug_rep@B     0B      -       96K  -
````

Error about mismatch with incremental source:
````
root@pve701 ~ # ./sendrec.sh myzpool A E
full send of myzpool/recvbug@A estimated size is 42.6K
send from @A to myzpool/recvbug@B estimated size is 624B
send from @B to myzpool/recvbug@C estimated size is 624B
total estimated size is 43.8K
send from @A to myzpool/recvbug@B estimated size is 624B
send from @B to myzpool/recvbug@D estimated size is 624B
send from @D to myzpool/recvbug@E estimated size is 624B
total estimated size is 1.83K
cannot receive incremental stream: most recent snapshot of myzpool/recvbug_rep does not
match incremental source
NAME                    USED  AVAIL     REFER  MOUNTPOINT
myzpool/recvbug_rep@A     0B      -       96K  -
myzpool/recvbug_rep@B     0B      -       96K  -
````

If there is a delta between the snapshots, both commands work as expected.

This is a regression from 0.8.5. With zfs-kmod-0.8.5-pve1, both commands worked as expected. Bisecting led to 30af21b02569ac192f52ce6e6511015f8a8d5729 "Implement Redacted Send/Receive" as the first bad commit. Version of user space tools did not seem to matter, while bisecting I used zfs-0.8.5-pve1.

The send stream remained identical between a working and non-working version (of course without recreating the datasets), so this seems to be a problem with receive.

### Describe how to reproduce the problem

The following script should reproduce the problems:
````
#!/bin/bash
pool=$1
from=$2
to=$3
source=$pool/recvbug
target=$pool/recvbug_rep
zfs destroy -r $source
zfs destroy -r $target
zfs create $source
zfs snapshot $source@A
zfs snapshot $source@B
zfs snapshot $source@C
zfs send -Rpv $source@C | zfs receive -F $target
zfs destroy $source@C
zfs snapshot $source@D
zfs snapshot $source@E
zfs send -Rpv -I $source@$from $source@$to | zfs receive -F $target
zfs list -t snap $target
````

### Include any warning/errors/backtraces from the system logs

No warnings/errors in the system logs.

**Comment by foxmox** [comment]
@pcd1193182 any hunch what it could be? Or suggestion for where to start looking if I were to try and tackle this?

**Comment by pcd1193182** [comment]
For the A-D case, it looks like what's happening is that `zfs receive -F` decides to discard snapshot C because it isn't present in the source's send package, but it doesn't skip the A-B stream. Comments suggest that `zfs_receive_one()` should handle that case by eating the EEXIST and driving the receive on, but it appears to not be happening correctly. I'll dig in further, hopefully this should be easy to resolve and write a test case for. I haven't looked at the A-E case yet, but my guess is that after the B-D incremental gets skipped, the D-E is attempted and fails because D was never received.

**Comment by pcd1193182** [comment]
It looks like the change that caused the issue is that `dmu_recv_begin` now grabs the payload of the BEGIN record and the next header, which in the case of this empty stream is the END record. This change was made to pull the list of redaction snapshots from the begin record's nvlist payload into memory so we can do things in the receive begin synctasks. This confuses `recv_skip` into skipping the B-D stream entirely, so it never gets received. The fix here is probably to try to do the check for if the tosnap exists before we do `receive_read_payload_and_next_header` in `dmu_recv_begin`, or to have `recv_skip` somehow peek at the next record instead of consuming it, but I will investigate further.
