### ISSUE TITLE
Official support for linux kernel 5.15

### ISSUE THREAD

**Issue by lvd2** [openzfs/zfs#12786]
### How will this feature improve OpenZFS?

5.14 kernel is EOL now and 5.15 is going to be next LTS.

**Comment by rincebrain** [comment]
Currently 5.15 works fine with 2.0.6 and 2.1.1 as far as anyone's found; I believe the only reason it's not listed is that they both predate 5.15's actual release.

That said, whenever 2.1.2 and 2.0.7 drop, I would expect the supported range to include it.

**Comment by Evernow** [comment]
> Currently 5.15 works fine with 2.0.6 and 2.1.1 as far as anyone's found; I believe the only reason it's not listed is that they both predate 5.15's actual release.
> 
> That said, whenever 2.1.2 and 2.0.7 drop, I would expect the supported range to include it.

Usually the META file is updated to indicate this though, I don't see it updated in any branch: https://github.com/openzfs/zfs/blob/master/META

**Comment by rincebrain** [comment]
If you look at the timing of the commits versus releases, those seem to have always happened a couple days before a new release of 2.0.x or 2.1.x that included support for it, so I would guess that such a commit will turn up around when the open PRs for 2.0.7/2.1.2 get merged into their respective branches in order to include it in them.

**Comment by jgottula** [comment]
Arguably, I'm not sure that official support for kernels above 5.12 should technically have ever been claimed in 2.0.6/2.1.0/2.1.1 due to #12301. 😬 (Perhaps my fault, for not bringing up the supported kernel range thing at the time.)

Fortunately, #12759 got merged to master today and I suspect will make its way into 2.0.7 and 2.1.2 as well.

**Comment by univerz** [comment]
what is the usual openzfs release cadence? it's really unfortunate that filesystem is blocking kernel update.

**Comment by lvd2** [comment]
Now that there's official 2.1.2 release, this issue is fixed
