### ISSUE TITLE
"zfs send -I"  sends data before deciding it should have ignored the data.  

### ISSUE THREAD

**Issue by tandersn** [openzfs/zfs#12927]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  centos 
Distribution Version	|  7
Kernel Version	| 4.19.211-1
Architecture	|  x86_64
OpenZFS Version	| zfs-2.1.1-1

### Describe the problem you're observing
When sending a range of snapshots using -I to make the set of snapshots on the replicant be identical to the primary, the zfs send seems to actually send all the data, before deciding that it is going to ignore the snapshots that already exist.
### Describe how to reproduce the problem
zfs create a_filesystem
zfs snapshot a_filesystem@a
copy some data to a_filsystem
zfs snapshot a_filesystem@b
copy some data to a_filsystem
zfs snapshot a_filesystem@c
copy some data to a_filsystem
zfs snapshot a_filesystem@d

zfs send -R a_filesystem@d |zfs receive offsitepool

copy some data to a_filsystem
zfs snapshot a_filesystem@e

zfs destroy zfs snapshot a_filesystem@c

zfs send -I  a_filesystem@a  a_filesystem@e |pv|zfs receive offsitepool

you will see 'pv' report that it transfers the data through the pipe, and when done, then says "already exists, ignoring".

**Comment by rincebrain** [comment]
I think if you did send -RI a_filesystem@d a_filesystem@e | zfs recv -F, it would do what you wanted without excess transfer, assuming you really want the ones that didn't exist on the source to go away.

**Comment by tandersn** [comment]
> I think if you did send -RI a_filesystem@d a_filesystem@e | zfs recv -F, it would do what you wanted without excess transfer, assuming you really want the ones that didn't exist on the source to go away.

I'm not sure you understood the point of my bug report. -RI doesn't seem to change anything.  When sending a range of snapshots, where some of them already exist on the target, the snapshot is sent, and THEN the check is made to see if it already exists. It should be the other way around.  The check to see if the destination shapshot exists should be made, before the data is sent.  The way it works now, the data is needlessly sent. 

In the example steps above, the amount of data in the steps "copy data to a_filesystem" should be big enough to be measured, like a few 100MB at least. Then use `pv` and you can see.

**Comment by rincebrain** [comment]
How are you proposing that the receiver tell the sender which snapshots are already present over a one-way connection from sender to receiver?

Yes, -RI would still include all the snapshots named, but importantly, it also includes in the send stream every snapshot on the source, and if you use recv -F, it will nuke all snapshots that don't exist on the sender.

**Comment by tandersn** [comment]
> How are you proposing that the receiver tell the sender which snapshots are already present over a one-way connection from sender to receiver?
> 
> Yes, -RI would still include all the snapshots named, but importantly, it also includes in the send stream every snapshot on the source, and if you use recv -F, it will nuke all snapshots that don't exist on the sender.

This isn't about flags, changing flags doesn't change the outcome.  It's an order of operations issue. I wouldn't say it is "one way", information is returned to the sender in the form of:  "snap a_filesystem@b already exists; ignoring "

When  sending a range of snapshots, where some of the snapshots already exist on the target, the information returned says:  "already exists; ignoring".  So it already DOES return the information that the snapshot exists, and that it is ignoring it.  The issue is that is sends all the data of the snapshot BEFORE deciding to ignore it, rather than just sending the header or even just the GUID first to see if it exists before continuing to send the bulk of the data in the snapshot.

So right now it:

Sends snapshot, all information ABOUT the snapshot and all the DATA of the snapshot itself (which can be TBs),  then realizes it is already there, and returns: " already exists; ignoring".  

I propose:

Send the header or the guid of the snapshot only, check and see if that exits, and return " already exists; ignoring" without sending all the data. 

If you run through the example i posted, using the `pv` command, you can see it send the data before getting to the point where it returns " already exists; ignoring",  rather than just sending the GUID first, checking that, and then returning  "already exists; ignoring".

**Comment by rincebrain** [comment]
Using `zfs send -I foo@d foo@e` instead of `zfs send -I foo@a foo@e` would avoid sending the earlier snapshots, and using -R and -F would allow you to remove ones that have since been removed on the sender on the receiver.

Your objection appears to be that you're specifying a much larger range of snapshots and then want ZFS to set up a backchannel to "know" that actually some of those are already on the receiver and just not send them.

When you run a command like `zfs send | ssh dst zfs recv`, the stdout+stderr of zfs recv is connected to your terminal, not to `zfs send` - `zfs send` has no way of hearing a response from `zfs recv` other than an error from "my stdout errored on write".

`zfs recv` is the one printing "already present, ignoring", not `zfs send`.

I understand your example. You're requesting it send all of the snapshots between a and e, and then would like it to not do that if they already exist on the receiver.

One could set up a backchannel for that information in various ways (I'm a fan of the sneaky way Oracle passes resumable send/recv state via `ssh dst zfs recv --resume | zfs send --take-input-from-stdin | ssh dst zfs recv`, for example), but I don't really see the increased complexity as a win versus just specifying which range of snapshots to send in the first place?

**Comment by gmelikov** [comment]
@tandersn the point @rincebrain already mentioned is that `zfs send` doesn't know anything about `zfs recv` side, so it doesn't know about snapshots on receiving side. It's a one side stream with everything that you asked to send.

**Comment by tandersn** [comment]
I get what you guys are saying now, for some reason i was thinking that zfs send would have access to the response zfs recv was giving (the already exists response). 

@rincebrain what i am trying to do, and the reason why your example doesn't quite solve my problem, is that i am doing something a little different with my snapshots, it's more complex than my simplistic example.  Doing the `-I snap@a snap@e | zfs receive`  (e.g. the entire range) was a very easy way to handle it.  Basically what i am doing, is taking daily snapshots the normal way (every day). Then every week, the oldest daily is renamed to the weekly. Then every month, the oldest weekly is renamed to the monthly.  The  `-I snap@a snap@e` (full range) method makes the replicant look just like the primary by fixing up the names on the replicant to match the primary.  it was just an easy way to keep them all sync'd up and it worked fine in my testing. When i put it into production on the fileservers is when i noticed it was actually transferring the data, which doesn't work in production because it takes too long.  Using -R isn't ideal because sometimes we have to delete snapshots on the primary to free up space, but don't want those deleted on the backup server in case someone submits a restore request. 

for background, the reason i am trying to do my snapshots this way, is for 2 reasons:  1) it allows for less overall snapshots with the same retention criteria (in our old method, on a day where Sunday falls on the 1st, there would be 3 snapshots taken that day in a normal daily/weekly/monthly setup) and the decreased number of snapshots has a performance advantage when doing zfs list (some of our home directory file servers are set up with individual filesystems for each student, so 300 students x ~70 snapshots vs 300 students x 45 snapshots is noticeable).  2)  students and faculty do funny things and sometimes write programs that write TBs of junk data and it takes us a few days to find it and clean it up. If the student happened to do this during a time when the monthly was taken, we have to delete that monthly to clear it out, and that removes the ability to restore any legit file from that monthly later on.  

I've already written a workaround, by first syncing up the names before i do my sends now.  I perceived this as a bug, but now it sounds like it is just "the way things have to be" so i guess just close this out?  

Thanks for your time and effort in responding to me.

**Comment by GregorKopka** [comment]
As a late reply:
I would suggest to label the snapshots something like @\`date +%Y%m%d%h%m\` and then structure your scripts to

1. Pull from the backup source, instead of pushing to the target:
This will prevent a compromised source to also nuke the backups by simply logging in through the ssh connection.
2. Never ever use -F on recv:
Else a compromised source could simply wipe the dataset contents, remove the existing snapshots and make a new one, then the next backup cycle would destroy the backups (by snapshots being removed and datasets being overwritten with empty ones)
3. Always filter properties:
Else as a dataset received with something like `mountpoint=/root/.ssh` would be a root compromise of the backup server.
4. Hold the last snapshot pulled:
So it'll be available for the next cycle
5. Run retention policy on the backup server:
Keep snapshot history on the backup according to your needs by pruning the ones no longer needed.

This will result in a much more resilient backup system.
