### ISSUE TITLE
Cannot zfs receive unencrypted dataset as a child of encrypted dataset ('cannot receive new filesystem stream: inherited key must be loaded')

### ISSUE THREAD

**Issue by rsplaul** [openzfs/zfs#13033]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| bookworm/sid
Kernel Version	| 5.15.0-2-amd64
Architecture	| amd64
OpenZFS Version	| zfs-2.1.2-1 / zfs-kmod-2.1.2-1

### Describe the problem you're observing

When receiving an unencrypted dataset as a child of an encrypted dataset, `zfs receive` complains with 'cannot receive new filesystem stream: inherited key must be loaded'

### Describe how to reproduce the problem
```
zpool create pool1 /path/to/dev1
zpool create pool2 /path/to/dev2
zfs create -o encryption=on -o keyformat=passphrase -o keylocation=prompt pool1/enc
zfs create -o encryption=off pool1/enc/noenc
zfs snap pool1/enc@snap
zfs snap pool1/enc/noenc@snap
zfs send -w pool1/enc@snap | zfs receive pool2/enc
zfs send -w pool1/enc/noenc@snap | zfs receive pool2/enc/noenc
```

### Include any warning/errors/backtraces from the system logs
n/a

### Additional remarks
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259231 obviously describes the same problem. However, it seems that the unencrypted dataset must be a child of an encrypted dataset on *both* sides to produce this behaviour.

**Comment by AttilaFueloep** [comment]
Yes, I can reproduce this. There are actually two issues here. The first one is with your sequence of commands. Since `pool1/enc/noenc` isn't encrypted  `zfs send -w pool1/enc/noenc@snap` is equivalent to `zfs send -Lec pool1/enc/noenc@snap`. This will generate a send stream without properties and the `zfs receive pool2/enc/noenc` will inherit all properties, including encryption, from `pool2/enc`, meaning the receive will encrypt `pool2/enc/noenc` on the fly. You also want to add `-u` to the receive since the parent `pool2/enc` isn't mounted. So you should either do
```
zfs snap -r pool1/enc@snap
zfs send -w pool1/enc@snap | zfs receive pool2/enc
zfs send -w pool1/enc/noenc@snap | zfs receive -u -o encryption=off pool2/enc/noenc
```
or
```
zfs snap -r pool1/enc@snap
zfs send -w pool1/enc@snap | zfs receive pool2/enc
zfs send -pw pool1/enc/noenc@snap | zfs receive -u pool2/enc/noenc
```
or even
```
zfs snap -r pool1/enc@snap
zfs send -Rw pool1/enc@snap | zfs receive -u pool2/enc 
```

Here comes  the second issue into play,  the above commands also fail with the same error message. This seems like a bug to me. The initial implementation of native encryption disallowed unencrypted datasets below encrypted ones. This restriction was removed in #8870 and it looks like `zfs receive` doesn't account for the case where an unencrypted dataset  is received unencrypted below an encrypted one while doing the check for the loaded key. I'll put this on my list of raw encrypted send/recv issues I'm looking into.

As a side note, I think that nesting unencrypted datasets  below encrypted ones is generally not a good idea, and I would try to avoid such a setup if possible. But I can see that here are setups that benefit from that.

As a workaround you can do
```
zfs send -w pool1/enc@snap | zfs receive pool2/enc
zfs load-key pool2/enc
zfs send -w pool1/enc/noenc@snap | zfs receive -o encryption=off pool2/enc/noenc
```
that works as intended but is less than ideal and may not be possible in certain scenarios at all.

**Comment by rsplaul** [comment]
Thanks for the explanations and your testing. Actually, the scenario in my case is a backup with [syncoid](https://github.com/jimsalterjrs/sanoidl) on a potentially untrusted low-performance backup-host, hence the idea to do a raw send (`--sendoptions=w`).

I agree, that nesting unencrypted datasets under encrypted datasets is probably not a good idea in the first place, but since such configurations are possible, `zfs receive` should somehow support them without breaking the "zero-knowledge principle" that allows for backups of encrypted datasets on untrusted hosts.

**Comment by AttilaFueloep** [comment]
> the scenario in my case is a backup with [syncoid](https://github.com/jimsalterjrs/sanoidl) on a potentially untrusted low-performance backup-host, hence the idea to do a raw send

Unfortunately that's one of the scenarios where loading the key isn't an option, yes.

> but since such configurations are possible, `zfs receive` should somehow support them without breaking the "zero-knowledge principle" that allows for backups of encrypted datasets on untrusted hosts.

That's right, it should work seamlessly.  Spotting the place where things fail is the hard part though ;-)

**Comment by gamanakis** [comment]
I can confirm that removing the `dsflags |= DS_HOLD_FLAG_DECRYPT;` resolves this.
Now we only have to find a proper conditional.

**Comment by AttilaFueloep** [comment]
Well, in `dmu_recv_begin_check()` we could test  if  the `drba->drba_dcp` nvlist contains `cp_crypt = ZIO_CRYPT_OFF`. I think that would imply that we are receiving with `-o encryption=off` or sending with `-p` an unencrypted dataset.

Since I'm new to this code please take everything I say with a grain of salt though.

**Comment by gamanakis** [comment]
Nice, I think that should work! Do you want to go ahead and file a PR?

**Comment by AttilaFueloep** [comment]
Yes, I can do that, but before doing so I'd like to trace this a bit more to get a better understanding of the inner workings. That way I'd feel more comfortable changing the code.

**Comment by AttilaFueloep** [comment]
@gamanakis Feeling sufficiently sure that this is the right approach now, I'm preparing a PR and would like to give you credit for the analysis by adding you as a co-author. Is that OK with you?

**Comment by gamanakis** [comment]
Sure, thank you!

**Comment by AttilaFueloep** [comment]
Opened PR #13076 with a fix.
