### ISSUE TITLE
OpenZFS on FreeBSD needs to support BIO_ORDERED

### ISSUE THREAD

**Issue by peterjeremy** [openzfs/zfs#13065]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 13.0-stable
Kernel Version	|  13.0-STABLE 0fc6eebbf763
Architecture	|  amd64
OpenZFS Version	|  zfs-2.1.2-FreeBSD_gaf88d47f1, zfs-kmod-2.1.2-FreeBSD_gaf88d47f1

### Describe the problem you're observing

OpenZFS doesn't include the BIO_ORDERED flag on bio operations it generates.  This allows the FreeBSD I/O subsystem to arbitrarily reorder I/O operations, which breaks ZFS expectations regarding which data is on stable storage.

### Describe how to reproduce the problem

1) OpenZFS code search.
2) With a geom_gate(4) patched to detect BIO_ORDERED operations, do a `zpool create`, `zfs recv` and `zpool export` to a geom_gate device and note the absence of any BIO_ORDERED operations.

### Include any warning/errors/backtraces from the system logs
N/A

**Comment by amotin** [comment]
For some time ZFS on FreeBSD indeed marked all BIO_FLUSH operations with BIO_ORDERED flag.  But from one side it badly affected NVMe performance, since NVMe with its multiple queues makes its implementation problematic, while from another ZFS always waits for depending writes to complete before sending BIO_FLUSH requests, so explicit request ordering is not required.  So I've removed that.  Do you know any specific scenario where any expectations are broken?

**Comment by peterjeremy** [comment]
There was some discussion regarding BIO reordering in freebsd-fs@FreeBSD.org and some messages around https://lists.freebsd.org/archives/freebsd-fs/2022-February/000696.html noted that OpenZFS didn't appear to use BIO_ORDERED.  If OpenZFS internally serialises IO requests then this bug is probably obsolete.

**Comment by freqlabs** [comment]
Seems not applicable.
