### ISSUE TITLE
zfs process freeze spl_delay_taskq

### ISSUE THREAD

**Issue by chriruch** [openzfs/zfs#13160]
Distribution: Debian
Distribution Version: Bullseye
Linux Kernel: 5.10.92-1
Architecture: x86_64
ZFS Version: 2.1.2-1-bpo11+1

I am experiencing freezes on zfs processes on my backup server. Subsequent processes accessing resources locked by frozen processes freeze also. Frozen processes cannot be killed. Soft-reboot fails. Other zfs resources on same pool are working fine after the freeze. In the logs two occurences one at 2022-02-27 01:12, the second 2022-02-28 01:33. A hard reboot has been made 2022-02-27 21:38. The queue scheduler of the raidz members have been changed from md-deadline to none after the reboot without success.

The pool was created one month ago, fragmentation is 2% and the load is very low. The pool stores backups, it contains 117 datasets, no zvols, and 5242 snapshots. No NFS configured. Data is collected by zfs send/receive and rsync.

[tk5_dpkg.txt](https://github.com/openzfs/zfs/files/8152627/tk5_dpkg.txt)
[tk5_syslog.log](https://github.com/openzfs/zfs/files/8152628/tk5_syslog.log)
[tk5_uname.txt](https://github.com/openzfs/zfs/files/8152629/tk5_uname.txt)
[tk5_zpool_status.txt](https://github.com/openzfs/zfs/files/8152630/tk5_zpool_status.txt)
[tk5_dmesg.log](https://github.com/openzfs/zfs/files/8152631/tk5_dmesg.log)
[tk5_zpool_list.txt](https://github.com/openzfs/zfs/files/8164842/tk5_zpool_list.txt)

**Comment by supercoincoin** [comment]
Hello,
I second this post, i observed the same issue.


### System information
Type	Version/Name
Distribution Name	Debian
Distribution Version	Bullseye
Linux Kernel	5.10.84-1
Architecture	x86_64
ZFS Version	2.1.2-1-bpo11+1
SPL Version	?

Same behavior as described, had to (hard) reboot to recover from situation.
Also changed the scheduler for none but wasn't enough. In order to avoid this issue i've to drastically reduce number of snapshots on datasets to about a third of the original number (~170 > ~60).
The pool consists of one RAIDZ1 Vdev with 4 x 10TB SATA HDD, no L2ARC, server have 32GB of RAM of which 8GB are used for ARC, 59 datasets (38 filesystems, 21 zvol).
Doesn't seems to be related to system load (load average below 1 most of time) but more than on "zfs list -t snapshot" and some "intensive" commands like this. For information, 0% of fragmentation (system installed few time ago).

Thank in advance.

[fs2_kern.log](https://github.com/openzfs/zfs/files/8160051/fs2_kern.log)
[fs2_zpool_status.txt](https://github.com/openzfs/zfs/files/8160052/fs2_zpool_status.txt)
[fs2_uname.txt](https://github.com/openzfs/zfs/files/8160053/fs2_uname.txt)

**Comment by chriruch** [comment]
Similar fault on a different Debian Bookworm System.

System information

Type Version/Name
Distribution Name Debian
Distribution Version Bookworm
Linux Kernel 5.16.7-2j
Architecture x86_64
ZFS Version 2.1.2-1
SPL Version ?

[zorin_kern.log](https://github.com/openzfs/zfs/files/8233806/zorin_kern.log)
[zorin_uname.txt](https://github.com/openzfs/zfs/files/8233807/zorin_uname.txt)
[zorin_zpool.txt](https://github.com/openzfs/zfs/files/8233808/zorin_zpool.txt)
[zorin_dmesg.log](https://github.com/openzfs/zfs/files/8233809/zorin_dmesg.log)

**Comment by chriruch** [comment]
Similar, this time arc_prune blocked

[zorin_kern2.log](https://github.com/openzfs/zfs/files/8303651/zorin_kern2.log)
[zorin_ps2.log](https://github.com/openzfs/zfs/files/8303652/zorin_ps2.log)
[zorin_dmesg2.log](https://github.com/openzfs/zfs/files/8303653/zorin_dmesg2.log)

**Comment by chriruch** [comment]
This time after kernel panic

[zorin_ps3.txt](https://github.com/openzfs/zfs/files/8369912/zorin_ps3.txt)
[zorin_kern3.log](https://github.com/openzfs/zfs/files/8369913/zorin_kern3.log)
[zorin_dmesg3.log](https://github.com/openzfs/zfs/files/8369916/zorin_dmesg3.log)
[zorin_history3.txt](https://github.com/openzfs/zfs/files/8369917/zorin_history3.txt)
