### ISSUE TITLE
fio hang forever and process is not killable when remove a device of basic pool

### ISSUE THREAD

**Issue by why0406** [openzfs/zfs#13626]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|  CentOS Linux 8
Distribution Version	|
Kernel Version	|  4.18.0-240.el8.x86_64
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.3-1 zfs-kmod-2.1.3-1

### Describe the problem you're observing
1. The basic pool is SUSPENDED after removed a device from server.
2. And the device had been removed is till online when check `zpool status`, maybe it should be UNAVAIL ?
3. The fio hang forever
4.`zfs clear` does not  take effect when reconnect the removed device, the state of zpool is online again Only after reboot the server

### Describe how to reproduce the problem
1.  create a basic pool `zpool create zfsraid0 /dev/sdg /dev/sdh -m /mnt/zfs/`
2. Tesing IOPS by fio `fio -directory=/mnt/zfs/ -direct=1 -iodepth 64 -thread -rw=write -ioengine=libaio -bs=1024k -size=10G -group_reporting -name=testio`
3. Remove the device /dev/sdh from my server
5. Then the IOPS reduce to zero FOREVER and  fio process is not killable
6. The zpool status is  shown below
```
# zpool status zfsraid0
  pool: zfsraid0
 state: SUSPENDED
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-HC
config:

        NAME        STATE     READ WRITE CKSUM
        zfsraid0    ONLINE       0     0     0
          sdg       ONLINE       0     0     0
          sdh       ONLINE       6   146     0
errors: List of errors unavailable: pool I/O is currently suspended

errors: 71 data errors, use '-v' for a list
```

**Comment by rincebrain** [comment]
(Any particular reason you're running 2.1.3? 2.1.5 is the latest stable release.)

You might find `zpool clear zfsraid0 sdh` more successful than `zpool clear zfsraid0`, incidentally.

I'm not sure what you initially expected - you removed a non-redundant disk from a pool, it was never going to keep running after you did that.

Usually, the system will notice correctly when you reconnect a disk that vanished, assuming it got the same name. If it didn't, which can often happen with sdX names, you do indeed basically have no options other than rebooting. (See #11082 for where there's work being done to let you forcibly eject a pool that is suspended or faulted, but it turns out to be rather hard to correctly release all the possible places you might be holding a lock when that happened...)

**Comment by why0406** [comment]
Thanks a lot
