### ISSUE TITLE
No ZFS support for kernel 4.18.0-372.16.1.el8_6.x86_64 ???

### ISSUE THREAD

**Issue by yolilef** [openzfs/zfs#13668]
### System information

Type |  RHEL
Distribution Name	| Red Hat Enterprise Linux release 8.6 (Ootpa)
Distribution Version	| 8.6 (Ootpa)
Kernel Version	|  4.18.0-372.16.1.el8_6.x86_64
Architecture	| x86_64
OpenZFS Version	| l  zfs-2.1.5-1.el8.x86_64

### Describe the problem you're observing
I update my RHEL servers yesterday (kernel versio changing from 4.18.0-372.13.1.el8_6.x86_64 to 4.18.0-372.16.1.el8_6.x86_64). I use the kABI-tracking kmod. It seems than the ZFS version is not supported for the new version of the kernel because the zfs modules are not generated in /lib/modules/4.18.0-372.16.1.el8_6.x86_64 (the modules has been generated in 4.18.0-372.13.1.el8_6.x86_64 branch).

## Describe how to reproduce the problem

I try to desinstall ou reinstall the zfs packages, by following the intructions which are on this page : https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/index.html ... but with no success

### Include any warning/errors/backtraces from the system logs

**Comment by tmcqueen-materials** [comment]
This is not surprising. `iov_iter_fault_in_readable` is not in the list of whitelisted kABI interfaces that are guaranteed to remain unchanged within a release, so it is one (of a number ZFS uses) that can change even between minor releases. According to the full release notes:

https://lwn.net/Articles/901685/

They made a lot of fixes to gfs2 which included backporting the `iov_iter_fault_in_readable` to `fault_in_iov_iter_readable` change from the 5.x kernel series. So a new kmod for 16.1 is needed (or just use dkms since the patch to support this name change already exists in 2.1.5).

**Comment by behlendorf** [comment]
Thankfully this kind of interface change isn't common within a RHEL minor release cycle, but it clearly can happen since OpenZFS does use symbols beyond the defined kABI.  For the moment you'll want to switch to the dkms packages or rollback your kernel until new kmods can be built for the latest kernel.

**Comment by yolilef** [comment]
Hi Brian, Hello the Open Zfs team,

Thank you for your answers and your help. I have switched to the previous kernel and i will install the dkms version of open zfs if there is no other solution.

Have à nice day and sorry for my poor english.

Olivier L.
University of Rouen

Envoyé de mon iPhone

**Comment by tonyhutter** [comment]
Please try updating again - I just re-built the EL8 RPMs with the new kernel and pushed them out (the RPMs are labeled "zfs-2.1.5-2")

**Comment by yolilef** [comment]
Hi Tony,

Thank you for your help. This update works fine with the last kernel update of RHEL 8.6 … 

Have a nice day,

Cordially,

O.L.
University of Rouen Normandy
