### ISSUE TITLE
Adaptive MFU/MRU seems broken

### ISSUE THREAD

**Issue by shodanshok** [openzfs/zfs#14120]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux
Distribution Version	| 8.6
Kernel Version	| 4.18.0-372.26.1.el8_6.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.1.99-1501_g07de86923

### Describe the problem you're observing
MRU become very large when reading a big file for the first time, leading to extreme and unexpected MFU shrink. Moreover, re-reading a previously MFU-cached file shows degraded performance.

Please note that the same effect can be obtained by writing new data, with MRU again completely displacing MFU.

This means MFU cache is effectively over-shadowed by less valuable MRU cache, breaking ARC adaptive nature.

### Describe how to reproduce the problem

```
# disabling prefetch for easing debug, but the same happens with prefetch enabled
echo 1 > /sys/module/zfs/parameters/zfs_prefetch_disable

# test.img is 3.8G, test2.img is 3.6G
# first read
[root@localhost ~]# dd if=/tank/test/test.img of=/dev/null bs=1M status=progress
2768240640 bytes (2.8 GB, 2.6 GiB) copied, 2 s, 1.4 GB/s
3800+0 records in
3800+0 records out
3984588800 bytes (4.0 GB, 3.7 GiB) copied, 2.88245 s, 1.4 GB/s

# second read to move it in MFU
[root@localhost ~]# dd if=/tank/test/test.img of=/dev/null bs=1M status=progress
3800+0 records in
3800+0 records out
3984588800 bytes (4.0 GB, 3.7 GiB) copied, 0.78748 s, 5.1 GB/s

# MFU is 3.8G
ARC size (current):                                    98.4 %    3.8 GiB
        Target size (adaptive):                       100.0 %    3.9 GiB
        Min size (hard limit):                          6.2 %  248.6 MiB
        Max size (high water):                           16:1    3.9 GiB
        Most Frequently Used (MFU) cache size:        100.0 %    3.8 GiB
        Most Recently Used (MRU) cache size:          < 0.1 %    1.9 MiB
        Metadata cache size (hard limit):              75.0 %    2.9 GiB
        Metadata cache size (current):                  0.1 %    3.8 MiB
        Dnode cache size (hard limit):                 10.0 %  298.4 MiB
        Dnode cache size (current):                   < 0.1 %   93.2 KiB

# reading test2.img for the first time
[root@localhost ~]# dd if=/tank/test/test2.img of=/dev/null bs=1M status=progress
3348103168 bytes (3.3 GB, 3.1 GiB) copied, 4 s, 837 MB/s
3639+0 records in
3639+0 records out
3815768064 bytes (3.8 GB, 3.6 GiB) copied, 4.63754 s, 823 MB/s

# MFU was almost completely evicted by MRU
ARC size (current):                                    99.7 %    3.9 GiB
        Target size (adaptive):                       100.0 %    3.9 GiB
        Min size (hard limit):                          6.2 %  248.6 MiB
        Max size (high water):                           16:1    3.9 GiB
        Most Frequently Used (MFU) cache size:          5.3 %  210.7 MiB
        Most Recently Used (MRU) cache size:           94.7 %    3.7 GiB
        Metadata cache size (hard limit):              75.0 %    2.9 GiB
        Metadata cache size (current):                  0.2 %    5.1 MiB
        Dnode cache size (hard limit):                 10.0 %  298.4 MiB
        Dnode cache size (current):                   < 0.1 %   96.1 KiB

# relative arcstat, note how ghost lists hit was 0
[root@localhost ~]# arcstat -f time,read,miss,miss%,dmis,dm%,pmis,pm%,mmis,mm%,size,c,avail,mru,mfug,mfu,mfug 1
    time  read  miss  miss%  dmis  dm%  pmis  pm%  mmis  mm%  size     c  avail   mru  mfug   mfu  mfug
12:04:21  1.2K   590     50   590   50     0    0     0    0  3.9G  3.9G   3.3G     4     0   586     0
12:04:22  1.9K   937     50   937   50     0    0     1    1  3.9G  3.9G   3.3G    58     0   881     0
12:04:23  1.6K   815     51   815   51     0    0     1    1  3.9G  3.9G   3.3G    68     0   746     0
12:04:24  1.8K   892     51   892   51     0    0     1    1  3.9G  3.9G   3.3G    66     0   825     0
12:04:25   754   377     50   377   50     0    0     0    0  3.9G  3.9G   3.3G     0     0   377     0

# try re-reading the first file (test.img) to re-populate MFU, notice the degraded performance...
[root@localhost ~]# dd if=/tank/test/test.img of=/dev/null bs=1M status=progress
2836398080 bytes (2.8 GB, 2.6 GiB) copied, 2 s, 1.4 GB/s
3800+0 records in
3800+0 records out
3984588800 bytes (4.0 GB, 3.7 GiB) copied, 2.73548 s, 1.5 GB/s

#...and how MFU does _not_ repopulate completely, with some data "locked" by MRU
ARC size (current):                                   100.0 %    3.9 GiB
        Target size (adaptive):                       100.0 %    3.9 GiB
        Min size (hard limit):                          6.2 %  248.6 MiB
        Max size (high water):                           16:1    3.9 GiB
        Most Frequently Used (MFU) cache size:         93.9 %    3.6 GiB
        Most Recently Used (MRU) cache size:            6.1 %  242.9 MiB
        Metadata cache size (hard limit):              75.0 %    2.9 GiB
        Metadata cache size (current):                  0.2 %    5.1 MiB
        Dnode cache size (hard limit):                 10.0 %  298.4 MiB
        Dnode cache size (current):                   < 0.1 %   96.1 KiB
```

### Include any warning/errors/backtraces from the system logs

None

**Comment by amotin** [comment]
Thinking about it I can speculate such scenario:
 - During the first read each access increases arc_p (MRU size) to the full ARC size.
 - During the second read buffers are migrated to MRU, but since there are no ARC evictions of ghost hits arc_p is not changed.
 - When you start reading second file, previous MFU data are dropped from ARC because arc_p tells that previously MRU hits worked really great.
 - When you are re-reading the first file again, ZFS sees plenty of MFU ghost hits and shrinks arc_p.
 - On following first file re-reads MRU can't drop to zero, probably being limited by arc_p_min_shift (1/16 of ARC size) -- exactly the 6% you see.

So looks like it all works as written. The only question is what we can do about it.  The only issue I see so far is that after the second stage arc_p does not represent actual ARC state due to huge amount of MRU to MFU promotions and no other activity.

**Comment by shodanshok** [comment]
I spent yesterday doing some tests and I can confirm your analysis above. During the first read, `arc_p` can grow unbounded following `arc_c` until `arc_c_max` is reached. This in turn cause pressure on eventual MFU cache until ARC ghost list are engaged and the cache adjusted via new `arc_p` values.

I am not sure this was the premise behind the original ARC paper, which seems to suggest the initial `arc_p` value as 1/2 `arc_c`, and indeed we have the very same idea in some place inside `arc.c` where `arc_p` is set via `arc_p == arc_c >> 1`. One should also note that with the current behavior we are initially *less* resistant to cache scan than the standard linux pagecache (with its fixed 50/50 active vs inactive pages).

I played with two different patches to alter such behavior:
- a more complex one which prevents `arc_p` to displace MFU until ARC ghost list are non-zero;
- a more simple one which simply restrict enlarging `arc_p` to 1/2 `arc_c`, leaving eventual larger adjustments to ARC ghost list.

Any interest on seeing/trying them, or do you feel ARC code is ok as is?

**Comment by amotin** [comment]
There is a flag called arc_warm, set when ARC first time hits eviction.  May be we could reset arc_p to current MRU size when it is set first time.  Originally ZFS started with arc_c set to arc_c_max and so the code at the end of arc_adapt() was not called, but I changed that, since it caused some other bad effects, and arc_warm was added to address few effects of the change.

**Comment by shodanshok** [comment]
I just opened a PR with a tentative fix, can you give it a look (and sorry for the multiple commit, I had issue updating my forked branch).

**Comment by aheid** [comment]
>     * During the second read buffers are migrated to MRU, but since there are no ARC evictions or ghost hits arc_p is not changed.

I'm assuming you meant migrated to MFU.
Potentially dumb question: If so, shouldn't arc_p be reduced every time a buffer is migrated from MRU to MFU?

**Comment by amotin** [comment]
> I'm assuming you meant migrated to MFU. 

RIght.  Fixed.

> Potentially dumb question: If so, shouldn't arc_p be reduced every time a buffer is migrated from MRU to MFU?

It is a good question, since I don't have a straight answer.  arc_p measures how many recently read bytes we should keep in cache to still expect hits.  The fact that some block was promoted to MFU does not affect that distance.  From this perspective it should not be reduced.  But since those promoted blocks are no longer in MRU, they won't cause eviction for other MRU blocks for some time.  Reduced arc_p could make eviction to work better in some cases, but since with list element removal we loose information where exactly the promoted buffer was in the MRU list, we can not know when exactly to evict the remaining buffers (some could be before, some after).  Proper solution, I think, would probably be to leave some sort of place-holders in the MRU list in case of promotion, to be used by eviction code.  In that case arc_p could remain unchanged on promotion.

**Comment by shodanshok** [comment]
> Potentially dumb question: If so, shouldn't arc_p be reduced every time a buffer is migrated from MRU to MFU?

I've (ugly) test patch which does something similar, reducing `arc_p` to be at most `arc_c - mfusize`. However, considering the adjustments done via ghost list are going to overcome (by design) current `arc_p limit`, I am not sure it is worthwhile to adding complexity to such performance-sensitive code.

**Comment by aheid** [comment]
Just wanted to say thank you @shodanshok for your work tracking down these ARC issues.

I was able to reproduce your findings reported in the initial post, on Ubuntu 22.10 with ZFS 2.1.5. Prefetch made no difference.

Now, I looked at the delta of `mru_hits` before and after doing a streaming read of an uncached iso file. With prefetch disabled, the number of MRU hits grew with just a few. Yet the MRU cache still forced out the MFU data.

From what I can understand, when a block is read, the ARC does a cache lookup, if it doesn't find it will issue a read and when block comes back it will put the block into MRU and return it. However, this in itself shouldn't increase the MRU size, only a hit in the MRU cache should do that. To me it seems wrong that the MRU is allowed to grow without the corresponding MRU hits.

With prefetch enabled, the number of MRU hits did match the uncached filesize, so in that respect it makes sense that the MRU cache grows in size, yet I'd still classify that as a bug. A prefetch hit shouldn't count as a MRU hit in my view.

**Comment by aheid** [comment]
> It is a good question, since I don't have a straight answer.

Thank you for the explanation, however I'm not sure I follow entirely. In `arc_change_state` it removes the block from one list and adds it to another. If the old was the MRU list and the new is the MFU list, then does it need to evict more from the MRU list? Isn't the transfer of the header an "eviction" as such?

It just seems to me that, if we assume the cache is at max size, then growing the MFU requires reducing the MRU. And since `arc_p` is used to determine how much to evict from MFU, then `arc_p` should be reduced when growing MFU.

Though I could be entirely mistaken.

**Comment by amotin** [comment]
> It just seems to me that, if we assume the cache is at max size, then growing the MFU requires reducing the MRU. And since `arc_p` is used to determine how much to evict from MFU, then `arc_p` should be reduced when growing MFU.

It it counter-intuitive, but no. Cache hits do not affect arc_p ("perfect" or "target" MRU/MFU distribution), it is "close misses" (ghost states hits) that do. Cache hits on opposite confirm that current MRU/MFU distribution is good and should be kept.  The fact that we hit MRU cache (and buffers promoted to MFU) means that current MRU caching distance is sufficient, while older MFU buffers can be evicted (despite we just added more) until we start seeing more mfu_ghost hits.

The only controversy appears from the fact that when we got MRU hits, some buffers could be counted as both MRU (because they are still recent) _and_ MFU (because they were hit more than once).  That is why I think we could implement a mechanism to _temporarily_ reduce arc_p in terms of cache size, but not in terms of time, and automatically restore it later when it would be the time for the promoted buffers to be evicted from MRU cache.

**Comment by aheid** [comment]
> It it counter-intuitive, but no.

Thank you for the follow-up explanation. I knew about the ghost hit logic yet managed to forget it when writing the post :(

I re-ran the tests while monitoring both regular and ghost hits for both MRU and MFU, again with prefetcher disabled. I reboot between runs to be sure it's uncached. Again, the final uncached read managed to fill the ARC with MRU, entirely displacing the existing MFU cache, yet as you can see there were no increase in ghost hits:

`Pre-run stats
-----------------------------------
mru_hits                        4    47677
mru_ghost_hits                  4    0
mfu_hits                        4    78561
mfu_ghost_hits                  4    0

ARC size (current):                                    99.9 %    3.9 GiB
        Target size (adaptive):                       100.0 %    3.9 GiB
        Target size (MRU):                             99.7 %    3.9 GiB
        Min size (hard limit):                          6.2 %  248.4 MiB
        Max size (high water):                           16:1    3.9 GiB
        Most Frequently Used (MFU) cache size:         96.7 %    3.7 GiB
        Most Recently Used (MRU) cache size:            3.3 %  129.2 MiB

Post-run stats
-----------------------------------
mru_hits                        4    54442
mru_ghost_hits                  4    0
mfu_hits                        4    102495
mfu_ghost_hits                  4    0

ARC size (current):                                    99.9 %    3.9 GiB
        Target size (adaptive):                       100.0 %    3.9 GiB
        Target size (MRU):                             99.7 %    3.9 GiB
        Min size (hard limit):                          6.2 %  248.4 MiB
        Max size (high water):                           16:1    3.9 GiB
        Most Frequently Used (MFU) cache size:          0.3 %   13.4 MiB
        Most Recently Used (MRU) cache size:           99.7 %    3.8 GiB
`
I guess the MRU can grow because the target size `arc_p` is already at 100% given the mentioned lack of adjustment when promoting from MRU to MFU? Given the absence of ghost hits even at the start when the MRU was only ~130MB means that if the arc_p had been reduced, the uncached streaming read would not have caused it to grow back.
