### ISSUE TITLE
building zfs-2.0.7-1 from source fails on `make install`

### ISSUE THREAD

**Issue by ianvernon** [openzfs/zfs#14122]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Amazon Linux
Distribution Version	| 2
Kernel Version	| 5.10.144-127.601.amzn2.aarch64
Architecture	| aarch64
OpenZFS Version	|  zfs-2.0.7-1 

### Describe the problem you're observing

Running `make install` after running `make` gives me an error that I do not know how to recover from:

```
$ make install
Making install in include
make[1]: Entering directory `/usr/local/src/zfs-2.0.7/include'
Making install in sys
make[2]: Entering directory `/usr/local/src/zfs-2.0.7/include/sys'
Making install in fm
make[3]: Entering directory `/usr/local/src/zfs-2.0.7/include/sys/fm'
Making install in fs
make[4]: Entering directory `/usr/local/src/zfs-2.0.7/include/sys/fm/fs'
make[5]: Entering directory `/usr/local/src/zfs-2.0.7/include/sys/fm/fs'
make[5]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/usr/local/src/zfs-2.0.7/include/sys/fm/fs'
 /bin/install -c -m 644 zfs.h '/usr/local/src/zfs-2.0.7/include/sys/fm/fs'
/bin/install: ‘zfs.h’ and ‘/usr/local/src/zfs-2.0.7/include/sys/fm/fs/zfs.h’ are the same file
make[5]: *** [install-kernelHEADERS] Error 1
make[5]: Leaving directory `/usr/local/src/zfs-2.0.7/include/sys/fm/fs'
make[4]: *** [install-am] Error 2
make[4]: Leaving directory `/usr/local/src/zfs-2.0.7/include/sys/fm/fs'
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory `/usr/local/src/zfs-2.0.7/include/sys/fm'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/usr/local/src/zfs-2.0.7/include/sys'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/usr/local/src/zfs-2.0.7/include'
make: *** [install-recursive] Error 1
```

### Describe how to reproduce the problem

* Download ZFS 2.0.7-1 source
* Expand tar to `/usr/local/src`: `tar --no-same-permissions -xzvf zfs-2.0.7.tar.gz -C /usr/local/src`
* Run `./configure`
* Run `make`
* Run `make install`, and get the above error.

I am doing this on a `c6g.xlarge` instance on AWS FWIW. I am unable to build and install the RPMs for ZFS as well due to `python-packaging` not being available as an RPM, which led me to install from source.

**Comment by rincebrain** [comment]
The problem here appears to be that you unpacked it in /usr/local/src, and that is where make install is attempting to install some files to. So you could unpack it somewhere else, or tell `./configure` to use a different prefix.

Having `python-distlib` installed if `python-packaging` isn't available should work, I think, since the latter was added because the former prints big deprecation warnings and is gone in even newer versions - if the RPM won't accept that, then go futz with the BuildRequires to drop that, since that is intended to only be enforced on platforms where that package exists. (I don't have the time at this moment to go spin up an Amazon Linux VM and see what breaks, but that would be my two thoughts.)

**Comment by ianvernon** [comment]
Thanks for the help @rincebrain , will try this! Appreciate the assistance.
