### ISSUE TITLE
zfs list and destroy -vn totally wrong about snapshot space consumption

### ISSUE THREAD

**Issue by AllKind** [openzfs/zfs#15313]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Mint (Ubuntu 22.04 based)
Distribution Version	|21.2
Kernel Version	|5.15.133 (custom vanilla)
Architecture	|amd64
OpenZFS Version	|2.1.12 (built from source)

### Describe the problem you're observing
The used space output for `zfs list` as well as the reclaimed space calculation of `zfs destroy -v -n` is completely wrong.
The `USEDSNAP` field of `zfs list` correctly shows the total sum of space consumed by snapshots (immediately).

As far as memory serves me, the `zfs list` output was never reliable. What also made me wonder, that it often took a long time (hours / days - I never measured it) after deleting stuff, for it to catch up with it. Is that to be expected?
But now it is just way off.
I think (but not sure about that either) it's the case since I did a `zpool upgrade` from 0.8 features to 2.1.12.

### Describe how to reproduce the problem
```
sudo zfs list -o space | grep video
NAME                                                AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD
storage/video                                       46.2T  62.5T      204G   62.3T             0B         0B
storage/video@autosnap_2023-09-22_23:15:07_monthly      -     0B         -       -              -          -
storage/video@autosnap_2023-09-22_23:15:07_weekly       -     0B         -       -              -          -
storage/video@autosnap_2023-09-22_23:15:07_daily        -     0B         -       -              -          -
storage/video@autosnap_2023-09-23_00:00:01_daily        -     0B         -       -              -          -
storage/video@autosnap_2023-09-24_00:00:02_daily        -  3.39M         -       -              -          -
storage/video@autosnap_2023-09-25_00:00:02_daily        -  5.57M         -       -              -          -
```

```
for x in $(sudo zfs list -t snapshot |grep "video@autosnap"|awk '{ print $1 }'); do sudo zfs destroy -v -n "$x"; done
would destroy storage/video@autosnap_2023-09-22_23:15:07_monthly
would reclaim 0B
would destroy storage/video@autosnap_2023-09-22_23:15:07_weekly
would reclaim 0B
would destroy storage/video@autosnap_2023-09-22_23:15:07_daily
would reclaim 0B
would destroy storage/video@autosnap_2023-09-23_00:00:01_daily
would reclaim 0B
would destroy storage/video@autosnap_2023-09-24_00:00:02_daily
would reclaim 3.39M
would destroy storage/video@autosnap_2023-09-25_00:00:02_daily
would reclaim 5.87M
```
```

for x in $(sudo zfs list -t snapshot |grep "video@autosnap"|awk '{ print $1 }'); do sudo zfs destroy -v "$x"; done
will destroy storage/video@autosnap_2023-09-22_23:15:07_monthly
will reclaim 0B
will destroy storage/video@autosnap_2023-09-22_23:15:07_weekly
will reclaim 0B
will destroy storage/video@autosnap_2023-09-22_23:15:07_daily
will reclaim 0B
will destroy storage/video@autosnap_2023-09-23_00:00:01_daily
will reclaim 85.4G
will destroy storage/video@autosnap_2023-09-24_00:00:02_daily
will reclaim 108G
will destroy storage/video@autosnap_2023-09-25_00:00:02_daily
will reclaim 10.5G
```
EDIT: The first two commands tell me, that my snapshots use about 9MB of space, which is absolutely inaccurate.

The last command actually frees 204GB of space.

### Include any warning/errors/backtraces from the system logs

none

The pool is composed of two raidz-2 vdevs.
If any more information is needed, I'm happy to provide it.

Thank you in general and this particular case!

**Comment by rincebrain** [comment]
`USED` on a snapshot has always meant "how much would be freed if you deleted this snapshot and only this snapshot right now", which means destroying a snapshot will impact USED of every other snapshot of the dataset, potentially.

Destroying snapshots, if you have the `feature@async_destroy` feature enabled, will throw all the space on a queue to be freed over time between other more important operations, because it used to block the `zfs destroy` command until it freed everything, and that's not ideal. You could get some of that behavior back with `zfs destroy -d` if you really wanted to, and you can look at the `freeing` property  on the entire pool to watch as it add things as you mark snapshots for destruction and it slowly or rapidly walks the list and frees it. If you were doing those `zfs destroy` commands in the example and `freeing` was 0 the entire time, that'd be one thing, but I would be very surprised.

This doesn't seem like a bug, at least with the information you've reported. I'm not saying there can't be bugs, just that this seems far more likely to be a mismatch of expectations for how this works than a bug, with what's been reported so far.

**Comment by AllKind** [comment]
Thank you for answering rincebrain.

> USED on a snapshot has always meant "how much would be freed if you deleted this snapshot and only this snapshot right now", which means destroying a snapshot will impact USED of every other snapshot of the dataset, potentially.

I'm aware of that, though AFAIK the man page isn't very clear about the math behind it. Just saying the sum of `USED` does not need to match `USEDSNAP`, because snapshots can share blocks.

I think there is a bit of a misunderstanding.
I'm not saying destroying the snapshots does not free the space. It does that and quite fast.
I'm saying:
If I delete some data, the `USED` field in `zfs list` and the dry run operation of `zfs destroy` is not updated accordingly.

In my above example, I had destroyed 204GB of data. But within 4 days, `zfs list` and `zfs destroy -v -n` did not reflect that.
Rendering both useless for that matter.
The `USEDSNAP` field on the other hand is updated correctly immediately.

**Comment by rincebrain** [comment]
Both of your commands are correct in a vacuum.

`zfs destroy -vn` is telling you how much it'll free if you freed _just_ the snapshots specified in that moment.

`zfs destroy -v` run repeatedly will have different output, because you have since deleted the previous snapshots, so the state has changed, and the amount freed will differ.

`zfs destroy -vn storage/video@autosnap_2023-09-22_23:15:07_monthly%autosnap_2023-09-25_00:00:02_daily`, for example, would have said 204G.

**Comment by AllKind** [comment]
@rincebrain 
Thank you very much for explaining.
I see the error in my thinking now. Sorry for the noise.
Also I must admit, that I wasn't aware of the zfs destroy percent sign option.

But still made me think, if it would be useful to kind of re-use the `USEDSNAP` field for snapshots in a way that says:
This snapshot would take up that space, if it were the only one. Or in other words, relative to the current state of the dataset. Kind of the opposite of the `USED` field.
I would find that useful.
What would you think about that?

I will close this issue soon, as the above would be a feature request.
