### ISSUE TITLE
Write and checksum errors on Raspberry Pi 4

### ISSUE THREAD

**Issue by mrdomino** [openzfs/zfs#15779]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| Bookworm
Kernel Version	| 6.1.69 (Debian 6.1.0-17-arm64)
Architecture	| arm64
OpenZFS Version	| 2.2.2

### Describe the problem you're observing

With a ZFS pool on a 1TB M.2 SSD (attached via the [Argon One M.2 case](https://argon40.com/products/argon-one-m-2-case-for-raspberry-pi-4)), after writing about 400–500GB of data, I start getting write errors, and after a reboot, scrub shows checksum errors. The issue is also reported elsewhere: https://forums.raspberrypi.com/viewtopic.php?t=326523.

Note that I'm using the official [Debian raspi](https://raspi.debian.net/) image, not Raspbian / Raspberry Pi OS. My Raspberry Pi is the same model as the forum post, 4 Model B Rev 1.4.

The same drive seems fine when formatted as ext4 or btrfs.

**Comment by rincebrain** [comment]
"I got checksum errors with this case on Linux and they go away when I use USB2 or FreeBSD" doesn't really sound like a ZFS bug,

I'm personally using a Pi 4 with USB3 and 8G of RAM successfully without hitting any such issue, though on 5.15.x atm.

I'd need to see more information about the errors you're getting, but "limit memory to under 4 GiB" would be rather unfortunate as a solution on this platform, since ZFS doesn't really control where the memory it gets is mapped from, so unless the kernel exposes a way to request only memory below that, I don't really know of a good way we could work around it.

**Comment by rincebrain** [comment]
I mean, I've been using ZFS on my Pi 4 with 8G of RAM for years, on the model mentioned in the forum post, so...I don't really think there's a "known issue with ZFS" so much as "a buggy enclosure".

**Comment by mrdomino** [comment]
Are we sure it's the enclosure? I don't see that the other report was using that case, though I'm pretty ignorant of raspi stuff so far...

btrfs has been working fine on that same drive/enclosure, so there seems to be some way in which ZFS is uniquely tripping over something.

**Comment by rincebrain** [comment]
You said you were having that issue, so I was assuming it was the same issue.
If it's not the same issue, then you should probably not say that.

Historically, ZFS is, one might say, far more aggressive at actually sending all the IO that a disk claims it can handle, and this can lead to fun consequences when disks, or enclosures, or ..., don't actually handle what they claim to.

So no, I'm not sure it's not a ZFS problem, but you have no information about it, and have said you have no interest in helping to investigate it, so I don't think this is going to go anywhere.

**Comment by mrdomino** [comment]
No, I don't know that it's the same issue; it just looked similar at first glance.

Fair enough then. If I get a spare Pi or anything changes I'll reopen.
