### ISSUE TITLE
sync=<size> for handling bursts of writing

### ISSUE THREAD

**Issue by Haravikk** [openzfs/zfs#15799]
### Describe the feature would like to see added to OpenZFS

I would like to see the `sync` property expanded to allow for a size specification, such as `sync=50M`, allowing us to specify that a pool should change from `sync=standard` to `sync=always` and back when writes to the dataset(s) exceed a certain amount of write activity.

The size specification would define an amount of data written during a certain period, either configurable with another setting, or some default such as one second, one minute or such. When ZFS sees an amount of data written to a dataset (and any descendant inheriting this property) that exceeds this amount, the dataset will temporarily act as if it were set to `sync=always`, until the bandwidth used drops below the specified amount again.

Alternatively, it might sense for the size to specify an amount of queued writes – this would mean the feature might not kick in until after performance has begun to degrade, but it may be more feasible?

### How will this feature improve OpenZFS?

Currently the only way to force writing to a high-speed SLOG is to set to `sync=always`, but this isn't always desirable.

By limiting when the `sync=always` behaviour applies to only periods with large amounts of writing, it would remain possible for ZFS to perform asynchronous writes the rest of the time.

### Additional context

This idea occurred to me while working with a large pool consisting of mostly high capacity SMR drives; as much as these are maligned, they're fine for things like periodic backups which is what this pool was primarily for.

However, while the performance of SMR drives can be okay most of the time, when too much data is written at once the performance often takes a nose dive, causing operations to slow considerably (which can then have knock on effects).

To mitigate this I installed a high speed SLOG device with the same level of redundancy, and enabled `sync=always` on the root dataset to force as much writing as possible into the SLOG, providing a much larger buffer before performance will drop. With nice big drives this should avoid the performance cliff edge the pool was otherwise seeing.

While this is fine, it seems to me like the switch to `sync=always` is only actually required when the amount of data being written is large enough that there's a danger of overwhelming the drives, which isn't always the case. Since the size of backups being sent can vary, not all of them will cause this problem, so the ability to control when `sync=always` is enabled would be useful.

I could probably rig something like this up via script by using `zpool iostat` to detect when bandwidth use might be too high, and change the setting accordingly, but I feel like it would make a lot of sense to have ZFS be able to manage this itself.

**Comment by gmelikov** [comment]
> Currently the only way to force writing to a high-speed SLOG is to set to sync=always, but this isn't always desirable.

why do you ever need `sync=always`? You should have better performance with `sync=standard` and dedicated SLOG, because `sync=always` won't give you any difference on how your dirty writes will be written on SMR vdevs.

> This idea occurred to me while working with a large pool consisting of mostly high capacity SMR drives; as much as these are maligned, they're fine for things like periodic backups which is what this pool was primarily for.

For backups you may even use `sync=disabled` and call it a day.

SLOG is not a cache, it's a journal to give some guarantees for synchronous writes. Data will be cached in RAM as "dirty write" for both sync and async writes. `sync=always` have nearly one usecase - to force-make async writes synchronous (and it's really questionable).

So, or you're really want to speed up synchronous writes and add fast SLOG, or you don't need it and maybe just think about using `sync=disabled`. 

But I don't see a profit from this feature request at all (because I don't understand a use case), maybe I'm wrong and feel free to describe it with consideration to info of my comment earlier.

Offtopic - you may want to look at `zfs_txg_timeout` to bump period when dirty writes may be aggregated in RAM. Or maybe even use special VDEVS on your nvmes, it should give a great performance bump for SMR vdevs.
