### ISSUE TITLE
Replace XDR code with BSD-relicensed copy

### ISSUE THREAD

**Issue by bgermann** [openzfs/zfs#16047]
### Describe the problem you're observing
OpenZFS includes include/os/freebsd/spl/rpc/xdr.h under the non-free Sun RPC license.
That code was relicensed upstream (see FreeBSD or glibc copy) to a BSD license by Oracle.

Please replace the OpenZFS copy with a BSD-licensed one.

**Comment by rincebrain** [comment]
FreeBSD's copy has the same license both [here](https://github.com/freebsd/freebsd-src/blob/main/sys/xdr/xdr_mem.c) and [here](https://github.com/freebsd/freebsd-src/blob/main/sys/cddl/compat/opensolaris/rpc/xdr.h) still.

You may be thinking of [here](https://github.com/freebsd/freebsd-src/blob/main/include/rpc/xdr.h), which doesn't include the function from that header here, which is present in the first file I linked in FreeBSD, and is still under the same license there. 

illumos, fascinatingly, has it marked [under CDDL](https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/rpc/xdr_mem.c) since the launch of OpenSolaris, at least, so one could conceivably copy that.
