### ISSUE TITLE
Fedora 40 repo

### ISSUE THREAD

**Issue by rabin-io** [openzfs/zfs#16102]
Can we have a Fedora 40 repo ready of the upcoming Fedora release - 40? 

* Fedora 40, come with Kernel 6.8 (6.8.5-301.fc40.x86_64)

https://fedorapeople.org/groups/schedule/f-40/f-40-key-tasks.html

**Comment by tonyhutter** [comment]
Thanks, Fedora 40 is on our radar.  Looks like its release date is 2024-04-23.  Typically it takes some time after they release to put out the AMI's for us to begin testing.  Once it passes the test suite then we can buiid RPMs for it.  So I wouldn't expect zfs RPMs to be available the day it comes out.  We may also need to wait for the upcoming zfs-2.2.4 release (https://github.com/openzfs/zfs/pull/16107) since Fedora 40 runs a 6.8 kernel.

**Comment by rabin-io** [comment]
I see, thank you for the explanation.

I'm just wondering if the tests can be done with Fedora rawhide, as testing ground for each next Fedora release.

**Comment by tonyhutter** [comment]
> I'm just wondering if the tests can be done with Fedora rawhide, as testing ground for each next Fedora release.

It's not really useful since rawhide is a moving target.

**Comment by Lalufu** [comment]
There is a AMI for the current RC:
https://fedoraproject.org/wiki/Test_Results:Fedora_40_RC_1.14_Cloud#x86_64_hvm_gp3_AMIs

**Comment by tonyhutter** [comment]
Besides the kernel fixes, we will also need https://github.com/openzfs/zfs/pull/16125 to build on F40

**Comment by RomanRcT** [comment]
I would like to know, when Fedora 40 will be supported?

**Comment by tonyhutter** [comment]
2.2.4 has been released with Fedora 40 support: https://github.com/openzfs/zfs/releases/tag/zfs-2.2.4
```
dnf install -y https://zfsonlinux.org/fedora/zfs-release-2-5$(rpm --eval "%{dist}").noarch.rpm
```
