### ISSUE TITLE
Feature Request: parameter to Destory pool or dataset completely, no recovery.

### ISSUE THREAD

**Issue by davidngrc** [openzfs/zfs#16260]
I found some article online suggesting if you destroy a dataset or pool.
somehow you can recover it.

and in below article, someone suggest this wipe.
1 after destroy the dataset or pool.
2 take one of the drive out to another system.
3 and wipe it by write 0 to all disk sector.
4 put it back to the original system, wait for Resilvering to complete.
5 then take the next drive out to other system.
6 repeat step 3 o 5 until all drive are clean.
7 this way, the dataset data supposed to be gone.
https://www.truenas.com/community/threads/how-to-properly-destroy-a-dataset-so-it-cant-be-recovered.97406/

this is a good idea.
is it possible add a zfs destory new parameter, if set, 
zfs will wipe the dataset by putting the 0 to the existing dataset disk sector,
or to speed it up, putting the 0 only on the odd ( I meant the next next )  disk sector.
then run the normal destroy.

Thank you.

**Comment by amotin** [comment]
Since ZFS is copy-on-write file system, there may be indefinite number of previous dataset versions scattered throughout the pool empty space.  Wiping the last copy location would not be reliable.  You'd need to wipe all the disk free space, and hope that disk (SSD primarily) has no data in some reserved sectors, invisible to software, but potentially accessible through forensics methods.  More reliable than disk overwrite would be its cryptographic erase, if supported, but it would require pretty long and painful process you've described above.  I'd probably add there another disk and instead of removing drives one by one, replaced them with new/previous pre-erased one.  It would be safer, but would still take forever to complete.  If you need to regularly reliably delete some datasets, ZFS encryption may be preferable -- there is no more reliable way to delete the data than encrypt them and loose the key.
