### ISSUE TITLE
Linux 6.10 compatibility and new promptly release

### ISSUE THREAD

**Issue by wiesl** [openzfs/zfs#16425]
As support for Linux 6.10 has not formally been added in zfs 2.2.5 (I understand it for stability reasons): Is it possible to release a new zfs version in a promptly manner?

BTW: Is there any OpenZFS discussion platform like a mailinglist, forum, etc. (except github issues/discussions) available?

Thnx.

**Comment by wiesl** [comment]
Looks good so far with Fedora 40 and Kernel 6.10.3-200.fc40.x86_64.

**Comment by snajpa** [comment]
@scineram could you please stop with the thumbs down on pretty much all new issues?

**Comment by n0xena** [comment]
2.2.5 works on arch with 6.10.3 standard
https://github.com/archzfs/archzfs/pull/542

**Comment by Yamakuzure** [comment]
> As support for Linux 6.10 has not formally been added in zfs 2.2.5 (I understand it for stability reasons): Is it possible to release a new zfs version in a promptly manner?

The newly supported kernel 6.9 is EOL already, so I do hope for it, too.

**Comment by Gibson85** [comment]
Yeah, I am stuck on 6.8 kernel since months. And sure it is vacation time. But in the meanwhile you was 2 kernel versions behind. And now they are so late to release zfs 2.2.5 that there is not even a 6.9 kernel available anymore on fedora. I also do not see why it is not possible to release versions with kernel fixes only. They argued that they would not have enough people power for that. But this is bullshit. It's only to change processes. And doing so in the end could be even more efficient and safe time. So I bet if 2.2.6 comes out we are running Fedora 41 already with kernel 6.11 or so. It's like it is. It's ZFS. I hope this 6.8.11 kernel has no security issues not beeing fixerd anymore.

**Comment by lnicola** [comment]
@Gibson85 I'm running 2.2.5 on 6.10.4. But ZFS is built for more "enterprise" applications, so you'll be much safer on older kernels.

**Comment by tonyhutter** [comment]
The 6.10 kernel will be fully supported in zfs-2.2.6: https://github.com/openzfs/zfs/pull/16472.  

You could technically build zfs-2.2.5 against 6.10, but there were additional 6.10 bugs found after its release: f2f4ada24 fb432660c.

**Comment by robn** [comment]
OpenZFS does not track Linux release schedules, and does not claim to. We issue stable releases when we think they're ready and are something we can support, not when Linux decides.

If your expectation is that OpenZFS will track Linux release schedules, then you have a choice before you: change your expectation, be disappointed, or, contribute your time or sponsor a person or company to make that happen faster.

Or you could just thank @tonyhutter coz he does a top job as release guy :clap:

**Comment by wmmur** [comment]
sorry my contribution to the project is to annoy @robn and accidentally help @tonyhutter. Sorry. zfs-2.2.5 had the bugs mentioned by @tonyhutter. I believe that even though I have been using the linux-6.11.0 rc3 and rc4 kernel on zfs-master for several days, zfs-2.2.6 should have formal support for linux-6.10.x, I hope that zfs-2.2.6 will be compatible with linux-
rt (zfs-master is compatible with linux-rt).

**Comment by Gibson85** [comment]
I also want a stable version and not to risk my data. So I prefer to wait for a working and tested version. And I did not criticise a single person here for it's work. You shouldn't be offended so quickly :). But you said it. It is a bit disappointing. I see you have limited resources. But I wonder a bit why. One would think that ZFS should play an important role on enterprise environments where good money is paid. If you have a company to pay me for contributing to ZFS let me know ;).

**Comment by Venomtek** [comment]
> I also want a stable version and not to risk my data. So I prefer to wait for a working and tested version. And I did not criticise a single person here for it's work. You shouldn't be offended so quickly :). But you said it. It is a bit disappointing. I see you have limited resources. But I wonder a bit why. One would think that ZFS should play an important role on enterprise environments where good money is paid. If you have a company to pay me for contributing to ZFS let me know ;).

Maybe go speak to Canonical, since they are going to start shipping with the latest upstream kernels, and they have an option to install on zfs root, maybe they will be up to the task.

_"Canonical has announced a major shift in its kernel selection process. Starting with Ubuntu 24.10, all future releases will include the latest upstream Linux kernel, even if it's still in Release Candidate (RC) status at the time of the release"_

On the other hand, they will probably just fork it and make it exclusive to Ubuntu.

**Comment by tonyhutter** [comment]
zfs-2.2.6 is out and supports the 6.10 kernel: https://github.com/openzfs/zfs/releases/tag/zfs-2.2.6

**Comment by wiesl** [comment]
Tony, thank you for the release. BTW: Why are the staging branches, e.g. zfs-2.2.6-staging not used?

**Comment by tonyhutter** [comment]
@wiesl they are used.  When creating a release, we use the staging branch as a base and add on any additional commits we need.  You'll notice all the zfs-2.2.6-staging commits are in zfs-2.2.6.

**Comment by wiesl** [comment]
Yes, I see them at the release tag: https://github.com/openzfs/zfs/commits/zfs-2.2.6/
But at the staging branch https://github.com/openzfs/zfs/commits/zfs-2.2.6-staging/ I don't see them (also on previous staging branches they are not seen).

**Comment by tonyhutter** [comment]
@wiesl ah now I see what you meant - it turned out there were no commits in zfs-2.2.6-staging.  Normally there are commits in the staging branch, but in this case there was not, which is unusual.
