### ISSUE TITLE
Missing good documentation for TRIM on L2ARC cache devices

### ISSUE THREAD

**Issue by mabod** [openzfs/zfs#16644]
I just added an SSD as cache device to my main pool (4 HDD RAID10). But I did not find any good documentation about how the trim operation is performaned on SSD cache devices.

I read about persistent and non-persistent L2ARC. I read about parameters like l2arc_trim_ahead and l2arc_write_max and I also read PR https://github.com/openzfs/zfs/pull/9789  

But I still have no clue if and how trim is performed on my new cache SSD. I still do not understand what I need to configure. etc. etc. Should I go for a persistent l2arc? Why? How?

From my point view the easiest setup would be if a trim is performant on every import of a pool.

**Comment by amotin** [comment]
Persistent L2ARC is enabled by default, unless you disable it via module parameter. But AFAIK it should have nothing to do with TRIM.  Generally TRIM for L2ARC is a questionable concept, since L2ARC is written sequentially, and so in some opinions should not cause excessive flash fragmentation.  But if you wish, according to zpoolprops(7): "TRIM on L2ARC devices is enabled by setting l2arc_trim_ahead > 0" and "autotrim=on".

**Comment by mabod** [comment]
Thank you, but where can I read about this?  Especially  about autotrim=on in conjunction with cache devices.

**Comment by amotin** [comment]
Is section for autotrim in `man 7 zpoolprops` not enough? Please propose the extension.

**Comment by mabod** [comment]
To me it is not clear that the autotrim property includes log and cache devices. If that is the case a "zpool trim" command would also do the trick. But I have 4 HDD in the pool plus the SSD for cache. And when I initiate a zpool trim for that pool, I get the error that trim is not supported. Why would autotrim for that pool than work?

**Comment by amotin** [comment]
Both `zpool trim` (manual TRIM) and autotrim work for special and log vdevs, since they are pretty much a normal vdevs from space allocation point of view.  L2ARC vdevs are different, they require explicit TRIM support.  As I commented in other ticket, autotrim is supported there is you enable it via the module parameter.  `zpool trim` I guess may be not implemented, but it may not have much sense in many cases when persistent L2ARC is full of data.

**Comment by mabod** [comment]
Thank you for your explanations. Very helpful for me. I will close this issue now.
