### ISSUE TITLE
NFS/POSIX ACL support

### ISSUE THREAD

**Issue by user318** [openzfs/zfs#170]
It will be good to have POSIX ACL support.
As I see zfs already have xattr support and some other filesystems made ACL support over xattr. I'm do not know the internals, but this task may be simple to implement.

**Comment by ghfields** [comment]
@behlendorf: 

> The issue lies with the Linux utilities (getfattr, setfattr, etc) which are built around POSIX rather than NFS ACLs. There have been attempts in the past to bring NFS ACLs to Linux but to my knowledge none of have been widely successful. Unless things have changed recently that's the biggest obstacle.

I see distros are using the "nfs4-acl-tools" package for NFS4 acl management.  It uses nfs4_getfacl, nfs4_setfacl, and nfs4_editfacl.  When I run these against zfs, I currently get "Operation to request attribute not supported."  This seems to me the way linux is going to do NFS4.  Now we just need a way for the tools and zfs to be aware of each other.

**Comment by behlendorf** [comment]
@ghfields thanks for commenting, I haven't looked in to nfs4 acls for a few years but it looks like they're making really good progress with the user space components.  Based on a cursory reading of the nfs4-acl-tools source it looks like the expected user/kernel interface is via an xattr named `system.nfs4_acl` which contains the raw xdr encoded acl.

Getting this working might only require adding xattr handlers for a `system.nfs4_acl` xattr which translates between the nfs4 acl stored internally by ZFS and the representation of it expected by the utilities.  Since NFSv4 is the only consumer of this the kernel doesn't provide any generic functionality we can use we'd need to write the functions to do this encoding/decoding.

On the surface getting this working looks very possible.  I think it would be great if a developer wanted to tackle this feature.

**Comment by ghfields** [comment]
Since this issue was closed when the POSIX acls was implemented, should a new issue be created specifically for NFS4 acls?  Or should this one be reopened?

**Comment by behlendorf** [comment]
@ghfields can you open a new issue for this.  That'll make it easier to track.
