### ISSUE TITLE
FreeBSD IO Mirror Improvements

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#1803]
Additionally improvements have been made to the #1461, commit 556011dbec2d10579819078559a77630fc559112, by @stevenh for FreeBSD.  We need to evaluate what impact these changes have under Linux, they can be found here:

http://svnweb.freebsd.org/changeset/base/256956

**Comment by kpande** [comment]
@behlendorf why was it that Linux doesn't work out with this approach? do the locality system calls introduce more latency? Didn't see any numbers on this specific patch. It pushes FreeBSD from 100MB to 300MB/s using simple HDD mirrors.

**Comment by behlendorf** [comment]
The data just didn't show a clear win.  I suspect because the Linux IO elevator already can reorder requests we may have already gotten some/most of those gains.  That said, if people want to test the above patches any analyse the results I'm all for it.  Perhaps there are workloads which we didn't test which could take advantage of this.

**Comment by kpande** [comment]
I'd be willing to test this out. I've got asymmetric performance on some mirror systems and FreeBSD does really well with that.

**Comment by nergdron** [comment]
Note that I'm currently trying to pull data off a mirror with a drive that's dying (await of 800, vs await of ~2 on the healthy drive), and I'm definitely wishing this change had been merged in, since it seems to be preferring IO from the slow drive and not the fast one. So I think there's still a use case for this in failure scenarios, at least if it works as described in the FreeBSD notes.

**Comment by behlendorf** [comment]
@nergdron the rest of the bsd functionality was merged to master and will appear in the 0.7.0 release.
