### ISSUE TITLE
SPA history corruption and pool suspend

### ISSUE THREAD

**Issue by tuxoko** [openzfs/zfs#3049]
Hi all,

We had a pool with a corrupted SPA history along with some other plain files, as shown by zdb.
The corruption is likely not caused by ZFS itself.
However, the problem is that while `zpool status` shows the pool is online,

```
  pool: p1
 state: ONLINE
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-HC
  scan: none requested
config:

    NAME                        STATE     READ WRITE CKSUM
    p1                          ONLINE       0     0     1
      raidz2-0                  ONLINE       0     0     6
        scsi-35000cca0003d1e5c  ONLINE       0     0     0
        scsi-35000c5000ab7be47  ONLINE       0     0     0
        scsi-3500000e01ad2a8d0  ONLINE       0     0     0
        scsi-3500000e01dd91480  ONLINE       0     0     0
        scsi-35000c5001250f153  ONLINE       0     0     0
        scsi-35000c5000b12e817  ONLINE       0     0     0

errors: 1 data errors, use '-v' for a list
```

The pool is actually suspended due to "uncorrectable I/O failure", and every access to it will hang.

Now what I want to ask is:
Is this kind of pool suspend intended? SPA history doesn't seem critical enough.
If it is intended, shouldn't the pool state be like FAULTED since it can't be accessed?

Thanks

**Comment by behlendorf** [comment]
> Is this kind of pool suspend intended? SPA history doesn't seem critical enough.

Unfortunately, this logic really doesn't take in to account how important a given block is.  If all attempts to access a block which is needed fail then the pool can be suspended.  There are a few exceptions for things like prefetch but in general this is how it works.  So I think it's reasonable that the pool was suspended.

If it is intended, shouldn't the pool state be like FAULTED since it can't be accessed?

> If it is intended, shouldn't the pool state be like FAULTED since it can't be accessed?

Yes, yes I think it should.  That said, it looks like the code here is working as originally intended so clearly there is some room for interpretation.  As for what state it's in I think SUSPENDED might be more appropriate since it's explicitly waiting for a `zpool clear` to be run to unsuspend the pool.  But that isn't an existing state.
