### ISSUE TITLE
Space re-balancing with large file blocks

### ISSUE THREAD

**Issue by don-brady** [openzfs/zfs#3540]
Commit f1512ee6 (illumos issue 5027) introduced support for larger blocks in ZFS (> 128K).
 
VDEV Space Re-balancing
 
The traditional VDEV space re-balancing occurred by means of a bias based on a 512K `metaslab_aliquot` and the number of VDEV children.  This bias mechanism will not function correctly with large allocation sizes. An alternate method may need to be devised to allow effective re-balancing when streams of large allocations occur.

Intel is currently working on a alternate re-balancing solution for large blocks.

**Comment by behlendorf** [comment]
This recently came up in the context of #3389.  The only significant concern was this this could potentially lead to a slight imbalance in the free space.  Although the expectation was that in practice this imbalance would be corrected for over time due to the bias.

One possible solution to this would be to scale the `metaslab_aliquot` size based on the dataset's maximum recordsize.  Setting it as `4 * recordsize` would produce similar behavior but it might not be convenient to access the dataset size while allocating.  Better ideas welcome!
