### ISSUE TITLE
zfs kernel module debuginfo RPMs for different kernel releases have the same name

### ISSUE THREAD

**Issue by bprotopopov** [openzfs/zfs#3971]
When ZFS RPMs for different kernel revisions are placed in the same repo (which is common practice for RH derivatives, e.g. Centos), the kernel module debuginfo RPMs clobber each other because they all have the same filename. Yet the contents of those RPMs seems different, as the ZFS kernel module code has many variations, depending on the kernel release. One way to avoid this is to include kernel release in the RPM names.

**Comment by bprotopopov** [comment]
Here is a patch that addresses the issue:

From 2e472827de73ecff53a5cbecdb91dc24aa8e0a8e Mon Sep 17 00:00:00 2001
From: George Stockfisch <georgestockfisch@gstockfisch.local>
Date: Mon, 19 Oct 2015 11:40:16 -0400
Subject: [PATCH] bug-23336 add kernel revision to the name of the zfs-kmod debuginfo package

---
 config/rpm.am                |    4 ++++
 rpm/generic/zfs-kmod.spec.in |    6 +++---
 2 files changed, 7 insertions(+), 3 deletions(-)

diff --git a/config/rpm.am b/config/rpm.am
index 311c754..44a85ad 100644
--- a/config/rpm.am
+++ b/config/rpm.am
@@ -66,6 +66,8 @@ srpm-common: dist
 	LANG=C $(RPMBUILD) \
 		--define "_tmppath $$rpmbuild/TMP" \
 		--define "_topdir $$rpmbuild" \
+		--define "pkgname $(pkg)" \
+		--define "kmodname $(pkg)" \
 		$(def) -bs $$rpmbuild/SPECS/$$rpmspec || exit 1; \
 	cp $$rpmbuild/SRPMS/$$rpmpkg . || exit 1; \
 	rm -R $$rpmbuild)
@@ -82,6 +84,8 @@ rpm-common:
 	LANG=C ${RPMBUILD} \
 		--define "_tmppath $$rpmbuild/TMP" \
 		--define "_topdir $$rpmbuild" \
+		--define "pkgname $(pkg)-@LINUX_VERSION@" \
+		--define "kmodname $(pkg)" \
 		$(def) --rebuild $$rpmpkg || exit 1; \
 	cp $$rpmbuild/RPMS/*/* . || exit 1; \
 	rm -R $$rpmbuild)
diff --git a/rpm/generic/zfs-kmod.spec.in b/rpm/generic/zfs-kmod.spec.in
index 7871df3..9f806bd 100644
--- a/rpm/generic/zfs-kmod.spec.in
+++ b/rpm/generic/zfs-kmod.spec.in
@@ -40,7 +40,7 @@
 %bcond_with     debug_dmu_tx
 
 
-Name:           %{module}-kmod
+Name:           %{pkgname}
 
 Version:        @VERSION@
 Release:        @RELEASE@%{?dist}
@@ -93,7 +93,7 @@ BuildRequires:             kmod-spl-devel = %{version}
 # Kmodtool does its magic here.  A patched version of kmodtool is shipped
 # with the source rpm until kmod development packages are supported upstream.
 # https://bugzilla.rpmfusion.org/show_bug.cgi?id=2714
-%{expand:%(bash %{SOURCE10} --target %{_target_cpu} %{?repo:--repo %{?repo}} --kmodname %{name} %{?buildforkernels:--%{buildforkernels}} --devel %{?prefix:--prefix "%{?prefix}"} %{?kernels:--for-kernels "%{?kernels}"} %{?kernelbuildroot:--buildroot "%{?kernelbuildroot}"} 2>/dev/null) }
+%{expand:%(bash %{SOURCE10} --target %{_target_cpu} %{?repo:--repo %{?repo}} --kmodname %{kmodname} %{?buildforkernels:--%{buildforkernels}} --devel %{?prefix:--prefix "%{?prefix}"} %{?kernels:--for-kernels "%{?kernels}"} %{?kernelbuildroot:--buildroot "%{?kernelbuildroot}"} 2>/dev/null) }
 
 
 %description
@@ -104,7 +104,7 @@ This package contains the ZFS kernel modules.
 %{?kmodtool_check}
 
 # Print kmodtool output for debugging purposes:
-bash %{SOURCE10}  --target %{_target_cpu} %{?repo:--repo %{?repo}} --kmodname %{name} %{?buildforkernels:--%{buildforkernels}} --devel %{?prefix:--prefix "%{?prefix}"} %{?kernels:--for-kernels "%{?kernels}"} %{?kernelbuildroot:--buildroot "%{?kernelbuildroot}"} 2>/dev/null
+bash %{SOURCE10}  --target %{_target_cpu} %{?repo:--repo %{?repo}} --kmodname %{kmodname} %{?buildforkernels:--%{buildforkernels}} --devel %{?prefix:--prefix "%{?prefix}"} %{?kernels:--for-kernels "%{?kernels}"} %{?kernelbuildroot:--buildroot "%{?kernelbuildroot}"} 2>/dev/null
 
 %if %{with debug}
     %define debug --enable-debug
-- 
1.7.1

**Comment by bprotopopov** [comment]
I can do a pull request as well, of course.

**Comment by behlendorf** [comment]
For CentOS / RHEL I'd suggest using the `rpm/redhat/*` spec files instead.  Because CentOS / RHEL are an entireprise distribution they provide a stable kABI which means we can rely on weak-modules support.    This allows a single build of ZFS to be used with multiple kernels of the same flavor.

As for the `rpm/generic/*` spec files they should already encode the kernel version in the package name.   If that's not being done for the debuginfo package it should be included.

**Comment by behlendorf** [comment]
@bprotopopov yes I see what you're saying now.  Definitely something we should fix.  However, we're going to need to do it without changing `config/rpm.am`.  This is just a helper for convenience and we can't rely on it to pass critical information in to the package builds.  The correct defaults need to be spec file itself.

**Comment by bprotopopov** [comment]
Hi, @behlendorf 

I am having a bit of a hard time understanding your meaning. 

the config/rpm.am appears to be a template for generating RPM-related targets in the Makefile. The generated makefile uses the zfs-kmod.spec in two different contexts: 
1) to generate SRPMs which do not need the kernel release in the name of the package
2) to generate the kmod-zfs and zfs-kmod-debuginfo RPMs which do need the release in their name

The rpm.am is aware of the context, whereas zfs-kmod.spec is not. The context is communicated to zfs-kmod.spec by way of parameters (--define statements). The suggested changes did not modify this behavior in any way. To my knowledge (looking at spec files/makefiles for other out of tree kernel modules), the context is routinely communicated to the spec file through the parameters.

What the suggested changes do is a fairly straightforward refactoring of this context passing mechanism to pass the needed info a bit more cleanly, but separating the package and the module name in two separate parameters. This is to make sure the release is added to the names of both kmod-zfs and zfs-kmod-debuginfo RPMs. The existing code does not do this properly.

How do you propose this to be done without help from rpm.am (and consequently without help from the Makefile) ?

**Comment by behlendorf** [comment]
That's all true but the thing to keep in mind is all of the `rpm.am` infrastructure was added primarily for convenience.  It provides a way to easily override the defaults which are specified in the spec file.  As you noted it does this by setting defines when building the source rpm and binary rpms.  However, the srpm must always contain reasonable default values so it can be rebuilt without addition defines.

The following command must generate valid binaries for the installed kernel:

```
rpmbuild --rebuild spl-kmod-0.6.5-45_g18d2f56.el7.centos.src.rpm
```

It does this with the help of the `kmodtool` script which dynamically generates the required parts of the spec file.  This potentially includes sections for multiple kernels because given a single source rpm you should be able to build packages for multiple kernels by passing a `kernels` define.

However it seems like that functionality is currently broken because it tries to create identically named `%package -n kmod-spl-devel` sections.  It should only generated one of those and multiple `%package -n kmod-spl-devel-<kernel>` sections.

```
rpmbuild --rebuild spl-kmod-0.6.5-45_g18d2f56.el7.centos.src.rpm --define "kernels 3.10.0-327.10.1.el7.x86_64 3.10.0-327.4.5.el7.x86_64"
Installing spl-kmod-0.6.5-45_g18d2f56.el7.centos.src.rpm
error: Package already exists: %package       -n kmod-spl-devel
```

Similarly what we may need to do to resolve this is to manually add `%package -n kmod-spl-devel-<kernel>` sections which call `find-debuginfo.sh` appropriately.  Then disable the default debuginfo generalization.

The whole thing is surprisingly complicated but it needs to be to be so flexible.  I'd suggest reading the kmod2 documentation at http://rpmfusion.org/Packaging/KernelModules/Kmods2 to get a feel for how everything works.

**Comment by bprotopopov** [comment]
Thanks for the pointer, @behlendorf, I'll take a look.

**Comment by admnd** [comment]
@behlendorf  Do you know if this kmod standard thing still true in 2020? The explanation via the link above refers ultimately to a Fedora article which is now tagged as being obsolete. A bit of searching around gives no clear piece of information. My concern was if using ./configure --with-spec=redhat still make sense today, especially for CentOS/RedHat 7 / 8. Having a different RPM set with same filenames complicates a bit my local ZFS repository management.

**Comment by behlendorf** [comment]
@admnd I'm not sure how widely adopted it still is as a standard., but I think it still does make sense.    The alternative for CentOS/RedHat would be to build new kmod packages for every kernel release which is something we're not setup to do.  If you'd like to do this locally that should be absolutely fine, the `--with-spec=redhat` option is in no way required on CentOS/RedHat.
