### ISSUE TITLE
Add Grsec/PAX Image to BuildBot

### ISSUE THREAD

**Issue by sempervictus** [openzfs/zfs#5436]
There are a number of distributions out there offering rational mechanisms for using Grsec/PAX in daily life, and that number will only grow. Having a buildbot with most relevant hardening configurations enabled (disabling hidesym and RAP mostly) would be very useful in identifying things like improper memory access, PATH placement for binaries, and other nuances which will just flag the protections and skyline themselves.

Additionally, if its license compatible and reasonable to do this, the kernel build trees from those grsec builds generate a number of GCC plugins used to harden against overflows and bound behaviors as much as possible at build time. If we can lean on them during our DKMS/raw module builds, the instrumentation provided by them could be valuable, if they actually produce safer modules and binaries, even better.

**Comment by behlendorf** [comment]
I'm all for it.  Can you recommend a representative distribution which has an ec2 ami which is actively maintained?

**Comment by sempervictus** [comment]
Need to look into Ami, but we will probably want to automate custom kernel builds since distro kernels use RAP which makes out of tree modules a nightmare.

I could theoretically fork our local aur kernel package to drop all changes past grsec and set it up to track upstream linux-grsec simply using our k config to build without rap and hidesym. 

On rolling releases like arch/gentoo, keeping that image updated may require some TLC and automation too, but quite doable at regular intervals, or even in callback form on kernel package build success.




-------- Original Message --------

**Comment by behlendorf** [comment]
If most/all of the Grsec/PAX checks we care about are done at build time then this should be pretty straight forward to automate.  The [Kernel.org Built-In](http://build.zfsonlinux.org/builders/Kernel.org%20Built-in%20x86_64%20%28BUILD%29) builder already automates most of this with the [bb-build-linux.sh](https://github.com/zfsonlinux/zfs-buildbot/blob/master/scripts/bb-build-linux.sh) script.

The very latest kernel is pulled from the kernel.org git repository, it is minimally configured, the spl and zfs version are applied to it, then the whole thing is built.  We should just need to point it at the aur kernel git repository or package and tweak the configuration accordingly.

Now if you want to automatically test the resulting binaries that's more problematic since you'd need to reboot the node on to newly built kernel.  That's more challenging to automate with buildbot since if a buildslave reboots it's considered a failure.

**Comment by sempervictus** [comment]
Far as testing goes, a few scripts and bins added to the test suite to verify PIE bins PAX headers if need be, or even run simple static analysis if we detect a grsec setup.


-------- Original Message --------

**Comment by behlendorf** [comment]
We did recently add some basic pax checks in f26eb428622a6f3dc613d81faf905958e231e8b1 which are run in the `make lint` buildbot step.  We can easily extend them as needed.

So it sounds like if someone can extend/modify the existing bb-build-linux.sh script to do the needed build that's the majority of what's needed.  We don't even need to get it running in ec2 since there's no need for a clean image for every build if we're not loading the modules.

**Comment by perfinion** [comment]
I've been meaning to do this for a while. In gentoo we build hardened cloud images that should work on AWS. 
http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage4-amd64-hardened+cloud-nomultilib/

How do the buildbots work? If they are rebooted from a completely clean image every time then we can just have it pull the latest weekly image and use that so it'll be pretty up-to-date. I'm not entirely sure how to load up a .qcow2 image into AWS tho.

This should ideally be more than just a pure build test since I have on occasion caught issues at runtime with PAX_SIZE_OVERFLOW.

**Comment by behlendorf** [comment]
> How do the buildbots work? If they are rebooted from a completely clean image every time.

Yes.  They boot a clean image from an AMI for every test build.  So if an Gentoo hardened AMI could be created from the qcow2 image that should work.  It would also need [cloudinit](https://cloudinit.readthedocs.io/en/latest/) installed and configured in the AMI since this is what's used to bootstrap the buildslave.

**Comment by sempervictus** [comment]
We've used a few image builders for our openstack arch image, can probably do same for gentoo. I'm a bit under the gun for a few days, but will dig into it soon as I have a chance.


-------- Original Message --------

**Comment by perfinion** [comment]
http://distfiles.gentoo.org/experimental/amd64/openstack/
the qcow2 images are here, they already have cloud-init setup and the kernel and grub and should be completely ready to go. afaik, they are going to be added to the autobuilding soon and done weekly instead of in the experimental dir.
they were originally for openstack but should work on ec2 as well, if there should be more kernel config changes, we can get that added to future builds.

Looks like raw images can be imported as AMIs so would need to use qemu-img to convert it.
https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html

@prometheanfire is there any chance that infra can just upload those images as official AMIs directly when they are built?

I will take a look at the buildbot scripts and see what needs modifying for gentoo, its probably just a matter of deps.

**Comment by prometheanfire** [comment]
I'd ask @robbat2 about hosting those images.  It's good to know those images work on ec2 though (I haven't had a chance to test).

**Comment by robbat2** [comment]
yes, if we get the DIBs generating qcow2's as part of the `autobuilds` output (not `experimental`), then we can extend those to AMI.

I'm not certain about the cost implications of having _official_ AMIs already uploaded to Amazon however, can anybody find me a good link on that?

**Comment by behlendorf** [comment]
@robbat2 it depends on what you mean by _official_.

Making the AMI public and publishing the AMI id to the community should only cost you the AWS standard rate per-GB to store the AMI.  Likely a few cents per month in storage costs.  You won't be changed when someone spins up an instance based on that AMI.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html

If by _official_ you mean available through the AWS marketplace then I'm not sure.  They do provide a [sellers guide](http://awsmp-loadforms.s3.amazonaws.com/AWS_Marketplace_-_Seller_Guide.pdf) if you're interested in investigating that route.

**Comment by robbat2** [comment]
<hat type="gentoo-foundation-treasurer">
@prometheanfire's images were based on a 2GiB disk IIRC, so, and assuming we want both EBS-backed and Instance-store (S3).

Rough calculations (for a single weekly release):
regions: 14 (must upload to each region)
image-types: 4 (multilib/non, hardened/non)
EBS cost: $0.12/GB/month (averaged over regions)
S3 cost: $0.03/GB/month (averaged over regions)
Total: 2 * $0.15 * 14 * 4 = $16.80/month/release.

Gentoo is doing weekly releases, so keeping the last 4 would mean $67.20/month in AWS charges (the cross-account billing is unclear what happens if we delete an image while instances running from it are still running).
</hat>
