### ISSUE TITLE
zfs rollback persistence: newer snapshots persist when you rollback to older snapshots

### ISSUE THREAD

**Issue by kernelOfTruth** [openzfs/zfs#5862]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Gentoo ~amd64
Distribution Version    |  rolling release, portage 2.3.3
Toolchain Versions      | Portage 2.3.3 (python 3.4.5-final-0, unavailable, gcc-6.3.0, glibc-2.23-r3, 4.10.0-bfq x86_64)
Linux Kernel                 |  4.10
Architecture                 |  amd64 (x86_64)
ZFS Version                  |  9999 (v0.7.0-rc3) (February 16th 2017)
SPL Version                  |  9999 (v0.7.0-rc3) (January 31st 2017)

### Describe the problem you're observing
Created snapshots after compilation of different releass Android kernels / ROMs,

when wanting to rollback to a snapshot that is 7 instances behind the current one it e.g. says:

```
cannot rollback to 'home/android/kernels@04.03.2017_intelliplug': more recent snapshots or bookmarks exist
use '-r' to force deletion of the following snapshots and bookmarks:
```

### Describe how to reproduce the problem

Function/Feature limitation:

Wanting to roll back to a snapshot that is older than the latest one the older ones would be destroyed.

We need a feature that allows preservation of newer snapshots when the data in those is still needed for e.g. retrieval, similar to git branches - only on a bigger scale

**Comment by b333z** [comment]
Why not clone (equiv to git branch) instead of rollback to preserve intermediate snapshots?

**Comment by kpande** [comment]
this just seems unnecessary since it can be handled in userspace

**Comment by kernelOfTruth** [comment]
@b333z , @kpande thanks for the suggestion !

gotta see if clone offers enough flexibility to do it easily :)

**Comment by mailinglists35** [comment]
Please reopen. Most automated tools create snapshots, not clones. I find this pretty unexpected to not be able to rollback to any snapshot *and* keep the other snapshots intact.

Does this require on disk format changes?

**Comment by behlendorf** [comment]
@mailinglists35 sure.  I've gone ahead and tagged this as a feature and shorted up the subject line.  As for if it would require an on-disk format change that would really depend on how it gets implemented.  That's a definitely possibility, I'd have to think about it more.

**Comment by mailinglists35** [comment]
Can this be revisited, please?

I'm using this feature like this: I have some virtual machines running on zvols.
Sometimes I break stuff so I want to rollback to an earlier snapshot.
But I do not know to which one, so with current design I am forced to rollback one by one from the newest to the oldest, or else I would lose them all.

This makes it very difficult for me to find the right point in time to return to, because I have to try all snapshots sequentially. If I was able to restore arbitrarily snapshots, then it would be faster to find the right one to rollback from.

Thanks

**Comment by gmelikov** [comment]
> Most automated tools create snapshots, not clones

But this doesn't prevent you from creating a clone of specific snapshot.  @mailinglists35 maybe you can give example of such tools, which rollback snapshots? I don't know about any, unfortunately.

**Comment by mailinglists35** [comment]
all snapshotting tools create snapshots, not clones. besides, clones take a lot of space so are unpractical to make use of clones to protect virtual machines

**Comment by gmelikov** [comment]
@mailinglists35 clones in zfs won't require any space on creation, it will write only diffs from original snapshot on writes to clone, I don't understand what you mean here in context of this issue.

**Comment by gmelikov** [comment]
I mean create clone from snapshot when you need to find exact snapshot to rollback on.

**Comment by misterbigstuff** [comment]
what do you want revisited? i don't think the feature is very useful, no sponsor seems to want to pick it up. personally, i clone a snapshot when i need to rollback, instead of rolling back, which is an expensive operation. the bonus is that it allows me to preserve the snapshots. and they consume no space until written to..

**Comment by mailinglists35** [comment]
> 
> 
> I mean create clone from snapshot when you need to find exact snapshot to rollback on.

ah, I didn't know that. That seems to solve my issue. thank you!
