### ISSUE TITLE
NFS Stale File Handle

### ISSUE THREAD

**Issue by chjohnst** [openzfs/zfs#6197]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | CentOS
Distribution Version    | 7.3
Linux Kernel                 | 3.10.0-514.16.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.6.5.9-1
SPL Version                  | 0.6.5.9-1

### Describe the problem you're observing
Noticing a Stale File Handle error when you have one machine write to NFS and another client reading from a file that is atomically replaced with a mv operation.  I normally use ext4/xfs or btrfs and do not see this issue (although I see the counters go up on the NFS server side for stale file handles in /proc/net/rpc/nfsd)

### Describe how to reproduce the problem
A simple python script writing on one node, and a client reading the file (watch -n.1 md5sum file 2>out) after a few seconds to minutes eventually I will hit the race condition where the file is being moved to replace it.  I know that perhaps the expected behavior is to see a "Stale File Handle" but with other filesystems such as ext4, xfs and btrfs I do not see this behavior. 

import shutil
import time

while True:
  time.sleep(.5)
  shutil.copyfile('file', 'file.tmp')
  f = open('file', 'a+')
  f.write('XXXXXXXXXXXXXX\n')
  f.flush()
  shutil.move('file.tmp', 'file')

**Comment by devZer0** [comment]
is that still reproducible with 0.7.13 or 0.8.1 ?

do you also have the possibility to test with most recent centos7 including all updates?

**Comment by nanite10** [comment]
I can also confirm this behavior with ZFS 0.8.3-1 on the latest updated CentOS 7.7 running kernel 3.10.0-1062.18.1.el7.x86_64 using NFSv4. This issue does not present with XFS being the underlying filesystem. Here is the test:

1. Create files test1.txt test2.txt. Populate test1.txt with 100M of data.
2. On NFS client A, open test1.txt with less
3. On NFS client B, run a move command for mv test2.txt to test1.txt
3. On NFS client A, the opened file with less will not be able to traverse the file past 1024 lines and will indicate I/O errors.

Looking at lsof for the less process, the open file handle will now be marked as "unknown".

When performing the same test from the same clients with a filesystem using XFS, NFS client A is still able to traverse (read) the entirety of the file despite the move operation. Looking at lsof on the process, the file handle is still showing as valid.

**Comment by nanite10** [comment]
I have retested this with the latest linux 5 kernel provided on Ubuntu 20.04 (5.4.0-24-generic) and clients with the same behavior with OpenZFS 0.8.3-1. Performing the same operation to an XFS based export does not have the issue.

Not sure if this is related: https://about.gitlab.com/blog/2018/11/14/how-we-spent-two-weeks-hunting-an-nfs-bug/

FWIW - I retested on CentOS 7.7 with OpenZFS 0.7.3 and still have the same behavior.

**Comment by rfeltstykket** [comment]
Perhaps a bit off topic, but what are the NFS client mount options?  Have you tested sync vs async?  I've seen that resolve many problems with NFS+ZFS.

**Comment by nanite10** [comment]
Yes, I've tried NFSv3, NFSv4, NFSv4.1 and NFSv4.2 with sync/async, ac/noac, etc.

**Comment by nanite10** [comment]
I did further reading on this and found that it appears ZFS is working to the NFS protocol's expectation. I don't believe there's anything in the NFS protocol to guarantee where a file handle has been unlinked by another client, or on the server side, to maintain the file on the filesystem. It looks like Linux developers worked around this behavior on the VFS layer by having the server return the file descriptor of the new file. This may or may not be acceptable based on application expectations.

It would be helpful to get some feedback from the ZFS maintainers here; it looks like this behavior only presents in NFS. Would it be possible to implement the same workarounds which were done in the Linux kernel to ZFS?

IANAD, so I may be misunderstanding the changes which need to be made.

**Comment by don-brady** [comment]
@nanite10 what VFS workaround(s) are you referring to?   I took a brief look at the `struct export_operations` implemented in xfs vs zfs but don't have enough context to see any real difference.

**Comment by nanite10** [comment]
Hi Don,

Thanks for getting back to me on this issue, appreciate you looking into it. I am a systems engineer and not a developer, but the best summation I found is this article: https://about.gitlab.com/blog/2018/11/14/how-we-spent-two-weeks-hunting-an-nfs-bug/

Instead of a Stale file handle, the Linux NFS v4.0 server showed stale contents. It turns out this difference in behavior can be explained by the NFS spec. From RFC 3010:

"A filehandle may or may not become stale or expire on a rename. However, server implementors are strongly encouraged to attempt to keep file handles from becoming stale or expiring in this fashion."

NFS server on Linux with xfs / ext4 will "gracefully" handle the following scenario:

1. NFS client A has a process opens file1.txt on NFS server
2. NFS client B has a process which performs a 'mv file2.txt file1.txt' overwriting it
3. NFS client A's process will get the new file's data upon reading

Currently with ZFS as the backend filesystem, client A's process gets stale file handle upon read which breaks ZFS as being used for NFS servers where applications perform these behaviors.

This can be recreated easily in Python by doing the following:

1. On NFS client A open a python shell:
  import fcntl
  fh = open('file1.txt', 'r')
  fcntl.flock(fh, fcntl.LOCK_SH)

2. On NFS client B, perform a 'mv file2.txt file1.txt'

3. On NFS client A's python shell:
  buf = fh.read()

You will get a stale file handle error when ZFS is used.

**Comment by ogelpre** [comment]
We ran into this issue with an old mbox-setup with distributed dovecot after migrating the storage box to ZFS. We see error messages like the following:

```
Dec 13 19:51:58 imap-1 dovecot: imap($user)<...><...>: Error: file_istream.fstat(/var/mail/$user) failed: Stale file handle
Dec 13 21:00:07 imap-1 dovecot: imap($user)<...><...>: Error: Mailbox $dir: fcntl() failed with mbox: Stale file handle
Dec 13 22:42:09 imap-1 dovecot: imap($user)<...><...>: Error: Mailbox $dir: i_stream_stat() failed with mbox: Stale file handl
```

Mounting nfs shares with mount option `lookupcache=none` reduced the amount of failed access.
