### ISSUE TITLE
Problems getting kdump to work with ZFS

### ISSUE THREAD

**Issue by bendikro** [openzfs/zfs#6476]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Ubuntu
Distribution Version    | 16.04
Linux Kernel                 | 4.4.0
Architecture                 | x86
ZFS Version                  | 0.6.5.6-0ubuntu16
SPL Version                  | 0.6.5.6-0ubuntu4

### Describe the problem you're observing

A lot of issues have been reported about kdump-tools package failing to install on Ubuntu, such as 
https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1661629

As far as I understand, the problem is that the bash function `dep_add_modules_mount` in `/usr/share/initramfs-tools/hook-functions` (initramsfs-tools-core package) doesn't support ZFS.

By adding `MODULES=most` to `/usr/share/initramfs-tools/conf-hooks.d/zfs`, the error goes away since the `dep_add_modules_mount` function is no longer called.

How should this be solved? Should `MODULES=most` be added by default in the ZFS package?

After resolving this issue, I still have problems getting kdump to save a crash dump, presumably because of ZFS or lack of support for ZFS in kdump?

I've basically followed these instructions: https://help.ubuntu.com/lts/serverguide/kernel-crash-dump.html
Doing this on an Ubuntu VM with ext4 filesystem works, but natively with ZFS on root results only in a `/var/crash/kexec_cmd` file containing `/sbin/kexec -p --command-line="BOOT_IMAGE=/ROOT/ubuntu@/boot/vmlinuz-4.4.0-79-generic root=ZFS=rpool/ROOT/ubuntu ro boot=zfs bootfs=rpool/ROOT/ubuntu irqpoll nr_cpus=1 nousb systemd.unit=kdump-tools.service" --initrd=/var/lib/kdump/initrd.img /var/lib/kdump/vmlinuz`

I do understand that this may not be a bug in the ZFS code/package, but it would still be very beneficial for everyone to sort this issue out.

Any hints on how to debug this further to figure out the problem?

**Comment by behlendorf** [comment]
> I still have problems getting kdump to save a crash dump, presumably because of ZFS or lack of support for ZFS in kdump?

My suggestion would be to start here and try and determine what exactly is going wrong.  My understanding of kdump is that it doesn't require any special support from the filesystem.  So I'd expect it to work with ZFS, it may be a case of updating the scripts to be aware that ZFS is a valid kdump target.

If it does turn out this is failing because of missing functionality in ZFS, as a wild guess because O_DIRECT isn't supported, we can definitely look in to getting that functionality added.  But beyond adding the needed core functionality to ZFS this is really something only the distribution can comprehensively fix.

**Comment by jgallag88** [comment]
For what it's worth, I've been able to get a crash dump of an Ubuntu 18.04 machine that is using ZFS on root. As mentioned above, I had to add `MODULES=most` to `/usr/share/initramfs-tools/conf-hooks.d/zfs`, but I didn't need to make any other configuration changes to accommodate ZFS. (I did have to change the amount of memory reserved for the crash kernel, but that's unrelated to ZFS.)

**Comment by ccoager** [comment]
This is affecting me too but on Ubuntu 18.04. I did find a bug upstream though, https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1778844

**Comment by jgallag88** [comment]
@ccoager I'm not sure that https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1778844 is related to this issue, since that doesn't have any mention of ZFS.

@bendikro The upstream bug you mentioned (https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1661629) has been fixed in 18.04. We have been able to successfully generate a crash dump on a system using ZFS on root without adding `MODULES=most`. We weren't able to do before that issue was fixed. Do you have any objection to closing this issue at this point?

**Comment by bendikro** [comment]
@jgallag88 
I haven't tested it myself, but if the ticket has been resolved I'd say this ticket can be closed.
