### ISSUE TITLE
Implement swap file support

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#666]
Currently, swapon fails on swap files with an "invalid arguments" error. It looks like we can support for swap files by implementing bmap in ./module/zfs/zpl_file.c. The simplicity of this interface might make it easier to debug issue #342.

**Comment by Ambyjkl** [comment]
Btrfs now support swap files, so it would be nice to also have support in openzfs, especially since Windows essentially only supports "swap" files (pagefile.sys and hiberfile.sys).

**Comment by lundman** [comment]
Ah what? I've not yet looked at swap-file support in Windows, but it is not particularly difficult, the requests come into IRP_MJ_READ and IRP_MJ_WRITE with PAGING flag set on. Won't be an issue, but I think this issue is more focused on the Linux version.

But the btrfs guide still says `From kernel 5.0+ btrfs have native swap files support, but with some limitations. Swap file - must be fully allocated as NOCOW with no compression on one device.` which makes it pretty useless, better to use zvol and swap device no?
