### ISSUE TITLE
root pool import now takes much longer to import at boot.

### ISSUE THREAD

**Issue by VERTlG0** [openzfs/zfs#6710]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Gentoo
Distribution Version    | 
Linux Kernel                 | 4.13.4-gentoo
Architecture                 | x86_64
ZFS Version                  | 0.7.0-98_g01ff0d75
SPL Version                   | 0.7.0-13_ge8474f9

### Describe the problem you're observing
At boot, importing my root pool now takes considerably longer. Once "Importing ZFS pool rpool" is shown on the screen 36 seconds go by before it seems to starts to import the pool. This used to take 2-3 seconds. 
### Describe how to reproduce the problem
I rebooted after the first boot, and the same thing occurs. Ive also used the system for the day, and rebooted and still the same. Ive rebooted three times in a row to see if it would go back to being a fast import but still the same on all three reboots. 
### Include any warning/errors/backtraces from the system logs

heres a video of me booting the system, importing, and then repeating teh boot process a second time. https://www.youtube.com/watch?v=-YhIAJNj6hQ

**Comment by bunder2015** [comment]
It appears that newer versions of zfs have a dependency on udev during imports, which isn't present during boot when using genkernel (which uses busybox mdev).

https://gist.githubusercontent.com/bunder2015/3798f992e67231bec0ca9b24372e0db4/raw/b748848699accdac06c960f9dae446ece6300207/zpool.strace.3569
https://gist.githubusercontent.com/bunder2015/3798f992e67231bec0ca9b24372e0db4/raw/b748848699accdac06c960f9dae446ece6300207/zpool.strace.3570
https://gist.githubusercontent.com/bunder2015/3798f992e67231bec0ca9b24372e0db4/raw/b748848699accdac06c960f9dae446ece6300207/zpool.strace.3571

Dracut doesn't have this problem because they use udev.
