### ISSUE TITLE
zpool import unique exit code when importable with force

### ISSUE THREAD

**Issue by tanabarr** [openzfs/zfs#6743]
When MMP / `multihost=on` , and a pool has not been cleanly exported (e.g. power loss while pool is imported). Another host can import using `-f` and `zpool import` error message reflects that. Would it be possible for the exit code from `zpool import` to be unique in this situation to aid in programmatic detection rather than parsing the stderr?

**Comment by tanabarr** [comment]
related to https://github.com/zfsonlinux/zfs/issues/6727

**Comment by richardelling** [comment]
Unfortunately, it is not feasible to have the zpool command reflect all of the hundreds of possible errors or incomplete sub-operations in an exit code. For this reason, people who develop appliances must parse the errors and error events that they are concerned about.

Another way to look at this, a pool import can trigger thousands of operations, some of which may fail while some may succeed. But it is not simple to declare for all consumers which operations should trigger a backout of the import or other failure handling.  The way the code is implemented, many of the operations are recursive, which makes this problem even more difficult to solve with a top-level error code.

This is true for both zfs and zpool commands. Note that people who do make appliances are known to write interfaces that are not running the zpool/zfs command line. This allows finer grained management of the various operations and the resulting error handling is a matter of reading nvlists rather than screen-scraping an unstable terminal output. For example, you will find parsing zpool's status output to be extremely difficult.

**Comment by tanabarr** [comment]
thank you for the reply and I appreciate the limitations you are describing

**Comment by jgrund** [comment]
@richardelling I'm presume you are describing writing against the `libzfs` / `libzfs_core` APIs?

**Comment by richardelling** [comment]
libzfs/libzfs_core is a starting point
