### ISSUE TITLE
High cpu usage of dbuf_evict for small random reads

### ISSUE THREAD

**Issue by woquflux** [openzfs/zfs#6952]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | Redhat
Distribution Version    | 7.2
Linux Kernel                 | 3.10.0-327.el7.x86_64
Architecture                 | 
ZFS Version                  | 0.6.4.2
SPL Version                  |  0.6.4.2

### Describe the problem you're observing
Terrible Performance with SSD x 18 (Intel S3500)

### Describe how to reproduce the problem
CPU usage of rngd is 100%

### Include any warning/errors/backtraces from the system logs
![image](https://user-images.githubusercontent.com/30719174/33937415-62c584fa-e03e-11e7-8e6c-31ae6a1c1f4e.png)

![image](https://user-images.githubusercontent.com/30719174/33937339-05621756-e03e-11e7-99ef-a4c2fa4583ae.png)

**Comment by behlendorf** [comment]
This was addressed in the zfs-0.7 series.  Alternately if you must run zfs-0.6. you should be able to cherry pick these two patches zfsonlinux/spl@0b43696e6676391e5bee8ba49e76e599bac1d89d and zfsonlinux/spl@0d267566650d89bde8bd5ec4665749810d5bafc7.

**Comment by woquflux** [comment]
There is another problem in the 0.7.3, dbuf_evict process CPU usage is 100%  

![image](https://user-images.githubusercontent.com/30719174/33972751-74a18076-e0ba-11e7-92bc-0a8ade1177f0.png)

**Comment by behlendorf** [comment]
@woquflux that's definitely something we're going to want to look in to further optimizing.  This particular small random read test case is pushing that dbuf cache eviction code to the limit on your system.  Can you post the output of `perf top -p <dbuf_evict pid>` from you system when it's running this workload.  That should let us isolate exactly which functions are consuming those cycles and why.

I've also changed the title of this issue to reflect the second issue you've mentioned rather than opening a new issue for it.

**Comment by woquflux** [comment]
![qq20171215-121415](https://user-images.githubusercontent.com/30719174/34026509-842fa270-e191-11e7-8209-48e315cb92fc.png)

@behlendorf Thanks for your reply. I had enough devices for test if you want more information

**Comment by behlendorf** [comment]
@woquflux thanks for the profiling data.

**Comment by richardelling** [comment]
While not a solution, we are interested in understanding whether and how we can use dbufstats to track dbuf-related pathologies. Could you add the output of `cat /proc/spl/kstat/zfs/dbufstats` before and after experiments?
