### ISSUE TITLE
Missing parameter descriptions in ZFS-Module-Parameters man page

### ISSUE THREAD

**Issue by abraunegg** [openzfs/zfs#7034]
The following zfs module parameters are missing from the zfs-module-parameters man page (updated 28th Oct 2017) using ZFS 0.7.5:

* dbuf_cache_hiwater_pct
* dbuf_cache_lowater_pct
* dbuf_cache_max_bytes
* dbuf_cache_max_shift
* dmu_object_alloc_chunk_shift
* send_holes_without_birth_time
* zfs_abd_scatter_enabled
* zfs_abd_scatter_max_order
* zfs_compressed_arc_enabled
* zfs_sync_taskq_batch_pct

Happy to create a documentation patch for the man pages if someone can send me the a description of what the module parameter is, what the default should be and what valid options are if it is being changed.

Best regards,

Alex

**Comment by behlendorf** [comment]
@abraunegg thanks, that would be greatly appreciated.  Each of these module options is described in the source code so I'd suggest starting with that and adapting it to be more useful to a user/administration rather than a ZFS developer.

* dbuf_cache_hiwater_pct
* dbuf_cache_lowater_pct
* dbuf_cache_max_bytes
* dbuf_cache_max_shift
  https://github.com/zfsonlinux/zfs/blob/master/module/zfs/dbuf.c#L96
* dmu_object_alloc_chunk_shift
  https://github.com/zfsonlinux/zfs/blob/master/module/zfs/dmu_object.c#L35
* send_holes_without_birth_time - alias for send_holes_without_birth_time
* zfs_abd_scatter_enabled
* zfs_abd_scatter_max_order
  https://github.com/zfsonlinux/zfs/blob/master/module/zfs/abd.c#L26
* zfs_compressed_arc_enabled
  https://github.com/zfsonlinux/zfs/blob/master/module/zfs/arc.c#L141..L147
* zfs_sync_taskq_batch_pct
  https://github.com/zfsonlinux/zfs/blob/master/module/zfs/dsl_pool.c#L133
