### ISSUE TITLE
scrub found mirrored file with checksum error on both copies

### ISSUE THREAD

**Issue by array42** [openzfs/zfs#7075]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Fedora
Distribution Version    |  26
Linux Kernel                 |  4.14.11-200.fc26.x86_6
Architecture                 |  x86_64
ZFS Version                  |  0.7.5-1 (zfs, 0.7.5, 4.14.11-200.fc26.x86_64, x86_64: installed)
SPL Version                  |  0.7.5-1 (spl, 0.7.5, 4.14.11-200.fc26.x86_64, x86_64: installed)

### Describe the problem you're observing
I ran a scrub. A file turned out to have uncorrectable checksum errors. The error is listed to be in a snapshot. So does this also mean the same file from another snapshot is also defect?

At the same time I wonder how that can happen. The drives are HGST NAS drives, quite new. The machine has ECC memory. I just don't expect that both copies of a mirrored file contain a checksum error. That is the only error it found.

Also I did transfer the file in question with rsync and checksum check. So at that point it did verify the file after the transfer, so I was confident that the file is readable and everything should be well and just good as usual.

So.. is there an error with the checksum calculation itself? Impossible? Possible?
### Describe how to reproduce the problem
No idea how to reproduce.
### Include any warning/errors/backtraces from the system logs

**Comment by rincebrain** [comment]
Snapshots are copy-on-write, so any blocks that didn't change since the snapshot are going to be the same for any snapshots after it, as well as for the "live" copy, meaning that, for your case, there's only the one logical copy of the affected blocks on disk (e.g. all the snapshots where that block hasn't changed since).

What exact hardware setup are you on? I don't think "we" know of any corruption bugs in the checksum code, since I would rather expect there to be a lot of shouting if one slipped in, unless it was in a combination of edge cases that isn't automatically tested or commonly used.

If ZFS is indeed reporting a checksum error (not a read error) on both halves, that suggests that the data was mangled before it went out to the disks (or the data was mangled in the same way on both disks, which is vanishingly unlikely barring a truly hilarious unknown HW bug). What do the SMART counters look like on the two drives?

Since I don't think this is a ZFS bug, until we have more information, I'd suggest you drop by IRC (freenode.net #zfsonlinux) or the zfs-discuss@ mailing list linked from the ZoL front page, mention this thread and include the answers to the questions I've asked, and someone should be able to help you look further into how this went awry.

One final thing to remark - traditionally, rsync doesn't necessarily recheck the checksum of files if they "look" the same on both sides (e.g. same mtime/filesize) unless you explicitly use the -c flag to force rechecking, or do you have some additional checksum measure that you used after rsync was done?

**Comment by richardelling** [comment]
The checksum code uses the exact same routines for creating and checking. Thus a different result is not due to difference of code.
