### ISSUE TITLE
[dracut] zfs-generator.sh ignores legacy mountpoint

### ISSUE THREAD

**Issue by mskarbek** [openzfs/zfs#7569]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	| Fedora
Distribution Version	| 28
Linux Kernel	| 4.16.11-300.fc28
Architecture	| x86_64
ZFS Version	| zfs-0.7.9-1.fc28.x86_64
SPL Version	| spl-0.7.9-1.fc28.x86_64

### Describe the problem you're observing
System fails to boot with `sysroot.mount` error because of `-o zfsutil` being added to `mount` command for `legacy` mountpoint dataset.

### Worakaround
Comment out entire `rootflags` check in `zfs-generator.sh`: https://github.com/zfsonlinux/zfs/blob/561ba8d1b1bb1f74c0182fb95161adfec99e27a1/contrib/dracut/90zfs/zfs-generator.sh.in#L28-L34 and regenerate initramfs.

**Comment by HellScre4m** [comment]
I encountered exactly the same issue on my Gentoo with ZFS On Linux. I currently have legacy mountpoints because of systemd generator issue with zfs mounts in fstab. What actually I'm wondering about is dracut-zfs-lib.sh is handling mountpoints issue very neatly. I believe this module is redundant then. Removing module and regenearting initramfs to see what happens.

**Comment by HellScre4m** [comment]
Ok I haven't noticed both files are from the same module :D 
Also thr extra piece of code comes out if zfs-lib.sh for me (not the generator)
Have you noticed the duplicate?
I wish I can boot soon to see if it's possible  to do some code and PR.
