### ISSUE TITLE
Investigate effects of Linux WBT on ZFS

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#7787]
Linux integrated a writeback throttle mechanism:

https://lwn.net/Articles/698815/

This is a feature we might not need on zvols. Unfortunately, the symbol for disabling it with `EXPORT_SYMBOL_GPL`. We might be able to disable it by writing to sysfs, but we should first check if/how it affects us.

Also, our use of `submit_bio` on the vdevs should bypass it because it bypasses the buffer cache (and therefore is never written back), but this should be checked.

**Comment by akschu** [comment]
Just saw this while searching for zvol performance/flooding issues.

My issue (#7631) describes my ongoing problem with zvol writes completely killing the host, and I'm seeing many others having similar issues (#6890, #6736, #6330, #6265, #6888).

It seems that CONFIG_BLK_WBT would be desirable since the issue as I understand it, is that zvol writing bypasses the internal zfs throttles, but as you say, this code in theory isn't called in the case of a zvol.

So what do you mean by checked?  I'm not a kernel hacker, but I can try my workload on kernels with and without CONFIG_BLK_WBT.  Whatever I can do to help, as zvol issues are pretty painful right now.

**Comment by ryao** [comment]
@akschu Run workloads with and without it and see whether there is a difference and what that difference is.

**Comment by lunarthegrey** [comment]
I'm having performance issues on writes with zvols as @akschu is having. Writes for a few minutes on a single VM will cause my hypervisor's load to shoot up to 27. I'm unsure what to do at this point. I was hoping to put ZFS into production :(.

**Comment by akschu** [comment]
I am going to do this, just been busy with other stuff.  Probably in the next day or two.

**Comment by ryao** [comment]
I would expect the WBT stuff to slow things down rather than contribute to higher CPU usage. I don’t think this is the solution that you want.

I think my old idea of killing the zvol threads in favor of hooking things into the DMU for asynchronous operation might work here, but I cannot say when I or someone else will do it.

**Comment by akschu** [comment]
`
                             CONFIG_BLK_WBT=y                      | CONFIG_BLK_WBT=n 
                             | Iops | BW | Load                            | Iops | BW | Load
Zvol direct=1       | 229747 | 918991KB/s | 39.51       | 231382 | 925530KB/s | 36.57
Zvol direct=0       | 512062 | 2000.3MB/s | 31.72      | 511263 | 1997.2MB/s | 33.26
Dataset direct=0 | 223075 | 892301KB/s | 8.67       | 219264 | 877060KB/s | 8.55
`

I don't see any real difference with WBT.  But my testing very much shows how zvol is pretty much unusable for synchronous writes due to the load average going through the roof.

Command to run sync on zvol:
fio --name=randwrite --filename=/dev/zvol/datastore/vm/benchmark --ioengine=libaio --direct=1 --rw=write --size=30G --bs=4k --iodepth=8 --numjobs=8 --group_reporting --end_fsync=1; uptime

Command to run buffered on zvol:
fio --name=randwrite --filename=/dev/zvol/datastore/vm/benchmark --ioengine=libaio --direct=0 --rw=write --size=30G --bs=4k --iodepth=8 --numjobs=8 --group_reporting --end_fsync=1; uptime

Command to run buffered on dataset:
fio --name=randwrite --filename=/datastore/vm/benchmark --ioengine=libaio --direct=0 --rw=write --size=30G --bs=4k --iodepth=8 --numjobs=8 --group_reporting --end_fsync=1; uptime

**Comment by richardelling** [comment]
FYI, /sys/module/zfs/parameters/zvol_threads is a control over the number of concurrent threads handling zvol I/O. By default zvol_thread=32. So putting more I/Os into the queue, such as
fio's concurrent I/Os = iodepth * numjobs, means they will queue up in the block dev layer. If you
want to push more concurrency then you'll want to adjust zvol_threads then export/import the pool.

**Comment by samarium** [comment]
Given your usage case is zvol for VMs, you might want to look at http://jrs-s.net/category/open-source/zfs/ for some benchmarks on on various ZFS things, including zvol vs raw/qcow2 on ZFS datasets, zvol snapshotting etc.

**Comment by akschu** [comment]
I've seen that, but his benchmarks don't really tell us how the virtual machine was configured, and they shouldn't be configured the same for zvols and qcow images on a dataset.

Zvols benefit from native threads which aren't supported on ZFS datasets, also because zfs datasets lack O_DIRECT, the VM is configured with writeback caching (setting none calls O_DIRECT), which will obviously increase performance, but it's hard to know what the reliability cost is.  

The author suggests it's not a big deal because modern file systems journal, and even if that breaks, you would just revert another hour into the past, but I'm still skeptical.

At this point I am testing raw files on datasets, and may move there, but that doesn't mean that zvols don't have problems with large synchronous reads/writes.  A simple DD to a zvol can completely take out a machine.
