### ISSUE TITLE
zfs-0.7.9: Despite 'zfs_send_corrupt_data=1' unable to 'send | receive' or 'resume' stream with corrupted file(s)

### ISSUE THREAD

**Issue by Hypocritus** [openzfs/zfs#7905]
Expected Behavior: be able to **`send | receive`** a functional snapshot despite having a few corrupted files
_______
I developed a handful of corrupt files on a 19-drive (two missing, so 17 at that point) raidz3 bare test system through the controller becoming partially unseated from the motherboard. The event wasn't prolonged and was caught quickly. After rebooting and in the course of time I eventually came across them (to clarify, there were 17 drives of a 19-drive raidz3 **before** the controller became partially unseated; meaning there was only one parity drive before the unseating. The partial-unseating caused a loss of connection in about 3-4 more drives; the corruption was expected)

> status: One or more devices is currently being resilvered.  The pool will
> 	continue to function, possibly in a degraded state.
> .
> .
> .
> errors: Permanent errors have been detected in the following files:
> 
>         zSASCSI/zfsmount/path/to/corrupt/file1
>         zSASCSI/zfsmount/path/to/corrupt/file2
>         zSASCSI/zfsmount/path/to/corrupt/file3
>         zSASCSI/zfsmount/path/to/corrupt/file4
>         zSASCSI/zfsmount/path/to/corrupt/file5
>         zSASCSI/zfsmount/path/to/corrupt/file6

However as I knew there were only a few corrupt files, and as I was intent on recreating the array in a different configuration, I happily decided to set the new 0.7.x tunable `zfs_send_corrupt_data=1`, take a snapshot and to send the dataset to a backup array instead of potentially waiting several days for the resivers and scrubs to find the few files and then treating them.

`zfs send -evL zSASCSI/zfsmount@180908v0 | zfs receive -dus z10Tx4`

Near the end of the 2-day `send | receive` of approx 35 TB on the same hardware system to a separate backup pool, I obtained this:

> 04:59:12   32.88T   zSASCSI/zfsmount@180908v0
> internal error: Invalid exchange
> cannot receive incremental stream: checksum mismatch or incomplete stream.
> Partially received snapshot is saved.
> A resuming stream can be generated on the sending system by running:
>     zfs send -t 1-120df0f093-120-789c636064000310a500c4ec50360710e72765a526973030a47e666462c0269f96569c5a0292116080c9b321c9275596a41683649d923b832430f597e4a79766a63030a4e7496bd5f85dceb04092e704cbe725e6a6323054053b063b077bea57a515e7e697e69538185a18581a1a9419409c0e36979701e18f9cc4a2f4d4a49cfce4ecfc6c909804d43e987c6a6e526a0a500aa48f1b493c393fb7a028b5b818a20b020039e42808

Upon doing as suggested:

`
root@DRX1:/home/robbie# zfs send -t 1-120df0f093-120-789c636064000310a500c4ec50360710e72765a526973030a47e666462c0269f96569c5a0292116080c9b321c9275596a41683649d923b832430f597e4a79766a63030a4e7496bd5f85dceb04092e704cbe725e6a6323054053b063b077bea57a515e7e697e69538185a18581a1a9419409c0e36979701e18f9cc4a2f4d4a49cfce4ecfc6c909804d43e987c6a6e526a0a500aa48f1b493c393fb7a028b5b818a20b020039e42808 | zfs receive -dus z10Tx4`

I quickly get

> 
> internal error: Invalid exchange
> cannot receive incremental stream: checksum mismatch or incomplete stream.
> Partially received snapshot is saved.
> A resuming stream can be generated on the sending system by running:
>     zfs send -t 1-fe70e2f5b-120-789c636064000310a500c4ec50360710e72765a526973030a47e666462c0269f96569c5a0292116080c9b321c9275596a41603e98809c59d411298fa4bf2d34b33531818d2f3a4b56afc2e675820c97382e5f31273531918aa821d839d833df5abd28a73f34bf34a1c0c2d0c2c0d0dca0c204e079bcbcb80f0474e62517a6a524e7e72767e36484c026a1f4c3e35372935052805d2c78d249e9c9f5b50945a5c0cd1050100b35e28ae
> 

Upon increasing the error output:
(If any of the numbers in any of the following data seem a little fishy, I had to simulate a few of the numbers since I didn't save the original first set of error messages. The last set of data should be accurate)

`
root@DRX1:/home/robbie# zfs send -vP -t 1-1305484649-120-789c636064000310a500c4ec50360710e72765a526973030a47e666462c0269f96569c5a0292116080c9b321c9275596a41603e905f79a3b832430f597e4a79766a63030a4e7496bd5f85dceb04092e704cbe725e6a6323054053b063b077bea57a515e7e697e69538185a18581a1a9419409c0e36979701e18f9cc4a2f4d4a49cfce4ecfc6c909804d43e987c6a6e526a0a500aa48f1b493c393fb7a028b5b818a20b02002ce72954 | zfs receive -dus z10Tx4
`

I get

> 
> resume token contents:
> nvlist version: 0
> 	object = 0x201f348
> 	offset = 0x100000
> 	bytes = 0x18528983dea0
> 	toguid = 0x68d34e7c2a1b6e67
> 	toname = zSASCSI/zfsmount@180908v0
> 	largeblockok = 1
> 	embedok = 1
> 	compressok = 0
> full	zSASCSI/zfsmount@180908v0	3413774242240
> internal error: Invalid exchange
> cannot receive incremental stream: checksum mismatch or incomplete stream.
> Partially received snapshot is saved.
> A resuming stream can be generated on the sending system by running:
>     zfs send -t 1-130226495b-120-789c636064000310a500c4ec50360710e72765a526973030a47e666462c0269f96569c5a0292116080c9b321c9275596a41603e9173a533a832430f597e4a79766a63030a4e7496bd5f85dceb04092e704cbe725e6a6323054053b063b077bea57a515e7e697e69538185a18581a1a9419409c0e36979701e18f9cc4a2f4d4a49cfce4ecfc6c909804d43e987c6a6e526a0a500aa48f1b493c393fb7a028b5b818a20b0200ec0c28fb
> 

I can repeat that 100+ times, with no progress, however the large number number 3413774242240 will decrement around (but not exactly) 1024^2 and I will be given a brand new resume token every time.

I decided to delete the snapshot, delete the corrupt files (there ended up being about 35 bad among millions of good), take another snapshot, and to do another `send | receive`. This time I turned the send compression option on:

`zfs send -cevL zSASCSI/zfsmount@180910v0 | zfs receive -dus z10Tx4`

It passed through most of the data again, and broke again in the same manner

> 
> resume token contents:
> nvlist version: 0
> 	object = 0x201f365
> 	offset = 0x100000
> 	bytes = 0x18528a169f28
> 	toguid = 0x68d34e7c2a1b6e67
> 	toname = zSASCSI/zfsmount@180910v0
> 	largeblockok = 1
> 	embedok = 1
> 	compressok = 1
> full	zSASCSI/zfsmount@180910v0	3413764624696
> internal error: Invalid exchange
> cannot receive incremental stream: checksum mismatch or incomplete stream.
> Partially received snapshot is saved.
> A resuming stream can be generated on the sending system by running:
> 

, presumably at this dereferenced file in my new snapshot:

> errors: Permanent errors have been detected in the following files:
> 
>         zSASCSI/zfsmount@180910v0:<0x201f368>

(This dereference may have to do with the fact that I missed deleting one snapshot before taking the avove snapshot, and subsequently deleted that snapshot shortly after starting the send).

After the full resilver, this is the only corrupt file found in the array at present.

1) What can I do about this so that I do not have to wait a 3rd set of two days, potentially to find out that there is some other surprise waiting for me near the end? A user here [6711](https://github.com/zfsonlinux/zfs/issues/6711) reported

> I have managed to get zfs send to get past the corruption. I hacked zio.c to not check for corruption or compression etc. if the checksum is zero. This, along with setting
> 
> echo 1 > /sys/module/zfs/parameters/zfs_recover
> echo 1 > /sys/module/zfs/parameters/zfs_send_corrupt_data
> zfs set checksum=off lustre
> 
> has allowed the send to continue...

I am wondering if I could do something similar or better. (I do not know quite what to change in zio.c as I am not very familiar with its coding syntax)

2) As another thought and for other situations where it could potentially be useful, would it be possible/practical to commit a patch that allows the user to mount a partial (almost complete) send, so that they could rsync the little bit remaining? I certainly tried (unsuccessfully) to figure out how I might accomplish this, and it does not look like there is currently a path to do such a thing.

__________________
Ubuntu Xenial (16.04 LTS)
Kernel 4.4.0-57 x86-64

Version:
source-built 0.7.9-3ubuntu4~16.04.york0

**Comment by rincebrain** [comment]
I would _guess_ that it's objecting to some of the metadata being mangled, since ZFS uses EBADE (Invalid exchange) internally as ECKSUM, AKA "checksum error".

zfs_send_corrupt_data doesn't actually send the mangled bits that are flipped, it stubs them out with a constant value (0x2f5baddb10c, or "ZFS bad block", repeated), and so I would assume you might need zfs_recover=1 or some other kind of patch if that mangles metadata. 

_usually_, AIUI, zpool status -v gives you integers rather than names when it's talking about either things that aren't files (e.g. metadata, zvols) or things where it no longer knows the filename (...among other times, if the file has multiple hardlinks and you deleted one, since the parent field of the object only holds one of those). So if it's giving an integer, it's either something it no longer knows the path to for ~free or it's talking about metadata objects. zdb with a bunch of verbose flags on the dataset and base10 conversion of the integer will probably tell you more, e.g. zdb -vvv zSASCSI/zfsmount@180910v0 33682280

If the dataset is a volume, I have no idea what the arcana for the flags required o learn more is, I haven't used them much if ever.

You might be able to get further with zfs_recover on the receiver; zfs_send_corrupt_data literally only affects the send path so setting that on the receiver won't help you.

(I"m not an expert on send/recv, but attempting to read an incomplete send would probably be a great way to trip a bunch of assertions - I don't believe it sends things in a nice "all the metadata, then all the data" way so that you could enumerate the entire dataset even the bits that are missing their underlying data, I believe it does it as an in-order iteration over the metadata and associated data. I believe you can convince zdb to emit the raw data blocks if you ask it the right way, so you could probably forcibly read it, but at that point you might have less suffering just using GNU ddrescue on the zvol or rsync with "don't bail out on first error read" on the associated filesystems.)

I would probably say subjectively that not being able to send|recv this when you could still try rsync might be a bug in my eyes, but it could also be argued to be expected behavior since the metadata for it is literally not intact.

What I would say is definitely a bug, unless you're not saying something, is having permanent errors in files on a raidz3 that has errors on only two devices. What's zpool status have to say, precisely, about the vdev layout, and please tell me you didn't zpool clear already, though I suppose the errors would come back each scrub anyway.

**Comment by Hypocritus** [comment]
Looks like this might be a good time to try out the tunable `zfs_no_scrub_io=1` to see what I find.

**Comment by Hypocritus** [comment]
I encountered another weird happening. When I started a scrub on my 0.7.9 pool (remember that these you can -s(top)), if I issue a `zpool clear zARRAY`during the scrub, the scrub turns into a resilver, which you _can't_ stop. Wonder if it had anything to do with `zfs_no_scrub_io=1`. Well, if anyone's interested, I could test it out.

The new metadata-only scrub-turned-resilver finished in record time and found that same one bad reference from above.

I am probably just going to delete the snapshot and resend a 3rd one in order to move forward.
