### ISSUE TITLE
zpool scrub make root pool unimportable by dracut initramfs on next reboot

### ISSUE THREAD

**Issue by zpah** [openzfs/zfs#8283]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| 2019-01-09
Linux Kernel	| 4.14.83-gentoo
Architecture	| x86_64
ZFS Version	| 0.7.9-r0-gentoo
SPL Version	| 0.7.9-r0-gentoo

### Describe the problem you're observing
Command 'zpool scrub' breaks normal import of the zfs system root pool on next boot.
Boot process failed on initramfs stage (initramfs prepared by dracut).
Pool can be imported manually with command 'zpool import -f'.

Command 'zpool scrub' assign vdev label property 'hostname' (zdb -l <zpool-block-device>) to current hostname and remove property hostid. This action breaks pool import at the next boot on an initramfs stage.

**Comment by RJVB** [comment]
v0.7.12 does NOT remove the hostid property for me. You could try upgrading to see if your issue persist.

If that's not possible for you, maybe you can change your initrd (or grub) script so that it adds the -f option when importing the pool at boot?

**Comment by zpah** [comment]
Thank you for advice. I will try upgrade to v0.7.12. And post about results.

**Comment by zpah** [comment]
I am upgrade zfs to v0.7.12. Issue persist.
```
zhost# modinfo zfs | grep -iw version
version:        0.7.12-r1-gentoo
```
Command 'zpool scrub' v0.7.12 also deletes property hostid and make system pool unimportable.
```
zhost# zdb -l /dev/sda3 | grep '(hostid|hostname)'
    hostid: 8323329
    hostname: '(none)'
zhost# zpool scrub system
zhost# zdb -l /dev/sda3 | grep '(hostid|hostname)'
    hostname: 'zhost'
```

**Comment by RJVB** [comment]
Any idea how it is that your hostname property isn't set to begin with? It'd be interesting to know if your issue goes away when it's set before the scrub.

Can you reproduce this on pools that aren't you boot pool?

**Comment by zpah** [comment]
Properties zdb.hostname = '(none)' and zdb.hostid = 8323329 (0x007f0101) in my example assigned at the first pool import on the initramfs stage. On initramfs stage system hostname is not assigned yet and is configured at the standard OS initialization process (OpenRC in my case) later.

I have kernel.hostname configured before zpool scrub always. But it does not matter. Scrub always assign zdb.hostname = kernel.hostname and deletes zdb.hostid and by that breaks pool import at the initramfs stage, where kernel.hostname is not assigned yet, but hostid already exists and valid.

On non boot pool i can`t assign zdb.hostid by any way.

**Comment by RJVB** [comment]
You're right that hostname is probably not yet set when initrd imports the pool, still the property is set on my root pool. Maybe because I'm using a zfs-specific initramfs (an older version for Debian, 0.6.3-0.27~21b446~wheezy, which I keep frozen because it works).

The import command used is (last entry from the pool history):

`2018-12-20.15:00:46 zpool import -c /etc/zfs/zpool.cache -N bolaLNX -f`

The hostname info could somehow come from the cache, and note the explicit -f which probably comes from the kernel arguments in my grub.cfg:

`     linux     /vmlinuz-4.14.23-ck1-mainline-core2-rjvb root=ZFS=bolaLNX ro boot=zfs $bootfs zfsforce=1 nmi_watchdog=0 i915.preliminary_hw_support=1`

(where the zfsforce and later arguments from GRUB_CMDLINE_LINUX in /etc/default/grub).

I boot from EFI btw, but use REFind to get into the grub bootloader (allows me to boot older PCs with the same boot partition).

R

**Comment by zpah** [comment]
Thanks for reply. I consider that to use parameter '-f' to import system pool - the bad idea. It allow accidentally boot from wrong zfs pool!
Dracut imports zfs pool in zfs-specific initramfs with next command:
```
zhost# zpool history -l system
....
2019-01-15.15:21:51 zpool import -N system [user 0 (root) on (none):linux]
....
```
