### ISSUE TITLE
"configure: error: Cannot find  in your system path" looking for python{3,2}

### ISSUE THREAD

**Issue by aij** [openzfs/zfs#8300]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Nixos
Distribution Version	| unstable
ZFS Version	|  0.8.0-rc3

### Describe the problem you're observing

`./configure` prints unhelpful message

https://github.com/zfsonlinux/zfs/commit/6e72a5b9b61066146deafda39ab8158c559f5f15#diff-62ece392790db8cbacb2012ddb6f6bd7R50

### Describe how to reproduce the problem

Run run `./configure` without specifying `--with-python`, with `python3` on `$PATH` but without `/usr/bin/python{2,3}` existing.

### Include any warning/errors/backtraces from the system logs

The problematic code is [here](https://github.com/zfsonlinux/zfs/commit/6e72a5b9b61066146deafda39ab8158c559f5f15#diff-62ece392790db8cbacb2012ddb6f6bd7R50)

`--with-python=check` is the default, which results in ignoring the sytem path, checking for `/usr/bin/python3`, then `/usr/bin/python2` and finally setting `PYTHON=""` before logging `"Cannot find $PYTHON in your system path"`.

Would it be acceptable to use `which` instead of hardcoding the paths?

**Comment by behlendorf** [comment]
We shouldn't definitely fix the error message.

> Would it be acceptable to use which instead of hardcoding the paths?

Part of the reason for hard coding these paths in the `configure` check is to conform to the packaging guidelines for python shebangs in Fedora / CentOS.

https://fedoraproject.org/wiki/Packaging:Python#Multiple_Python_Runtimes

Extending the `--with-python=check` behavior to check `$PATH` as an additional fallback seems reasonable.  You'd need to also fix up the shebangs in the scripts for your environment.

**Comment by behlendorf** [comment]
Let's get @Conan-Kudo's thoughts on the best way to handle this.

As for `--with-python=no` that should work for the most part.  There are only a few things which require python and nothing critical.  1) some nice ancillary scripts (arcstat, arc_summary, etc), 2) The pyzfs library for external consumers, 3) the projects internal test suite.

**Comment by eli-schwartz** [comment]
Using `--with-python=no`, I expected zfs to simply not try to build pyzfs but build everything else. Instead, the configure check fails because there is no python command available in the minimal chroot that I used to (try to) build the zfs repo, and the check in question is unconditionally throwing errors, regardless of the value of `--with-python=no --enable-pyzfs=no`.

In fact, the latter switch defaulting to "check" does not seem to do much good if the build system unconditionally requires installing python to begin with.

...

Also the help text indicates that PYTHON=/path/to/python should work, but it doesn't as this variable is never checked until after the --with-python option checking has already overwritten it.

**Comment by Conan-Kudo** [comment]
Manually fixing shebangs is absolutely still needed. If you don't, the package build fails with an error.
