### ISSUE TITLE
ubuntu 18.04 root guide should create docker dataset

### ISSUE THREAD

**Issue by BeauSlim** [openzfs/zfs#8301]
@rlaager 

Apparently docker-ce automatically detects if /var/lib/docker is on ZFS and, without asking and with no changes to the default config, starts creating ZFS snapshots and clones of whatever dataset that directory is contained in (i.e. rpool/ROOT/ubuntu).   I would recommend that the guide include creation of a docker data set exactly like it does for nfs:

zfs create -o com.sun:auto-snapshot=false \
             -o mountpoint=/var/lib/docker                 rpool/var/docker 

Thanks for the awesome howto, by the way.

**Comment by rlaager** [comment]
Thanks for the suggestion. I've implemented that.

However, I did not set `com.sun:auto-snapshot=false`. I set that on NFS because the data is ephemeral. I'm not sure that we should exclude `/var/lib/docker` from snapshots. (Granted, `com.sun:auto-snapshot` is only honored by certain scripts, so this likely doesn't matter that much in practice anyway.) If there's a reason you think this is applicable on the docker dataset, please let me know. I'm certainly open to changing this.

Do you have any idea if this is applicable to the stock docker package too or if it is only for docker-ce specifically?

**Comment by kpande** [comment]
stock docker behaves this way on Gentoo as well. libvirt has a similar trait with `/var/lib/libvirt`.

snapshotting docker without it knowing sounds like a bad idea. it manages its own 'layers' and something tells me it would be unable to cope with random snapshots.

**Comment by BeauSlim** [comment]
Docker is new on this box, so I went ahead and double checked:  Yes, this is applicable to both the stock ubuntu 18.04 "apt install docker.io", and also if the user installs from the official docker repo.  

I suggested turning off the auto-snapshot because docker is already creating a bazillion filesystems, snapshots and clones.  Just "docker run hello-world" results in a 3 zfs filesystems/clones.   "docker run -it ubuntu" results in 6.   They do this for good reasons, but "zfs list" definitely gets a bit ridiculous.   Fortunately, it does seem to clean up after itself.
