### ISSUE TITLE
ZFS should support statx(), at least for btime

### ISSUE THREAD

**Issue by rlaager** [openzfs/zfs#8507]
Linux finally added a statx() syscall in 4.11 that can return btime ("birth time") aka crtime ("creation time"). glibc added support in 2.28. coreutils has support for statx() in master, as of two weeks ago. ZoL doesn't currently set btime in its getattr() responses as far as I can tell from the code.

If I'm following this correctly, it needs to do something like this in zfs_getattr_fast():
```
sp->result_mask |= STATX_BTIME;
sp->btime.tv_sec = ...
sp->btime.tv_nsec = ...
```

Besides btime, stat->attributes_mask has STATX_ATTR_COMPRESSED, STATX_ATTR_IMMUTABLE, STATX_ATTR_APPEND, STATX_ATTR_NODUMP, and STATX_ATTR_ENCRYPTED, most of which are the same as the FS_*_FL flags. ZFS doesn't currently set FS_ENCRYPT_FL flags, it seems, but it does set the other FS_*_FL in __zpl_ioctl_getflags().

It looks like STATX_ATTR_COMPRESSED has no FS_*_FL equivalent?

**Comment by rlaager** [comment]
@ryao has a patch in progress: https://bpaste.net/show/c1524d0f7d34

I pointed out, and he agreed, that it needs `sp->result_mask |= STATX_BTIME;`.

**Comment by ryao** [comment]
The STATX_ATTR_COMPRESSED and STATX_ATTR_ENCRYPTED file attributes have a couple of problems.The first is that other filesystems appear to allow turning on/off compression via them, so we wouldn't be matching the expected semantics. The second is that even if we (ab)use them only to report compression/encryption, we need to take a hold on the dnode to look up whether compression or encryption is used, which adds locking. That seems unnecessarily expensive given that few users will ever use this feature and the ones that do will likely want to use zdb anyway because it reports more detailed information. We can easily implement support for the other attributes, but it might be best if we pass on implementing support for STATX_ATTR_COMPRESSED and STATX_ATTR_ENCRYPTED, at least until there is an actual user for them.

That said, I have implemented support for everything but STATX_ATTR_COMPRESSED and STATX_ATTR_ENCRYPTED in #8509.

**Comment by rlaager** [comment]
Ignoring compress/encrypt seems reasonable.

**Comment by jaysonlarose** [comment]
Sorry to bother, but I was wondering what the status of this was? I'd very much like some way of getting access to a file/inode's creation time under ZFS, and this seems like the easiest path forward, considering the `statx()` `stx_btime` attribute also works for ext4.

Alternatively, is there any other method of exposing a file's ZFS creation time in userspace? I've looked high and low for such a thing, but evidently my Google-fu is not up to the task...

--Jays

**Comment by behlendorf** [comment]
There is a PR open when implements this functionality  #8509, but it needs a little polish before it can be merged.  It would be great if someone wants to pick up this work.  What's still required in described in this https://github.com/zfsonlinux/zfs/pull/8509#issuecomment-483794372.

**Comment by digitalsignalperson** [comment]
Being able to access btime will be useful. Can there be a way to mutate this? E.g. for backup tools?  With ext4 there is a debugfs request like `set_inode_field filename crtime <value>` [0]

Noticed my ZFS datasets shared over samba cifs mounted show birth time with stat. Seems this may be implemented as a pseudo-xattr, user.cifs.creationtime [1]

Also noting cifs recently adding support to mutate this "user" creation time. [2] though I'm not sure how
> 5.6 kernel (module version 2.25, released 3/29/2020, 59 changesets)
> Add support for fallocate mode 0 for non-sparse files. Allow setting owner info, DOS attributes, creation time from user space backup/restore tools.

Noting with #8509 it might be that the birth time reported by stat directly from a ZFS mount will differ from the birth time reported by stat from a CIFS mount of a ZFS dataset? Any foreseeable conflicts this could result in?


[0] https://stackoverflow.com/questions/29906359/how-can-i-set-file-creation-times-in-zfs

[1] https://superuser.com/questions/703768/is-there-really-no-way-in-linux-to-get-creation-time-for-files-on-cifs-smb-share

[2] https://wiki.samba.org/index.php/LinuxCIFSKernel

**Comment by dletai** [comment]
> Alternatively, is there any other method of exposing a file's ZFS creation time in userspace?
> --Jays

@jaysonlarose Suppose you want to know the btime (or crtime) of file _foo_ in pool _tank_ in dataset _bar_.

`sudo zdb -dddd tank/bar $(stat --format '%i' /tank/bar/foo) | grep crtime`

**Comment by jaysonlarose** [comment]
@dletai I did see that one from elsewhere on the Internet, unfortunately it requires root and a command execution to perform.

What I'm trying to do is manage a database of filesystem attributes (such as MIME type, sha512sum, various comparison hashes for images, that sort of thing. Kind of like Spotlight on Mac OS, except not), which I originally was using extended attributes for, except retrieving a few million xattrs is an order of magnitude slower than just pulling them from an SQLite database. I keyed the database to inode, which allows me to have my attributes follow the file across renames and hardlinks, but the problem I ran into is that I have no reliable way of determining whether or not any given inode has been deleted and reused (in which case I should remove the stale entries instead of allowing them to propagate to the new file). 

On filesystems such as EXT4, I can get cheap and easy access to the file creation time via the statx syscall, which I can then compare against the database to decide whether or not to invalidate the data. I have an interim workaround for filesystems such as zfs that support xattrs but not statx birthtime, where I store the filesystem inode as an xattr. If the inode xattr doesn't match the actual inode number or (far more likely) it just plain goes away, I know that I need to invalidate the data.

**Comment by dletai** [comment]
@jaysonlarose Sounds like an object store would be a better match - have you considered CEPH? Or even [manta](https://github.com/joyent/manta/) since this is a ZFS space after all :)

**Comment by almereyda** [comment]
This year's release of Fedora 34 and Ubuntu 21.10 will include a change to Nautilus that allows for displaying the statx creation time, after merging the changes that resolved these issues:

- https://gitlab.gnome.org/GNOME/nautilus/-/issues/1566
- https://gitlab.gnome.org/GNOME/glib/-/issues/1970

- Is it possible or likely that we will see some development efforts here that correlate with the planned changes at the other projects this year?
- Is Canonical's OpenZFS team aware of this issue regarding the upcoming switch to GNOME 40 for desktop installations using the experimental ZFS support?

References:

- https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-21.04-GNOME-3.38
- https://www.phoronix.com/scan.php?page=news_item&px=GNOME-40-File-Creation-Times

**Comment by digitalsignalperson** [comment]
@freqlabs thanks for working on the PR. You mention in the description "Samba wants to know birthtime." so I wonder if you or anyone here might have any insight on what samba is doing when it currently reports crtime with statx for a given file over a share to a zfs filesystem

Currently my ZFS pools are on a linux server and I have samba shares for access from a workstation

- on the server if I stat a file I can't see crtime, but can access a crtime with zdb
- on the workstation mounting a samba share to access the same file, using stat does report a crtime

I thought samba might be using some xattrs to be storing a crtime seperately, but I don't see any. Furthermore The crtime I see through the samba mount is not always consistent with the crtime I see on the server using zdb, so I'm not sure how it works

### Examples

**Scenario 1:  samba crtime differs from zdb crtime**

on server, stat a file x.txt on the zfs mount

```
Access: 2019-09-15 22:13:38.338744793 -0700
Modify: 2009-01-02 19:20:14.000000000 -0800
Change: 2019-09-15 22:13:38.338744793 -0700
Birth: -
```

using zdb instead

```
atime   Sun Sep 15 22:13:38 2019
mtime   Fri Jan  2 19:20:14 2009
ctime   Sun Sep 15 22:13:38 2019
crtime  Sun Sep 15 22:13:38 2019
```

on workstation, stat the same x.txt through the samba mount

```
Access: 2019-09-15 22:13:38.338744700 -0700
Modify: 2009-01-02 19:20:14.000000000 -0800
Change: 2009-01-02 19:20:14.000000000 -0800
Birth: 2009-01-02 19:20:14.000000000 -0800
```

Samba's showing the birth time and change time as 2009, differing from the "true" values per zdb.  Aside: the 2009 birth time is the "intuitive" one to me, as that is when the original file was created. This is what I see on my workstation through stat and visible in file managers in the "Created" column (e.g. Dolphin). Originally I used robocopy on windows to copy and preserve the timestamps when copying to these shares.


**Scenario 2:  samba crtime equals zdb crtime**

on server, stat a file y.txt on the zfs mount

```
Access: 2020-10-23 19:56:27.000000000 -0700
Modify: 2020-10-23 19:56:27.000000000 -0700
Change: 2021-04-27 17:12:02.943113079 -0700
Birth: -
```

using zdb instead

```
atime   Fri Oct 23 19:56:27 2020
mtime   Fri Oct 23 19:56:27 2020
ctime   Tue Apr 27 17:12:02 2021
crtime  Tue Apr 27 17:12:01 2021
```

on workstation, stat the same y.txt through the samba mount

```
Access: 2020-10-23 19:56:27.000000000 -0700
Modify: 2020-10-23 19:56:27.000000000 -0700
Change: 2020-10-23 19:56:27.000000000 -0700
Birth: 2021-04-27 17:12:01.852107300 -0700
```

This time, samba and zdb seem to agree for birth/crtime, and still disagree for change/ctime.


---

Cheers for anyone reading this far. Just curious how I might consider managing creation time or not going forward. Seemingly right now as-is on samba shares I can use windows tools like robocopy to preserve creation date (e.g. that's where the 2009 came from) still with zfs backed shares.

**Comment by rlaager** [comment]
@digitalsignalperson I suspect that Samba is just using the earliest of the values it sees (since there is no real crtime coming back from statx()). AFAIK, there is no way to set crtime, so if you are restoring files, they will get a newer crtime.

**Comment by digitalsignalperson** [comment]
@rlaager using the earliest date conflicts with scenario 2 (real example) where samba reports the birth time as 2021-04-27, and the earliest time is the mtime 2020-10-23

**Comment by freqlabs** [comment]
Just a guess, but Samba could be using some user xattr to keep track of it separately. @anodos325 might know what is actually going on there.

**Comment by digitalsignalperson** [comment]
Hmm right, it's probably in this user.DOSATTRIB

On the first file `getfattr --dump -m - x.txt` shows nothing, but the 2nd `getfattr --dump -m - y.txt`  shows a user.DOSATTRIB.

here https://wiki.samba.org/index.php/LinuxCIFSKernel it says under 4.9 Kernel
> Add way to query file attributes (cifs.dosattrib) and creation time (cifs.creationtime) via Linux xattrs

Googling seeing some suggest that creation time is stored in user.DOSATTRIB, but not sure how to decode it. That probably explains it though. Anyway, maybe off topic at this point. 

Also agree, don't think there's a away to modify the zfs crtime. Some old discussion here with no solution https://stackoverflow.com/questions/29906359/how-can-i-set-file-creation-times-in-zfs

**Comment by jaysonlarose** [comment]
@dletai Sorry for the delay in replying... since I'm working with files on a file system, I'd prefer it if I could just be able to use the file birth time, like I can do with ext3.

@digitalsignalperson @freqlabs Interesting that samba is using an extended filesystem attribute to store that data.  I guess it's a good way to do things if you can't get at the birth time through conventional means: It'll survive renames and hardlinks, and won't survive if the inode is unlinked and subsequently recycled.  I was thinking of doing the same thing for my own implementation, (specifically by dropping something like a uuid4 into an extended attribute), but I've never bothered moving off ext3, because hey, birth time.

**Comment by digitalsignalperson** [comment]
With ext4 you can use debugfs `set_inode_field filename crtime <value>` to change crtime. Would zdb or any particular zfs tool be appropriate to consider implementing something similar?
