### ISSUE TITLE
is it normal?  50-80 % [txg_sync]

### ISSUE THREAD

**Issue by niksfirefly** [openzfs/zfs#8537]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 16.04.4 LTS
Linux Kernel	| 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ZFS Version	| 0.6.5.6-0ubuntu16
SPL Version	| 0.6.5.6-0ubuntu4

### Describe the problem you're observing
I observe high CPU load and I/O
iotop -a -P -o -d 5
gives me
50-80 % [txg_sync]
Is it normal?

**Comment by drescherjm** [comment]
No however 0.6.5.6 is pretty old.

**Comment by rlaager** [comment]
Use [zfs-discuss](http://list.zfsonlinux.org) for support.

**Comment by behlendorf** [comment]
@niksfirefly if the pool is being written to then you should expect to see cpu and I/O by consumed by the `txg_sync` thread.  How much will depend on your specific hardware, the pool configuration, which features/properties are enabled, and your workload.  This may be normal for your circumstances.

As noted above the version of ZFS included in Ubuntu 16.04 is now fairly old and many improvements have been made since it was released.  Ubuntu 18.04 contains a newer version of ZFS with these improvements so you may want to consider upgrading.

**Comment by niksfirefly** [comment]
I wonder if I disable compression for dataset it might drop cpu high load?
I dont care about size because have plenty,but
I read that compression also speed up I/O on linux ZFS
Is this true?



śr., 27 mar 2019 o 22:50 Brian Behlendorf <notifications@github.com>
napisał(a):

**Comment by drescherjm** [comment]
***I wonder if I disable compression for dataset it might drop cpu high load?*** You can try. I still say at least part of your problem is you are using a 3 year old binary. There has been a lot of development and bug fixes since March 23rd 2016.

**Comment by behlendorf** [comment]
@niksfirefly turning off compression may help reduce the cpu usage.  It's overall impact on performance 
 / capacity will depend on how compressible your files are.

**Comment by janetcampbell** [comment]
ZFS does most of its compression when the TxG commit happens.  RMW reads are done to fill in blocks, they're checksummed, compressed, allocated, and issued.

I would update ZFS and try a lower compression like lz4 if the CPU usage is an issue.  lzjb, gzip-1 and above are much more CPU-intensive.  You can also limit the CPU footprint for compression by decreasing zio_taskq_batch_pct, but this will make TxG commit take longer if heavy compression is used.
