### ISSUE TITLE
zfs recv of zvol shows volblocksize=8K while in progress

### ISSUE THREAD

**Issue by russ0519** [openzfs/zfs#8690]
### System information
Type | Version/Name
 --- | --- 
Distribution Name	|  CentOS
Distribution Version	|  7
Linux Kernel	|  3.10.0-957.5.1
Architecture	|  x86_64
ZFS Version	|  0.7.12-1
SPL Version	| 0.7.12-1

_Text below edited by @rlaager after the topic of this issue changed..._

### Describe the problem you're observing
> As you can see from the penultimate zfs get, the volblocksize was being reported as 8k, but once it finished, it was 1M.

### Describe how to reproduce the problem
See comment below: https://github.com/zfsonlinux/zfs/issues/8690#issuecomment-488347049

**Comment by kpande** [comment]
read the man page. use `send -L`.

**Comment by rlaager** [comment]
The block size is preserved. The issue here is that you're using a block size > 128K, from the large_blocks feature. Accordingly, the destination needs to support the large_blocks feature and you must use `zfs send -L`.

**Comment by russ0519** [comment]
Yes, the -L flag does seem to work, however there are some inconsistencies.  This may be something that's already well known, but tripped me up.  While the send / receive is going on, the volume will report the wrong block size.  

Here is a test script. WARNING: if you have a something called tank/source or tank/destination, it will be DESTROYED. 

```
zfs destroy tank/source -r
zfs destroy tank/destination -r
zfs create -V 1T -b 1M -s tank/source -o compression=off
zfs get volblocksize,compression tank/source
sleep 5
mkfs.xfs /dev/zvol/tank/source -s size=4k -b size=4k -d su=512k,sw=2
mount /dev/zvol/tank/source /mnt
dd if=/dev/zero of=/mnt/test.txt bs=1M count=1k
umount /mnt
zfs snapshot tank/source@sync
zfs send -L -p tank/source@sync | pv | zfs recv tank/destination & PIDZFS=$!
sleep 1
zfs get volblocksize,compression tank/destination
wait $PIDZFS
zfs get volblocksize,compression tank/destination
```

Here is the output on my system:

```
NAME         PROPERTY      VALUE     SOURCE
tank/source  volblocksize  1M        -
tank/source  compression   off       local
meta-data=/dev/zvol/tank/source  isize=512    agcount=33, agsize=8388480 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=0, sparse=0
data     =                       bsize=4096   blocks=268435456, imaxpct=5
         =                       sunit=128    swidth=256 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal log           bsize=4096   blocks=131072, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB) copied, 0.560349 s, 1.9 GB/s
NAME              PROPERTY      VALUE     SOURCE                                                                                                                         ]
tank/destination  volblocksize  8K        default
tank/destination  compression   off       received
1.53GiB 0:00:01 [ 877MiB/s] [     <=>                                                                                                                                    ]
NAME              PROPERTY      VALUE     SOURCE
tank/destination  volblocksize  1M        -
tank/destination  compression   off       received

```

As you can see from the penultimate zfs get, the volblocksize was being reported as 8k, but once it finished, it was 1M.

**Comment by rlaager** [comment]
@behlendorf Can this (zfs recv shows volblocksize=8K while in progress) be easily addressed, or is this fundamental to how receiving a stream works?

**Comment by zviratko** [comment]
Sorry for hijacking issue, but does this mean that changing the volblocksize during zfs send/recv should be easily possible? If I'm reading this (and docs) correctly, then zfs send is able to make a stream compatible with a system not capable of large_blocks, so it should be able to chunk it even more to just change it to an explicit value (like sending a 128k volblocksize ZVOL into a 8k volblocksize ZVOL.... zfs send -o volblocksize=8k or something like that).

Worth filing an enhnancement request or am I wrong and this would be too difficult to implement?

**Comment by behlendorf** [comment]
@rlaager we may be able to change this behavior but the logic surrounding how properties are handled during a receive is surprisingly involved.  I hesitate to even try and summarize it, instead let me refer anyone interested in this to the `zfs_ioc_recv_impl()` function which handles most of this.  In the end it might be small change, but I don't think it would be a quick change to develop.

@zviratko setting a smaller maximum block size (<128k) to use in the send stream should be possible.  Do you have a specific use case in mind where this would be helpful?

**Comment by zviratko** [comment]
@behlendorf Actually I have at least two very real world scenarious for both converting it to a smaller blocksize and to a larger blocksize. I think converting to a larger blocksize is something I would use quite often.

We run several private clouds that use ZVOLs as backing storage for volumes of the VMs. We offer our customers several volume types with properties like replication factor and compression but also block size (volblocksize). We also set a "default' blocksize (that one evolved over time, I know one cloud has 8k, another has 32k, the rest probably have 128k).
In the past, some customers complained about unsatisfactory performance, which usually turns out to be about blocksize being too _small_. It is very noticeable during both synthetic benchmarks and actual workloads and backups. The same storage can zfs send a 128k bs volume @800MB/s but a 8k bs volume at only 50MB/s (and sadly we're talking SSDs in the storage here).
Just recently a customer deployed a rather large (100TB) volume for their veaam backup and it's just unusably slow - turns out it used the default 8KB volblocksize.

The easiest way to correct those mistakes with minimal downtime would be to
1) snapshots those volumes
2) replicate those volumes from this snapshot using zfs send/recv (which in case of such large volumes can take literally days or even weeks!)
3) create another snapshot
4) incrementaly sync
(repeat 3 & 4 until caught up to the original volume in time)
5) stop the VM
6) swap the volumes

The last two steps only take a few minutes as the snapshot difference will be small, thus causing minimal downtime to the VM.

While it might be possible to use app-level replication in some cases or to archive the old volume and start using a brand new one, sometimes the customers expect us to deal with it or are just unable to do it.

------------------------------

Another use case would be backup volumes. Having the live ZVOLs use small blocksize can have benefits, but on a backup server it would almost always be better to have a much larger blocksize for both space overhead and performance reasons - after all, when I have to recover this volume I hit the same performance difference (even worse, my backup storage uses spinning rust). In this case I could store backups @ 1M volblocksize and convert them to whatever is needed on recovery.
And it's not unusual to have an "ASAP!!!" target to recover a volume, so restoring it with a larger blocksize might be a better immediate solution when it takes a fraction of the time.

**Comment by rlaager** [comment]
@zviratko If this is of interest to you, can you file a separate issue? These seem to be two separate things.

**Comment by zviratko** [comment]
https://github.com/zfsonlinux/zfs/issues/8704

Thanks
