### ISSUE TITLE
Broken filesystem and can't revert transactions

### ISSUE THREAD

**Issue by tatarenko** [openzfs/zfs#8986]
Distribution Name: Debian
Distribution Version: Debian GNU/Linux 10
Linux Kernel: 4.19.45 
Architecture: x86_64
ZFS Version: 0.8.1-1
SPL Version: 0.8.1-1

Have RAIDZ2 with 13 drives. Had closure/controller failure and 5 drives out of 13 bekame disconnected. After couple server reset and HDD's transfering to another brand new server, got this message:
```
cannot import 'data': I/O error
Recovery is possible, but will result in some data loss.
Returning the pool to its state as of **some date**
should correct the problem.  Approximately **some number** seconds of data
must be discarded, irreversibly.  Recovery can be attempted
by executing 'zpool import -F data'.  A scrub of the pool
is strongly recommended after recovery.
```
So i made zpool import -F data and everything was fine except when i made `zpool status -v` i got this:
```
errors: Permanent errors have been detected in the following files:

        data/video/400:<0x0>
```
also when i make `zpool import -d /dev data`, got this:
```
unable to fetch ZFS version for filesystem 'data/video/400'
cannot mount 'data/video/400': Resource temporarily unavailable
```
When i am trying to revert any transactions with `zpool import -d /dev -FX -T 3903520 data` got this:
```
cannot import 'data': one or more devices is currently unavailable
```
and this in /proc/spl/kstat/zfs/dbgmsg:
```
1562084934   spa.c:5616:spa_tryimport(): spa_tryimport: importing data, max_txg=3903520
1562084934   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1562084935   spa_misc.c:393:spa_load_failed(): spa_load($import, config untrusted): FAILED: no valid uberblock found
1562084935   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): UNLOADING
1562084935   spa.c:5473:spa_import(): spa_import: importing data, max_txg=3903520 (RECOVERY MODE)
1562084935   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1562084935   spa_misc.c:393:spa_load_failed(): spa_load(data, config untrusted): FAILED: no valid uberblock found
1562084935   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): UNLOADING
```
This FS got 19TB of data i really don't want to lose. I am really want to restore/recover/dump them somehow.

**Comment by kpande** [comment]
you could try importing with a different version of ZFS but chances are you will be restoring from backup, that is DMU dnode object corruption.

**Comment by tatarenko** [comment]
Don't have backup. Which version i shuld try?

**Comment by DurvalMenezes** [comment]
@kpande:
> that is DMU dnode object corruption.

Given the `FAILED: no valid uberblock found` message that @tatarenko posted above, I think we're actually seeing VDEV-level corruption (possibly a large swath of disk blocks got overwritten when his controller/enclosure failed).

That is, if the txg submitted with the -T option is actually a valid I've one. @tatarenko , where did you get the `3903520` from?

Anyway, let the me stress the advice that @GregorKopka  already gave you on the mailing list: make a sector-level copy of every single device on this pool before experimenting (or even trying to use the pool, as I understand other datasets became accessible after the `zfs import -F` ) any further, and then work on the copies or copies of copies. Also, of you haven't already done so, I'd immediately mount all accessible datasets in read-only mode and then **back them up** ASAP in at least two different ways and make sure those backups are safe and can be restored from, and then erase and recreate the entire pool, because whatever happened to your unmountable dataset could have messed up other parts of your disks in a way that isn't showing right now. but could make you lose data further down the road.

Alternatively, *after* you have copied your disks sector-by-sector *and* made safe backups of everything you can access already, an error-free `zpool scrub` would indicate that the rest of the pool is reasonably safe and avoid having to recreate/restore it from backups (but I'd do it just the same if it could afford the downtime).

@tatarenko:
> Don't have backup.

Ouch. Big, big mistake -- you have probably learned this by now, and I'm sorry if I sound condescending, but let me stress it anyway (for your benefit and of anyone else reading this): good, solid, *tested* (and periodically *re*tested) backups are the only thing standing between you and complete data loss. Don't let ZFS (or any other filesystem/storage technology) lull you into a false sense of security: no data is safe unless it's backed-up in at least two places (ideally three, one of them a remote location). If you care about your data, you should really make the time/money/energy investment to properly protect it, or you "will* eventually lose it -- it's just a matter of *when* (and of course those things always happen at the worst possible moments).

@tatarenko:
> Which version i should try? Is there any way to read data from it?

What is this pool's history? Have you created it with ZFS 0.8.x? If yes, I don't think you will be able to use earlier versions because AFAIK 0.8.x defines new pool properties which would make the pool unimportable by earlier versions. And the traditional advice of using another ZFS implementation (eg, running on another OS like FreeBSD) would probably not the be applicable either, as (again AFAIK) every other implementation is now based on ZoL. :-/

**Comment by tatarenko** [comment]
> That is, if the txg submitted with the -T option is actually a valid I've one. @tatarenko , where did you get the 3903520 from?
@DurvalMenezes Got it from `zdb -hh data` when i import it without `-FX -T`
I actually tryed couple of txg from command output moving from the end of pool history in the past. Nothing works.
