### ISSUE TITLE
Skip reading any metaslab-related metadata when importing a pool readonly

### ISSUE THREAD

**Issue by sdimitro** [openzfs/zfs#9095]
It would be great if we could skip reading metaslab-related data when importing the pool readonly.

The main reason for having such feature would be to help in recovery of data in failure scenarios where space-accounting and its relevant on-disk state have been corrupted but we still want to access the pool's data.

**Comment by behlendorf** [comment]
I thought this was already the case, for exactly the reason you mentioned.  But looking at the git history it appears we made a change along these lines 7fc8c33ede10f7104ca0e91d690d3ebb5236887b, but reverted it afe373260ebf96ca5482b9ccbcef5915c47d18f7 due to some `ztest` failures (which I'm sure can be fixed).  As part of this, we should make sure to add a test case for this since it would be easily to accidentally break this an not notice.
