### ISSUE TITLE
Add two ssd disks to hold slog, but zpool become slower

### ISSUE THREAD

**Issue by scott-yao2018** [openzfs/zfs#9099]
modinfo zfs |head
filename: /lib/modules/4.4.0-158-generic/kernel/zfs/zfs/zfs.ko
version: 0.7.13-1
$ uname -r
4.4.0-158-generic

root@ubuntu:~# zpool add infokist2 log mirror /dev/nvme1n1 /dev/nvme0n1
root@ubuntu:~# zpool status 
  pool: infokist2
 state: ONLINE
  scan: none requested
config:

    NAME         STATE     READ WRITE CKSUM
    infokist2    ONLINE       0     0     0
      raidz2-0   ONLINE       0     0     0
        sda      ONLINE       0     0     0
        sdb      ONLINE       0     0     0
        sdc      ONLINE       0     0     0
        sdd      ONLINE       0     0     0
        sde      ONLINE       0     0     0
        sdf      ONLINE       0     0     0
        sdg      ONLINE       0     0     0
        sdh      ONLINE       0     0     0
        sdi      ONLINE       0     0     0
        sdj      ONLINE       0     0     0
        sdk      ONLINE       0     0     0
        sdl      ONLINE       0     0     0
    logs
      mirror-1   ONLINE       0     0     0
        nvme1n1  ONLINE       0     0     0
        nvme0n1  ONLINE       0     0     0

errors: No known data errors
sudo fio -filename=/infokist2/test1  -iodepth 1 -thread -rw=randrw -rwmixread=70 -ioengine=psync -bs=16k -size=100G -numjobs=8 -runtime=600 -group_reporting -name=randrw_70read_16k

before move slog to 2 ssd disks, the rand iops is 197, after move slog to 2 SSD disk, the IOPS is 132, why? suppose the moving slog to other to improve the performance.
use zpool iostat to check, the two disks are not used, there is no IO on them, What's wrong?

scutech@ubuntu8264:~$ zpool iostat -v 60

               capacity     operations     bandwidth 
pool         alloc   free   read  write   read  write
-----------  -----  -----  -----  -----  -----  -----
infokist2    1.44T  42.1T  1.54K    698  19.8M  28.3M
  raidz2     1.44T  42.1T  1.54K    698  19.8M  28.3M
    sda          -      -    139     57  1.79M  2.36M
    sdb          -      -    116     58  1.45M  2.35M
    sdc          -      -    134     56  1.65M  2.35M
    sdd          -      -    143     56  1.86M  2.36M
    sde          -      -    121     60  1.52M  2.36M
    sdf          -      -    135     57  1.66M  2.35M
    sdg          -      -    139     56  1.78M  2.36M
    sdh          -      -    115     61  1.44M  2.35M
    sdi          -      -    134     58  1.65M  2.35M
    sdj          -      -    143     54  1.86M  2.37M
    sdk          -      -    121     61  1.52M  2.36M
    sdl          -      -    135     58  1.65M  2.36M
logs             -      -      -      -      -      -
  mirror         0  1.45T      0      0      0      0
    nvme1n1      -      -      0      0      0      0
    nvme0n1      -      -      0      0      0      0
-----------  -----  -----  -----  -----  -----  -----

**Comment by ghfields** [comment]
Though I will not speak to the FIO reduction in IOPS after adding SLOG devices, I want to address your usage of SLOG.  Your "zpool iostat" output is garbled by github, but I think I see you have used 2x 1.6TB disks for an slog mirror.  

Slog devices are only used when sync writes are requested (think databases and nfs).  Additionally, by default, even if a sync write did occur, it still is flushed to the pool every 5 seconds.  If your system is not incurring sync writes, this speaks to them not being used.  It also illustrates that a pair of 1.6TB drives are grossly oversized because you will not get close to this amount of sync writes in 5 seconds.

Join us on IRC or the mailing lists where we can discuss your system usage and advise other accelerating techniques such as metadata allocation classes and l2arc.
