### ISSUE TITLE
Is resuming a -R replication supported?

### ISSUE THREAD

**Issue by deliciouslytyped** [openzfs/zfs#9150]
If you interrupt a `zfs send -R ... | zfs recv -s ...` the `receive_resume_token` only exists on the individual dataset that was transferring when the replication interrupted.

From reading the man pages and asking around, it wasn't clear to me that it's possible in any form to continue the replication without either
a) sending the remaining child datasets of the parent dataset individually
b) destroying the datasets that _did_ transfer (making resumption pointless)

`recv` does not accept the `send -R` because it complains about child dataset already existing.

**Comment by kpande** [comment]
nope it only resumes the transfer that failed.

**Comment by deliciouslytyped** [comment]
I wasn't clear, is there any way to do it, not necessarily dependent on the `receive_resume_token` mechanism? Really what I want to happen here it to ignore successfully existing children and just start sending datasets that haven't been transferred yet.

**Comment by allanjude** [comment]
Because ZFS has no way to tell if you have added or removed any filesystems between the transfer and the resume, it cannot resume the -R replication, only finish the individual snapshot transfer that was interrupted.

Because `zfs send` is a unidirectional protocol (the sender never gets any messages back from the receiver), it is not possible to do this directly in ZFS. You'd need a external helper script that could compare the state of the 2 trees of datasets and determine what snapshots still need to be sent.

**Comment by kpande** [comment]
it is _possible_ to do it in ZFS by encoding the send command arguments for the stream inside the receive resume token, but this requires modification of both recv and send, and probably send stream format to let recv know which arguments were given.

**Comment by deliciouslytyped** [comment]
Good point about it being a unidirectional protocol. 

@kpande: just because you encoded the arguments doesn't really negate allan's mentioned issues? Though I don't know if the `receive_resume_token` ensures integrity of target either?

- but yeah, it seems like the bottom line is the token would need some manner of extension.

The per-dataset token isn't influenced by other datasets though, ...I'm not sure how to say this, but I feel like some amount of dynamic-ness would be involved. Having a token attached to a dataset seems convenient for various reasons, but what about a tool generated token?
