### ISSUE TITLE
install via  deb file on ubuntu sets zfs (and others) module version to 0.8.0-1 not 0.8.0-260....

### ISSUE THREAD

**Issue by IslandLife** [openzfs/zfs#9298]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 19.04 disco
Linux Kernel	| 5.0.0-25-generic
Architecture	| x86_64
ZFS Version	| 0.8.0-260_g4bbf0477a
SPL Version	| 

### Describe the problem you're observing

'make' produces .ko with an explicit version such as 0.8.0-260_g4bbf0477a
(as displayed by modinfo filename)
However if I use  'make deb'  and do dpkg -i  on the deb file the modules installed 
)() all have version number 0.8.0-1
This was not the case in recent builds  (258?)
It is then not easy to quickly identify the build (258 , 259 ,, 260 etc) of ZFS in use.

### Describe how to reproduce the problem
```
git clone https://github.com/zfsonlinux/zfs.git
cd zfs
./autogen
./configure prefix=
make
make deb
dpkg -i [lzp]*deb

modinfo on zfs.ko  in the cloned directory
modinfo on the zfs.ko  file installed under /lib/
```

```
# find /lib/ -xdev -name zfs.ko -exec ls -ld {} \; 
-rw-r--r-- 1 root root 3935568 Sep  9 17:38 /lib/modules/5.0.0-27-generic/updates/dkms/zfs.ko
-rw-r--r-- 1 root root 3935568 Sep  9 17:32 /lib/modules/5.0.0-25-generic/updates/dkms/zfs.ko

# modinfo /lib/modules/5.0.0-27-generic/updates/dkms/zfs.ko | head
filename:       /lib/modules/5.0.0-27-generic/updates/dkms/zfs.ko
version:        0.8.0-1
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS
alias:          devname:zfs
alias:          char-major-10-249
srcversion:     7F2EE84C3296C78056BAAD5
depends:        spl,znvpair,icp,zlua,zunicode,zcommon,zavl
retpoline:      Y
```

**Comment by andi8086** [comment]
I have had the same problem when installing my personal DKMS package for arch linux. The problem is, that the kernel module sources already are incorporated inside the package and built upon installing the dkms package. However, git information is then missing and git describe will not provide an update for the META information. Thus, contents of the META file are used, which generates 0.8.0-1. My solution was to update the META file itself by a patch. I don't know if this is the best approach for this problem here in general :)
