### ISSUE TITLE
Doesn't Build on Linux 5.3

### ISSUE THREAD

**Issue by lovesegfault** [openzfs/zfs#9332]
Linux 5.3 is out, and ZFS currently does not support it, if nothing else due to the version check at the beginning of the build. Figured I'd open an issue to track the support.

**Comment by dreamcat4** [comment]
It seems there are some compiler errors, looking in the `make.log` ?

https://gist.github.com/dreamcat4/ea40f86aca1ebe82ff03d9b7e123e2e3

It kinnda reminds me of some other recent kernel breakage. I would love to know what is in Tony's `0.8.2` release. In case the fix is already in there. However there is no changelog attached to it over on his fork yet.

**Comment by tonyhutter** [comment]
@dreamcat4 I have PR out with the list of patches for 0.8.2 here: https://github.com/zfsonlinux/zfs/pull/9161

That patchset is currently building for me on Ubuntu 18 with a 5.3 kernel.

**Comment by RinCat** [comment]
Applied those Linux 5.3 compat patches, works great.

**Comment by lovesegfault** [comment]
@tonyhutter Any chance the 5.3 patches can be either:
1. Merged into master (if they aren't already)
2. Bunched into a single patch so that it's easier to apply & distribute

I build ZFS from source (-9999 package on Gentoo) but it still refuses to build on 5.3

**Comment by tonyhutter** [comment]
@lovesegfault the patches are already in master.  Alternatively, you can clone my 0.8.2 branch (https://github.com/zfsonlinux/zfs/pull/9161) and build with that.
