### ISSUE TITLE
sysevent.fs.zfs.config_sync every 300 seconds (zfs_ccw_retry_interval)

### ISSUE THREAD

**Issue by themylogin** [openzfs/zfs#9734]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Raspbian (Debian)
Distribution Version	| Buster (10)
Linux Kernel	| Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Architecture	| armv7l
ZFS Version	| 0.8.2-1
SPL Version	| 0.8.2-1

### Describe the problem you're observing

I have a simple setup of pool of one HDD used for daily backups. This HDD can't sleep when it is not used (most of the day) because it performs some writes. Every ~300 seconds this happens:

```
Dec 16 2019 23:06:59.231203041 sysevent.fs.zfs.config_sync
        version = 0x0
        class = "sysevent.fs.zfs.config_sync"
        pool = "backup"
        pool_guid = 0x2afef95900f48ad9
        pool_state = 0x0
        pool_context = 0x0
        time = 0x5df80003 0xdc7e0e1 
        eid = 0x8
```

I've set `zfs_ccw_retry_interval`  in `module/zfs/spa.c` (https://github.com/zfsonlinux/zfs/blob/master/module/zfs/spa.c#L103) to `600` and it started happening every 600 seconds. I honestly have zero understanding of what's happening in that code and may be wrong, but it looks like it thinks that configuration cache file write that happens on vdev online on pool import is considered failed and is retried infinitely? (and there are no other signs of this failure)

### Describe how to reproduce the problem

Create a pool of one disk and run `zpool events -f -v {poolname}`. You'll see `sysevent.fs.zfs.config_sync` happening every 300 seconds causing disk IO even when pool is absolutely idle.

**Comment by behlendorf** [comment]
You're diagnosis looks right to me.  Is there anything non-standard about the system configuration which would make it impossible to write a `/etc/zfs/zpool.cache` file?  I see you're using Raspbian which should be fine, but since that used to mean rolling your own kernel this may be less tested terrain.

If you're game, the quickest way to get to the root cause is probably to add a little debugging.  I'd suggest starting with a small change like this to log the `spa_config_write()` arguments and error.  After rebuilding and loading the new modules you can monitor the internal log file by reading the `/proc/spl/kstat/zfs/dbgmsg` file.  Then drill down from there to determine exactly what is failing.

```diff
diff --git a/module/zfs/spa_config.c b/module/zfs/spa_config.c
index 3a65b0b..3d6f32e 100644
--- a/module/zfs/spa_config.c
+++ b/module/zfs/spa_config.c
@@ -297,8 +297,11 @@ spa_write_cachefile(spa_t *target, boolean_t removing, bool
                }
 
                error = spa_config_write(dp, nvl);
-               if (error != 0)
+               if (error != 0) {
                        ccw_failure = B_TRUE;
+                       zfs_dbgmsg("spa_config_write(%px, %px) = %d",
+                           dp, nvl, error);
+               }
                nvlist_free(nvl);
        }
 
```

**Comment by themylogin** [comment]
@behlendorf thank you, my problem is solved! I've built it with default prefix (`/usr/local`) and install script created `/usr/local/etc/zfs` but module was still trying to write to `/etc/zfs/zpool.cache` which failed with `ENOENT` because `/etc/zfs` did not exist.

**Comment by behlendorf** [comment]
I'm glad you were able to resolve the issue.  It sounds like we should consider extending the code to handle this a little more gracefully.
