### ISSUE TITLE
Fedora ZFS on root guide

### ISSUE THREAD

**Issue by georgeabr** [openzfs/zfs#9763]
The only complete guides are for ubuntu and debian.

Can someone make a complete guide for ZFS root on Fedora?
The only guides for Fedora I found are for copying source to target, with rsync, which means 2 disks, which means curmbersome.
I'd like a guide for Fedora, as for Ubuntu/Debian, with simple steps to follow for zfs on root, on single disk.
Thank you.

**Comment by kpfleming** [comment]
Fedora does not have a tool similar to `debootstrap`; if you do an Internet search for 'install fedora chroot' you'll find that there aren't any simple recipes for installing Fedora into a chroot filesystem. The recipes which exist use yum or dnf to install a set of packages to boostrap a machine, but that is very fragile because the required package list could change from one Fedora release to the next, and releases are frequent, so the guide could rapidly become out of date.

If you can find a well-documented and supported path for installing Fedora into a chroot filesystem, like `debootstrap` does for Debian or Ubuntu, then I'd be happy to help write a guide, as I'd also like to run Fedora with a ZFS root filesystem.

**Comment by georgeabr** [comment]
The below tools allow boostrapping a Fedora installation.
They should be available to install on a live Fedora, I think:
- http://0pointer.net/blog/mkosi-a-tool-for-generating-os-images.html
- http://libguestfs.org/supermin.1.html

There is also the option `dnf --installroot=<path>`:
    - Specifies an alternative installroot, relative to where all packages will be installed.   
    - Think of this like doing `chroot <root> dnf`, except using `--installroot` allows dnf to work before the chroot is created. It requires absolute path.

@kpfleming, do you think this is a good starting point?

**Comment by mskarbek** [comment]
Here is my old script, things didn't change too much since I wrote it: https://gist.github.com/mskarbek/a0701fe21d6918ebaa872a3f58e63036
I'm moving my home lab to fc32 so I can document this process but following that script should help you understand what needs to be done.

**Comment by kpfleming** [comment]
The thing that concerns me is that the list of packages to be installed is hardcoded, unlike debootstrap which knows the minimum set of packages required for a functional Debian system. Reverse-engineering the base system installation is fragile, especially with a distribution which has a new release every six months.

**Comment by mskarbek** [comment]
You can use `dnf groupinstall "Fedora Workstation"` instead of a list. `dnf grouplist` shows you available options including server, minimal, and a bunch of desktop environments.

**Comment by kpfleming** [comment]
That's very helpful, thanks! It looks like `dnf groupinstall "Minimal Install"` would produce a result very similar to what the Debian ZFS Root guide produces.

**Comment by mskarbek** [comment]
One thing in my script that differs from the standard installation is the boot loader. That script assumes the EFI scenario and will not work with legacy BIOS. For that you need to replace `systemd-boot` with GRUB.

**Comment by kpfleming** [comment]
I spent a bit of time on this over the weekend and got at least to a point where a script can be run in a Fedora Live system to install a new system, although I didn't get the bootloader parts done because I've not yet used systemd-boot and setting up grub2 for EFI is a somewhat complicated process. In any case, the script is here:

https://gist.github.com/kpfleming/05b3ba981c70f8f892e136d1bc6e1884

**Comment by gregory-lee-bartholomew** [comment]
I might be able to help with the systemd-boot part. I've done several of these. Also, syslinux with a custom patch works as a very simple replacement for systemd-boot on BIOS.

**Comment by gmelikov** [comment]
@gregory-lee-bartholomew and everybody is welcome to review guide here https://github.com/openzfs/openzfs-docs/pull/21#pullrequestreview-466080863

**Comment by gmelikov** [comment]
https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora/Fedora%20Root%20on%20ZFS.html
